window.CPO_LIGHT_SOURCE_AUDIT = [
  {
    "code": "688498.SH",
    "name": "源杰科技",
    "board": "科创板",
    "userAccess": "非主板样本/风向标",
    "chainRole": "CW光源、DFB/EML激光器芯片",
    "bottleneck": "S",
    "evidenceGrade": "强",
    "industryPosition": "光源线最敏感风向标",
    "officialEvidence": "2025年报披露主营光芯片，覆盖DFB、EML激光器及大功率硅光光源；数据中心业务收入3.93亿元，同比+719.06%。2026Q1披露受益客户需求增长，数据中心领域CW光源产品销售额增长，归母净利润同比+1153.07%。",
    "earningsSignal": "强：数据中心CW光源已直接拉动利润；但公司也提示新产品认证、商业化导入、量产爬坡、供需变化存在不能见度。",
    "supplySignal": "较强：公告提到光芯片存在短期产能缺口，CW光源需求增长。",
    "marketAwareness": "已明显关注度变化",
    "misprice": "低-中",
    "chaseRisk": "高：近20日涨幅较大，且更适合作为板块风向标。",
    "judgement": "如果7月行情从光模块上移到光源线，源杰是最重要温度计之一；但更适合作为板块温度计观察。",
    "nextAudit": "跟踪中报CW光源收入占比、毛利率、客户集中度、产能爬坡。",
    "lastDate": "20260626",
    "ret5d": "6.2%",
    "ret20d": "55.6%",
    "ret60d": "61.5%",
    "volRatio20d": "0.78"
  },
  {
    "code": "002281.SZ",
    "name": "光迅科技",
    "board": "主板",
    "userAccess": "主板样本",
    "chainRole": "FP/DFB/EML/VCSEL激光器芯片、PD/APD、光器件、光模块一体化平台",
    "bottleneck": "A-S",
    "evidenceGrade": "强",
    "industryPosition": "主板中光源/光芯片平台证据最完整",
    "officialEvidence": "2025年报披露公司拥有FP、DFB、EML、VCSEL等多种类型激光器芯片、PD/APD探测器芯片以及SiP芯片平台；高速光模块支持400G/800G/1.6T。2025年营收119.29亿元同比+44.20%，归母净利9.46亿元同比+43.10%；2026Q1归母净利同比+59.76%。",
    "earningsSignal": "强：业绩兑现明确，但仍需拆分AI数通和光芯片收入贡献。",
    "supplySignal": "较强：年报称高端光模块持续供不应求；光芯片平台能承接上游关键约束叙事。",
    "marketAwareness": "已关注度变化",
    "misprice": "中",
    "chaseRisk": "高：此前异动公告提示阶段涨幅过快；近60日涨幅显著。",
    "judgement": "这是主板样本里最需要专题观察的光源线核心映射，但不能把它当低位未关注度变化。",
    "nextAudit": "中报重点看高速数通收入占比、光芯片自供/外供、800G/1.6T毛利率和客户结构。",
    "lastDate": "20260626",
    "ret5d": "-9.7%",
    "ret20d": "11.8%",
    "ret60d": "184.4%",
    "volRatio20d": "0.95"
  },
  {
    "code": "600703.SH",
    "name": "三安光电",
    "board": "主板",
    "userAccess": "主板样本",
    "chainRole": "GaAs/InP光通讯芯片、CW光源、EML、DFB、FP、VCSEL、PD/APD",
    "bottleneck": "A-S待验证",
    "evidenceGrade": "中",
    "industryPosition": "主板潜在线索，但业绩反证明显",
    "officialEvidence": "2025年报明确列示GaAs、InP光通讯芯片及非光通讯芯片，产品包括CW光源、EML、DFB、FP、VCSEL、PD、APD，应用包括5G网络、接入网、数据中心以及AI应用场景。",
    "earningsSignal": "弱：2025年归母净利润-3.53亿元；2026Q1营收同比-32.59%，归母净利同比-68.15%，扣非净利为负。",
    "supplySignal": "待验证：产品方向相关，但尚未看到数通光源订单、客户认证、收入占比和供不应求证据。",
    "marketAwareness": "关注度提升",
    "misprice": "中-高但风险高",
    "chaseRisk": "中高：近5/20/60日均有明显涨幅，但业绩未同步验证。",
    "judgement": "可作为“主板光源线待补充候选”，不能直接上升为主攻；核心看中报是否证明AI数通光通讯芯片真的贡献收入。",
    "nextAudit": "专题观察年报分部、投资者问答、公告，确认CW/EML/DFB是否有数据中心客户和量产收入。",
    "lastDate": "20260626",
    "ret5d": "23.9%",
    "ret20d": "29.0%",
    "ret60d": "73.0%",
    "volRatio20d": "1.30"
  },
  {
    "code": "688313.SH",
    "name": "仕佳光子",
    "board": "科创板",
    "userAccess": "非主板样本/风向标",
    "chainRole": "AWG/PLC/FAU、DFB相关产品、1.6T AWG与MT-FA",
    "bottleneck": "A",
    "evidenceGrade": "强",
    "industryPosition": "无源器件+部分光芯片风向标",
    "officialEvidence": "2025年报披露光芯片及器件收入15.91亿元，其中AWG相关产品5.45亿元、DFB相关产品0.84亿元；用于400G/800G的CWDM/LANWDM AWG组件大批量出货，1.6T AWG小批量出货，800G/1.6T MT-FA批量出货。",
    "earningsSignal": "强：2025年营收同比+98.15%，归母净利同比+473.25%。",
    "supplySignal": "中强：更多体现AWG/FAU/无源器件和DFB相关产品放量，不是纯CW光源。",
    "marketAwareness": "已关注度变化",
    "misprice": "中",
    "chaseRisk": "高：近60日涨幅较大，且非主板样本。",
    "judgement": "用于观察资金是否从光源进一步扩散到AWG/FAU/无源光器件。",
    "nextAudit": "跟踪1.6T AWG、MT-FA、DFB相关产品毛利率和客户验证。",
    "lastDate": "20260626",
    "ret5d": "2.4%",
    "ret20d": "9.7%",
    "ret60d": "102.8%",
    "volRatio20d": "1.15"
  },
  {
    "code": "603083.SH",
    "name": "剑桥科技",
    "board": "主板",
    "userAccess": "主板样本",
    "chainRole": "CPO集成硅光引擎、大功率激光器CPO集成光源预研",
    "bottleneck": "A",
    "evidenceGrade": "强",
    "industryPosition": "成品模块/硅光方案映射，不是光芯片本体",
    "officialEvidence": "2025年报披露NPO/CPO技术包括基于100G/L和200G/L的CPO集成硅光引擎，以及基于大功率激光器的CPO集成光源预研和样机研发。2026Q1因高速光模块业务规模增加，归母净利同比+276.44%。",
    "earningsSignal": "强：高速光模块业绩兑现，但光源多为预研/样机表达。",
    "supplySignal": "中：年报披露关键物料储备和产能扩张；但光源本体供需需再证实。",
    "marketAwareness": "已明显关注度变化",
    "misprice": "低-中",
    "chaseRisk": "高：近20/60日涨幅显著，且有异动公告和高估值提示。",
    "judgement": "适合作为CPO方案和主板弹性观察，不应当作光源芯片关键约束纯标的。",
    "nextAudit": "中报看1.6T送样进度、CPO/NPO预研是否进入客户验证、核心原材料短缺是否影响交付。",
    "lastDate": "20260626",
    "ret5d": "14.6%",
    "ret20d": "21.1%",
    "ret60d": "135.3%",
    "volRatio20d": "1.03"
  },
  {
    "code": "002902.SZ",
    "name": "铭普光磁",
    "board": "主板",
    "userAccess": "主板样本",
    "chainRole": "ELSFP光源，CPO/NPO应用大功率激光光源方案",
    "bottleneck": "B-A待验证",
    "evidenceGrade": "中",
    "industryPosition": "有光源方案但反证强",
    "officialEvidence": "2025年报披露ELSFP光源：开发CPO/NPO应用的大功率激光光源，实现高功率、低功耗、低成本特点，已完成前期方案设计，样品投料加工中。",
    "earningsSignal": "弱：2025年亏损，2026Q1仍亏损。公司异动公告提示800G LPO订单量较小、800G NPO未量产、1.6T尚处前期。",
    "supplySignal": "弱-中：有样品/方案，但尚无量产和业绩贡献。",
    "marketAwareness": "概念已知但弱化",
    "misprice": "低",
    "chaseRisk": "中：近期走势偏弱，问题不在便宜，而在证据未闭环。",
    "judgement": "暂不作为主攻，只能放在“光源方案跟踪验证”。",
    "nextAudit": "等待订单数量、客户验证、量产进度和亏损收窄信号。",
    "lastDate": "20260626",
    "ret5d": "-18.5%",
    "ret20d": "-14.3%",
    "ret60d": "7.2%",
    "volRatio20d": "1.12"
  },
  {
    "code": "300394.SZ",
    "name": "天孚通信",
    "board": "创业板",
    "userAccess": "非主板样本/风向标",
    "chainRole": "ELS解决方案、多通道高速光引擎封装、高密度光互连",
    "bottleneck": "A",
    "evidenceGrade": "强",
    "industryPosition": "光器件/封装耦合风向标，不是纯光源芯片",
    "officialEvidence": "2025年报披露数据中心产品包括多通道高速光引擎封装集成解决方案、高密度光互连集成解决方案、ELS解决方案。",
    "earningsSignal": "强：2025年光互连元器件收入50.82亿元，占营收98.43%，同比+57.27%。",
    "supplySignal": "中强：更多体现器件、耦合、封装和ELS系统方案需求。",
    "marketAwareness": "认知度较高",
    "misprice": "低-中",
    "chaseRisk": "中：近期回落，非主板样本，作为扩散温度计。",
    "judgement": "看它不是为了买，而是判断行情是否从光模块扩散到耦合/封装/ELS。",
    "nextAudit": "跟踪高速光引擎募投收入、毛利率变化和ELS客户推进。",
    "lastDate": "20260626",
    "ret5d": "-5.5%",
    "ret20d": "-28.9%",
    "ret60d": "0.1%",
    "volRatio20d": "1.14"
  },
  {
    "code": "300502.SZ",
    "name": "新易盛",
    "board": "创业板",
    "userAccess": "非主板样本/风向标",
    "chainRole": "高速光模块、硅光、LPO/NPO/CPO全形态",
    "bottleneck": "A",
    "evidenceGrade": "强",
    "industryPosition": "成品端和新形态光互联风向标",
    "officialEvidence": "2025年报披露基于VCSEL/EML、SiPh及TFLN等技术平台，覆盖LPO、LRO、XPO、NPO、CPO等多种形态，1.6T及更高速率产品是核心增长引擎。",
    "earningsSignal": "极强：2025年营收同比+187.29%，归母净利同比+235.89%。",
    "supplySignal": "强：验证下游高端模块需求，但不是上游光源纯度标的。",
    "marketAwareness": "认知度较高",
    "misprice": "低",
    "chaseRisk": "中：非主板样本，作为高端模块需求温度计。",
    "judgement": "用来判断CPO/硅光/1.6T大方向是否继续强，不用于寻找主板光源线估值分位偏低。",
    "nextAudit": "跟踪1.6T、LPO/NPO/CPO客户导入和毛利率。",
    "lastDate": "20260626",
    "ret5d": "-2.7%",
    "ret20d": "-21.2%",
    "ret60d": "26.5%",
    "volRatio20d": "1.18"
  }
];

