window.CPO_BOTTLENECK_SEGMENTS = [
  {
    "id": "s01",
    "order": 1,
    "stage": "系统/架构源头",
    "subStage": "交换ASIC与CPO交换机架构",
    "bottleneck": "S",
    "criticality": 98,
    "role": "影响CPO是否从可插拔模块走向板上/封装内光互连，是全链条需求的源头。",
    "why": "CPO的核心不是单个光模块，而是交换ASIC、光引擎、封装、散热和系统可靠性的协同。海外路线一旦明确，会向上游光源、硅光、封装和测试扩散。",
    "globalLeaders": "Nvidia、Broadcom、Marvell、Cisco、TSMC等",
    "domesticProgress": "国内A股直接映射弱，更多作为海外技术路线和资本开支风向标。",
    "companies": "暂无强主板直接映射；用中际旭创、新易盛、剑桥科技、光迅科技等验证需求传导",
    "tradable": "间接观察",
    "evidence": "中",
    "awareness": "认知度较高",
    "mispriced": "低",
    "watch": "产业催化源",
    "supplySignal": "技术路线催化强，价格/供应紧张不直接体现在A股公司。",
    "nextAudit": "持续跟踪Nvidia/Broadcom CPO交换机路线、1.6T/3.2T节奏、云厂商资本开支。",
    "source": "CPO全产业链流程图.md；CPO三重验证模型.md"
  },
  {
    "id": "s02",
    "order": 2,
    "stage": "上游材料",
    "subStage": "InP/GaAs衬底与外延",
    "bottleneck": "S",
    "criticality": 95,
    "role": "服务DFB/EML/CW光源、探测器等有源光芯片，是高速光互连最前端材料。",
    "why": "激光器和高速有源器件对材料、外延、良率、寿命和温漂要求高，国产替代难度大；一旦光芯片紧缺，材料端会成为更上游的关键约束。",
    "globalLeaders": "Coherent、Lumentum、Sumitomo Electric、IQE等",
    "domesticProgress": "A股主板样本直接纯度不高；源杰科技、仕佳光子等非主板样本风向标能验证下游光芯片产业热度。",
    "companies": "源杰科技(非主板样本风向标)、仕佳光子(非主板样本风向标)、光迅科技(主板样本映射)、待补充：三安光电等化合物平台是否真实切入数通光源",
    "tradable": "部分主板样本/多为风向标",
    "evidence": "中-强",
    "awareness": "关注度提升",
    "mispriced": "中",
    "watch": "重点观察",
    "supplySignal": "已有光芯片/CW光源产能缺口与需求增长信号，但还不是全行业统一价格变化叙事。",
    "nextAudit": "优先专题观察主板化合物半导体公司是否有数通DFB/EML/CW光源客户、收入占比和量产证明。",
    "source": "CPO非主板样本风向标证据专题观察.md；CPO第一批证据专题观察.md"
  },
  {
    "id": "s03",
    "order": 3,
    "stage": "上游材料",
    "subStage": "SOI/SiN/SiON/Ge/SiGe硅光材料体系",
    "bottleneck": "S",
    "criticality": 94,
    "role": "承载硅光PIC中的波导、调制器、探测器和光中介层。",
    "why": "CPO走向高密度、低功耗，硅光集成几乎绕不开。真正难点在工艺平台、低损耗、耦合损耗、温漂和规模化良率。",
    "globalLeaders": "Intel Silicon Photonics、TSMC、GlobalFoundries、IMEC、Ayar Labs等",
    "domesticProgress": "A股更多是硅光模块/器件映射，材料和代工平台需要继续专题观察。",
    "companies": "新易盛(非主板样本风向标)、剑桥科技(主板样本，硅光800G/预研)、光库科技(非主板样本风向标)、仕佳光子(非主板样本风向标)、待补充：硅光代工/材料平台",
    "tradable": "部分主板样本/多为风向标",
    "evidence": "中-强",
    "awareness": "关注度提升",
    "mispriced": "中",
    "watch": "重点观察",
    "supplySignal": "更偏技术路线关键约束，未见像MLCC那样清晰的全行业价格变化。",
    "nextAudit": "把“硅光”拆成设计、晶圆制造、调制器、探测器、耦合封装，防止只看概念。",
    "source": "CPO全产业链流程图.md；cpo_mapping_data.js"
  },
  {
    "id": "s04",
    "order": 4,
    "stage": "光芯片/电芯片",
    "subStage": "DFB/EML/CW光源/外置激光源ELS",
    "bottleneck": "S",
    "criticality": 97,
    "role": "为高速光模块、硅光模块和未来CPO光引擎提供稳定光源。",
    "why": "CPO/硅光把光源可靠性、功率、寿命和耦合效率推到核心位置；CW/ELS一旦供给紧，整个光引擎交付都会受影响。",
    "globalLeaders": "Coherent、Lumentum、MACOM、Broadcom相关生态等",
    "domesticProgress": "源杰科技业绩和CW光源信号最敏感但非主板样本；光迅科技具备主板样本映射；铭普光磁有CPO/NPO光源预研但订单和业绩反证较强。",
    "companies": "源杰科技(非主板样本风向标)、光迅科技(主板样本重点观察)、仕佳光子(非主板样本风向标)、铭普光磁(主板样本但跟踪验证)",
    "tradable": "部分主板样本/风向标",
    "evidence": "强",
    "awareness": "关注度提升",
    "mispriced": "中",
    "watch": "重点观察",
    "supplySignal": "源杰科技公告口径显示数据中心CW光源需求和短期产能缺口，是目前最像“关键约束”的环节之一。",
    "nextAudit": "比较光迅科技、源杰科技、仕佳光子的光芯片产品结构、客户认证、产能爬坡和毛利率。",
    "source": "CPO非主板样本风向标证据专题观察.md；光迅科技_剑桥科技_证据专题观察.md；CPO主板上游与连接器证据专题观察.md"
  },
  {
    "id": "s05",
    "order": 5,
    "stage": "光芯片/电芯片",
    "subStage": "硅光PIC/调制器/探测器/MUX-DEMUX集成",
    "bottleneck": "S",
    "criticality": 96,
    "role": "把调制、探测、复用解复用、波导等光功能集成到芯片级平台。",
    "why": "CPO从模块化走向芯片化，PIC性能、低损耗和良率是影响路线能否商业化的关键。",
    "globalLeaders": "Intel、Broadcom、Cisco、Marvell生态、Ayar Labs、Lightmatter等",
    "domesticProgress": "国内多处于产品化/模块化映射，真正PIC平台和大规模量产能力仍需逐家公司验证。",
    "companies": "新易盛(非主板样本风向标)、剑桥科技(主板样本重点观察)、光库科技(非主板样本风向标)、仕佳光子(非主板样本风向标)、博创科技(非主板样本风向标)",
    "tradable": "部分主板样本/风向标",
    "evidence": "中-强",
    "awareness": "关注度提升",
    "mispriced": "中",
    "watch": "重点观察",
    "supplySignal": "技术壁垒强，但价格变化/供应紧张信号不如800G/1.6T模块和CW光源直接。",
    "nextAudit": "重点验证公司是有硅光PIC设计/制造/封装能力，还是只做硅光模块集成。",
    "source": "CPO非主板样本风向标证据专题观察.md；光迅科技_剑桥科技_证据专题观察.md"
  },
  {
    "id": "s06",
    "order": 6,
    "stage": "光芯片/电芯片",
    "subStage": "Driver/TIA/DSP/Retimer/SerDes电芯片",
    "bottleneck": "A",
    "criticality": 86,
    "role": "负责高速电信号驱动、接收、均衡、重定时和信号完整性。",
    "why": "低功耗高速电芯片是光互连系统性能的重要约束，尤其LPO/NPO/CPO路线会改变DSP依赖和系统设计。",
    "globalLeaders": "Broadcom、Marvell、Credo、Semtech、MaxLinear等",
    "domesticProgress": "A股直接纯度偏低，容易和泛半导体芯片混淆。",
    "companies": "待建立专题观察池：只纳入有明确数通光模块/高速互连Driver、TIA、SerDes证据的公司",
    "tradable": "待补充",
    "evidence": "弱-中",
    "awareness": "认知度较低",
    "mispriced": "高但风险高",
    "watch": "待补充",
    "supplySignal": "目前更像技术壁垒，不宜先按价格变化逻辑交易。",
    "nextAudit": "建立EIC专项清单，要求公告或年报出现数通光模块、TIA/Driver/SerDes客户或量产收入。",
    "source": "CPO全产业链流程图.md；CPO三重验证模型.md"
  },
  {
    "id": "s07",
    "order": 7,
    "stage": "光器件/无源器件",
    "subStage": "FA/FAU、AWG、PLC、MUX/DEMUX",
    "bottleneck": "A",
    "criticality": 90,
    "role": "完成多路光信号引出、分波/合波、阵列耦合和无源光路管理。",
    "why": "越往CPO/硅光走，耦合损耗、插损、串扰、温漂和一致性越影响良率；这是容易被忽视的隐形关键约束。",
    "globalLeaders": "US Conec、Senko、Fujikura、Coherent相关无源器件生态等",
    "domesticProgress": "天孚通信、仕佳光子、太辰光等是非主板样本风向标；主板纯度需要继续挖。",
    "companies": "天孚通信(非主板样本风向标)、仕佳光子(非主板样本风向标)、太辰光(非主板样本风向标)、腾景科技(非主板样本风向标)、光迅科技(主板样本映射)",
    "tradable": "少量主板样本/多为风向标",
    "evidence": "强",
    "awareness": "未充分关注度变化",
    "mispriced": "中-高",
    "watch": "重点观察",
    "supplySignal": "不是典型价格变化线，更像良率/交付关键约束线；若资金从模块向器件扩散，这里弹性可能被重估。",
    "nextAudit": "寻找主板中是否存在FAU、AWG、PLC、光耦合、精密光学元件的真实量产公司。",
    "source": "CPO非主板样本风向标证据专题观察.md；cpo_mapping_data.js"
  },
  {
    "id": "s08",
    "order": 8,
    "stage": "光引擎/加工封装",
    "subStage": "光引擎集成与主动/被动耦合",
    "bottleneck": "S",
    "criticality": 96,
    "role": "把PIC/EIC、光源、FAU、基板、散热结构集成为可交付光引擎。",
    "why": "这是CPO从概念变成量产的核心关口，难点不是“能做样品”，而是自动化对准、良率、热漂移、可靠性和成本。",
    "globalLeaders": "Broadcom生态、Coherent、Lumentum、Cisco、Intel相关硅光生态等",
    "domesticProgress": "天孚通信是光器件/精密零组件风向标；剑桥、光迅、新易盛等在模块/硅光侧可观察；主板加工封装纯标的仍需观察。",
    "companies": "天孚通信(非主板样本风向标)、光迅科技(主板样本重点观察)、剑桥科技(主板样本重点观察)、新易盛(非主板样本风向标)、待补充：精密贴装/耦合设备公司",
    "tradable": "部分主板样本/风向标",
    "evidence": "中-强",
    "awareness": "未充分关注度变化",
    "mispriced": "中-高",
    "watch": "重点观察",
    "supplySignal": "更像良率和设备关键约束，若出现客户锁单、产能扩张和交期拉长，信号会显著增强。",
    "nextAudit": "开“耦合/贴装/光引擎封装设备”专项，寻找是否有A股公司进入数通光模块客户。",
    "source": "CPO全产业链流程图.md；CPO三重验证模型.md"
  },
  {
    "id": "s09",
    "order": 9,
    "stage": "光引擎/加工封装",
    "subStage": "陶瓷外壳/氮化铝薄膜基板/高可靠封装材料",
    "bottleneck": "A",
    "criticality": 88,
    "role": "用于光通信器件外壳、基板、承载、散热和高可靠封装。",
    "why": "CPO靠近热源，光器件又对温度敏感，封装材料的热、机械、介电和加工精度会影响长期可靠性。",
    "globalLeaders": "Kyocera、NGK/NTK、CoorsTek等陶瓷封装材料企业",
    "domesticProgress": "中瓷电子是目前主板中证据最强的上游材料/封装映射，披露1.6T多层薄膜基板量产并通过客户验证。",
    "companies": "中瓷电子(主板样本重点观察)、待补充：其他陶瓷/玻璃/高导热封装材料公司",
    "tradable": "主板样本",
    "evidence": "强",
    "awareness": "未充分关注度变化",
    "mispriced": "中-高",
    "watch": "重点观察",
    "supplySignal": "目前更偏客户验证/量产关键约束，尚未形成清晰全行业价格变化叙事；但主板稀缺性高。",
    "nextAudit": "继续验证中瓷电子1.6T薄膜基板收入弹性、客户结构、产能释放，以及是否还有同类主板公司。",
    "source": "CPO主板上游与连接器证据专题观察.md"
  },
  {
    "id": "s10",
    "order": 10,
    "stage": "光引擎/加工封装",
    "subStage": "2.5D/3D异质集成、Flip-chip、共封装",
    "bottleneck": "S",
    "criticality": 93,
    "role": "实现ASIC、EIC、PIC、光源和基板的低损耗高可靠集成。",
    "why": "CPO最终要把光电热机械系统塞进更紧凑空间，共封装良率、热管理、互连损耗和可靠性影响量产边界。",
    "globalLeaders": "TSMC、Intel、Broadcom生态、ASE、Amkor等",
    "domesticProgress": "A股容易被先进封装概念泛化，直接CPO共封装证据较少。",
    "companies": "中瓷电子(材料/基板映射)、兴森科技(封装基板/玻璃基板外围映射)、待补充：先进封装公司是否有光电共封装订单",
    "tradable": "待补充/部分外围",
    "evidence": "中",
    "awareness": "认知度较低",
    "mispriced": "高但风险高",
    "watch": "待补充",
    "supplySignal": "技术路线能见度强，但A股公司映射需要严审，不能把所有先进封装都当CPO。",
    "nextAudit": "筛掉泛先进封装，保留公告明确出现光电共封装、硅光、光引擎封装、CPO客户的公司。",
    "source": "CPO全产业链流程图.md；cpo_mapping_data.js"
  },
  {
    "id": "s11",
    "order": 11,
    "stage": "测试/设备",
    "subStage": "高速测试、BER/眼图、温循老化、可靠性验证",
    "bottleneck": "A",
    "criticality": 87,
    "role": "验证高速光模块、光引擎和器件能否稳定交付。",
    "why": "当行业从样品走向大规模量产，测试时间、设备精度、自动化能力和可靠性验证会成为交付关键约束。",
    "globalLeaders": "Keysight、Anritsu、Tektronix、VIAVI等",
    "domesticProgress": "A股映射尚未完成，容易被半导体测试设备混淆。",
    "companies": "待建立专题观察池：只纳入明确服务光通信高速测试/光模块自动化测试/老化测试的公司",
    "tradable": "待补充",
    "evidence": "弱-中",
    "awareness": "认知度较低",
    "mispriced": "高但需证据",
    "watch": "待补充",
    "supplySignal": "最值得找“还没被充分定价”的方向之一，但需要用客户和产品证据确认。",
    "nextAudit": "下一步优先从光模块测试设备、老化设备、自动化耦合测试设备公司开始挖。",
    "source": "CPO全产业链流程图.md；CPO三重验证模型.md"
  },
  {
    "id": "s12",
    "order": 12,
    "stage": "成品模块",
    "subStage": "800G/1.6T高速光模块、LPO/NPO过渡方案",
    "bottleneck": "B",
    "criticality": 84,
    "role": "当前AI光通信需求较直观兑现的产品层。",
    "why": "订单、收入、毛利和客户认证最直观，但市场认知也最充分，短线容易阶段位置偏高。CPO真正扩散时，它更多是温度计和资金起点。",
    "globalLeaders": "中际旭创、新易盛、Coherent、Fabrinet等",
    "domesticProgress": "A股已有强业绩兑现，主板光迅、华工、剑桥有主板样本映射；创业板代表公司非主板样本但需要看作风向标。",
    "companies": "光迅科技(主板样本重点观察)、华工科技(主板样本重点观察)、剑桥科技(主板样本重点观察)、中际旭创/新易盛(非主板样本风向标)、铭普光磁(跟踪验证)",
    "tradable": "主板样本+风向标",
    "evidence": "强",
    "awareness": "认知度较高",
    "mispriced": "低-中",
    "watch": "温度计/精选",
    "supplySignal": "800G/1.6T需求强，部分高端光模块供需紧；但多数核心标的已被市场充分关注。",
    "nextAudit": "不要再只堆模块公司，重点看成品强势能否向光源、PIC、封装、测试扩散。",
    "source": "CPO非主板样本风向标证据专题观察.md；光迅科技_剑桥科技_证据专题观察.md；华工科技_沪电股份_业绩兑现专题观察.md"
  },
  {
    "id": "s13",
    "order": 13,
    "stage": "AI网络硬件扩散",
    "subStage": "高速PCB/CCL、连接器、光模块壳体、液冷散热",
    "bottleneck": "B-C",
    "criticality": 70,
    "role": "承接AI服务器、交换机和高速互连硬件需求，但多数不是CPO本体。",
    "why": "它们可能跟随AI网络产业热度走强，却不一定是CPO替代难度较高环节；要防止从“受益AI”误判为“CPO关键约束”。",
    "globalLeaders": "Amphenol、Molex、Rogers、Panasonic、Nitto等",
    "domesticProgress": "沪电股份、深南电路、生益科技、意华股份、中航光电、英维克等已有AI硬件映射，其中部分已充分关注度变化。",
    "companies": "沪电股份、深南电路、生益科技、意华股份、中航光电、英维克、华正新材、兴森科技等",
    "tradable": "多为主板样本",
    "evidence": "中-强",
    "awareness": "认知度较高",
    "mispriced": "低-中",
    "watch": "外围精选",
    "supplySignal": "PCB/CCL/连接器可能有供需产业热度，但应作为AI网络硬件扩散，不当作CPO核心关键约束。",
    "nextAudit": "只保留有800G/1.6T交换机、光模块壳体、CPO端口或高速互连明确证据的公司。",
    "source": "CPO材料PCB扩散线证据专题观察.md；CPO主板上游与连接器证据专题观察.md；cpo_mapping_data.js"
  },
  {
    "id": "s14",
    "order": 14,
    "stage": "系统外围",
    "subStage": "光纤光缆、通信设备、泛算力基础设施",
    "bottleneck": "C",
    "criticality": 45,
    "role": "提供通信网络基础设施和外围弹性。",
    "why": "可能被资金短期带动，但离CPO核心关键约束较远，除非出现明确AI数据中心光互连订单或产品升级。",
    "globalLeaders": "Corning、Prysmian、Fujikura等",
    "domesticProgress": "亨通光电、长飞光纤、中天科技、烽火通信等更多是外围观察。",
    "companies": "亨通光电、长飞光纤、中天科技、烽火通信、特发信息、永鼎股份、通鼎互联等",
    "tradable": "主板样本但外围",
    "evidence": "弱-中",
    "awareness": "题材扩散",
    "mispriced": "低",
    "watch": "外围/谨慎",
    "supplySignal": "不优先按CPO关键约束观察，除非出现高密度数据中心光纤连接明确紧缺。",
    "nextAudit": "暂不作为主线，只在CPO强势末端外围扩散时观察。",
    "source": "cpo_mapping_data.js"
  }
];

