window.CPO_SILICON_PHOTONICS_AUDIT = [
  {
    "code": "300502.SZ",
    "name": "新易盛",
    "board": "创业板",
    "userAccess": "非主板样本/风向标",
    "layer": "真硅光PIC产业化风向标",
    "chainRole": "SiPh/TFLN技术平台、硅光PIC技术产业化、硅光模块、LPO/NPO/CPO",
    "bottleneck": "S",
    "evidenceGrade": "强",
    "officialEvidence": "2025年报披露公司基于VCSEL/EML、SiPh及TFLN等多种技术平台，覆盖LPO、LRO、XPO、NPO、CPO等多种形态；“硅光PIC技术产业化研究”已完成项目设计及样品验证、进入小批量生产阶段，并称PIC相关技术可实现从采购组装到核心自研的跃迁。",
    "earningsSignal": "极强：2025年营收248.42亿元同比+187.29%，归母净利95.32亿元同比+235.89%。",
    "purity": "高：公告同时出现SiPh、TFLN、PIC产业化、小批量生产，但非主板样本。",
    "marketAwareness": "认知度较高/已关注度变化",
    "misprice": "低",
    "judgement": "硅光PIC线最重要风向标之一，用来判断市场是否交易真正硅光平台，而不是关注候选。",
    "nextAudit": "跟踪中报PIC相关产品是否继续从小批量向规模化推进，以及TFLN/SiPh平台收入贡献。",
    "lastDate": "20260626",
    "ret5d": "-2.7%",
    "ret20d": "-21.2%",
    "ret60d": "26.5%",
    "volRatio20d": "1.18"
  },
  {
    "code": "603083.SH",
    "name": "剑桥科技",
    "board": "主板",
    "userAccess": "主板样本",
    "layer": "主板硅光模块/CPO硅光引擎映射",
    "chainRole": "硅光800G批量发货、CPO集成硅光引擎预研、NPO/CPO样机研发",
    "bottleneck": "A-S",
    "evidenceGrade": "强",
    "officialEvidence": "2025年报披露全系列硅光800G产品实现海外核心客户批量发货；NPO/CPO技术包括基于100G/L和200G/L的CPO集成硅光引擎和基于大功率激光器的CPO集成光源预研和样机研发。",
    "earningsSignal": "强：2026Q1因高速光模块业务规模增加，归母净利润同比+276.44%。",
    "purity": "中高：更像硅光模块和CPO硅光引擎集成，不等于自有PIC平台完全闭环。",
    "marketAwareness": "认知度较高/已明显关注度变化",
    "misprice": "低-中",
    "judgement": "主板里硅光/CPO方案证据较直观，但涨幅和估值风险已高，不属于低位冷门观察。",
    "nextAudit": "中报看硅光800G客户持续性、1.6T送样、CPO/NPO预研是否进入客户验证。",
    "lastDate": "20260626",
    "ret5d": "14.6%",
    "ret20d": "21.1%",
    "ret60d": "135.3%",
    "volRatio20d": "1.03"
  },
  {
    "code": "002281.SZ",
    "name": "光迅科技",
    "board": "主板",
    "userAccess": "主板样本",
    "layer": "光芯片/探测器/光波导平台映射",
    "chainRole": "探测器芯片PD/APD、SiP芯片平台、平面光波导、AWG/VMUX/WDM等无源器件",
    "bottleneck": "A",
    "evidenceGrade": "强",
    "officialEvidence": "2025年报披露公司拥有FP/DFB/EML/VCSEL等激光器芯片、PD/APD探测器芯片以及SiP芯片平台；具备COB、混合集成、平面光波导、微光器件、MEMS器件等封装平台；无源器件包括AWG、VMUX、WDM、VOA等。",
    "earningsSignal": "强：2025年归母净利同比+43.10%，2026Q1归母净利同比+59.76%。",
    "purity": "中高：不是纯硅光PIC公司，但探测器/光波导/器件平台对CPO量产关键。",
    "marketAwareness": "认知度较高/已关注度变化",
    "misprice": "中",
    "judgement": "主板样本中比剑桥更偏上游平台，但短期已抢跑；更适合作为中报验证标的。",
    "nextAudit": "拆分高速数通、光芯片/探测器、平面光波导产品收入和客户结构。",
    "lastDate": "20260626",
    "ret5d": "-9.7%",
    "ret20d": "11.8%",
    "ret60d": "184.4%",
    "volRatio20d": "0.95"
  },
  {
    "code": "300620.SZ",
    "name": "光库科技",
    "board": "创业板",
    "userAccess": "非主板样本/风向标",
    "layer": "薄膜铌酸锂/TFLN调制器风向标",
    "chainRole": "铌酸锂调制器、光器件、高速调制方向",
    "bottleneck": "A",
    "evidenceGrade": "中待补",
    "officialEvidence": "现有映射表将其列为光器件/铌酸锂调制器映射；本轮尚未补齐官方年报PDF专题观察，不能直接给强证据。",
    "earningsSignal": "待补：需补年报和一季报官方数据。",
    "purity": "潜在较高：如果TFLN调制器证据闭环，属于硅光高速调制核心环节。",
    "marketAwareness": "关注度提升",
    "misprice": "中但需证据",
    "judgement": "这条线值得补证据，但在官方公告未审完前只做风向标，不给强结论。",
    "nextAudit": "下一步补抓光库科技年报，核实铌酸锂调制器产品、客户、收入和量产阶段。",
    "lastDate": "20260626",
    "ret5d": "-7.3%",
    "ret20d": "23.7%",
    "ret60d": "86.4%",
    "volRatio20d": "0.82"
  },
  {
    "code": "688313.SH",
    "name": "仕佳光子",
    "board": "科创板",
    "userAccess": "非主板样本/风向标",
    "layer": "AWG/PLC/FAU与DFB器件风向标",
    "chainRole": "AWG、PLC、FAU、DFB相关产品、硅光定义与无源器件",
    "bottleneck": "A",
    "evidenceGrade": "强",
    "officialEvidence": "2025年报披露AWG相关产品收入5.45亿元、DFB相关产品0.84亿元；400G/800G CWDM/LANWDM AWG组件大批量出货，1.6T AWG小批量出货，800G/1.6T MT-FA批量出货。年报对硅光定义涉及硅基调制器、探测器、光波导器件。",
    "earningsSignal": "强：2025年营收同比+98.15%，归母净利同比+473.25%。",
    "purity": "中高：更偏无源PIC/AWG/FAU，不是硅光调制器纯线，但与CPO耦合和MUX/DEMUX强相关。",
    "marketAwareness": "已关注度变化",
    "misprice": "中",
    "judgement": "非主板样本，但用于判断资金是否从硅光模块扩散到AWG/FAU/MUX-DEMUX。",
    "nextAudit": "在下一条FAU/AWG/PLC专项中重点展开。",
    "lastDate": "20260626",
    "ret5d": "2.4%",
    "ret20d": "9.7%",
    "ret60d": "102.8%",
    "volRatio20d": "1.15"
  },
  {
    "code": "300548.SZ",
    "name": "博创科技",
    "board": "创业板",
    "userAccess": "非主板样本/风向标",
    "layer": "硅光模块/光模块风向标待补",
    "chainRole": "光模块、硅光方向待补证据",
    "bottleneck": "B-A待验证",
    "evidenceGrade": "弱-中",
    "officialEvidence": "现有映射表列为光模块、硅光映射；本轮未取得足够官方年报摘录，暂不拔高。",
    "earningsSignal": "待补。",
    "purity": "待验证：需要区分硅光模块、硅光芯片平台、普通光模块。",
    "marketAwareness": "关注度提升",
    "misprice": "中但证据不足",
    "judgement": "先作为非主板样本风向标备选，不进入主线强结论。",
    "nextAudit": "补年报/问询/投资者关系，核实硅光产品阶段和收入贡献。",
    "lastDate": "20260626",
    "ret5d": "-6.9%",
    "ret20d": "9.4%",
    "ret60d": "74.3%",
    "volRatio20d": "1.01"
  },
  {
    "code": "688195.SH",
    "name": "腾景科技",
    "board": "科创板",
    "userAccess": "非主板样本/风向标",
    "layer": "精密光学/光器件待补",
    "chainRole": "精密光学元件、光通信器件、硅光耦合潜在线索",
    "bottleneck": "B-A待验证",
    "evidenceGrade": "弱-中",
    "officialEvidence": "现有映射表列为精密光学元件、光通信器件；本轮尚缺硅光PIC/调制器/探测器直接官方证据。",
    "earningsSignal": "待补。",
    "purity": "待验证：更可能在精密光学和耦合环节，而非PIC本体。",
    "marketAwareness": "低迷/回落",
    "misprice": "中高但证据不足",
    "judgement": "价格表现冷，但不能因为回落就认定估值分位偏低；需要等证据。",
    "nextAudit": "放到光耦合/精密光学专项中补证。",
    "lastDate": "20260626",
    "ret5d": "-11.7%",
    "ret20d": "-45.1%",
    "ret60d": "-36.2%",
    "volRatio20d": "0.89"
  },
  {
    "code": "300394.SZ",
    "name": "天孚通信",
    "board": "创业板",
    "userAccess": "非主板样本/风向标",
    "layer": "光引擎/耦合封装风向标",
    "chainRole": "硅光集成布局、高速光引擎、精密微光学组件、光波导器件",
    "bottleneck": "A",
    "evidenceGrade": "强",
    "officialEvidence": "2025年报称积极布局硅光集成等下一代技术路线；高速光引擎在发射/接收芯片封装基础上集成精密微光学组件、精密机械组件、隔离器、光波导器件等。",
    "earningsSignal": "强：2025年光互连元器件收入50.82亿元，占营收98.43%，同比+57.27%。",
    "purity": "中：不是PIC本体，更偏硅光集成所需的耦合、封装、光引擎。",
    "marketAwareness": "认知度较高",
    "misprice": "低-中",
    "judgement": "硅光线里看它是为了理解光引擎和耦合良率，不是PIC本体标的。",
    "nextAudit": "在光引擎/封装耦合专项中重点展开。",
    "lastDate": "20260626",
    "ret5d": "-5.5%",
    "ret20d": "-28.9%",
    "ret60d": "0.1%",
    "volRatio20d": "1.14"
  },
  {
    "code": "300308.SZ",
    "name": "中际旭创",
    "board": "创业板",
    "userAccess": "非主板样本/风向标",
    "layer": "硅光模块需求温度计",
    "chainRole": "800G/1.6T光模块，部分硅光方案",
    "bottleneck": "B",
    "evidenceGrade": "强",
    "officialEvidence": "2025年报披露800G OSFP除传统EML设计外，也采取硅光方案满足10km以内传输需求；同时介绍硅光SiPh趋势。",
    "earningsSignal": "极强：2025年归母净利润同比+108.78%。",
    "purity": "中：成品模块温度计，不是硅光PIC本体。",
    "marketAwareness": "认知度较高",
    "misprice": "低",
    "judgement": "用来确认硅光模块需求相关度，不用于挖主板认知度较低公司。",
    "nextAudit": "成品模块跟踪阶段统一处理。",
    "lastDate": "20260626",
    "ret5d": "-8.3%",
    "ret20d": "4.7%",
    "ret60d": "109.7%",
    "volRatio20d": "1.02"
  },
  {
    "code": "688498.SH",
    "name": "源杰科技",
    "board": "科创板",
    "userAccess": "非主板样本/风向标",
    "layer": "硅光光源/探测器芯片关联",
    "chainRole": "硅光光源、激光器芯片、探测器芯片定义与产品体系",
    "bottleneck": "A-S",
    "evidenceGrade": "强",
    "officialEvidence": "2025年报将硅光定义为激光器芯片作光源、硅基集成调制器和无源光路；公司主营光芯片，含激光器芯片和探测器芯片，并在数据中心CW光源放量。",
    "earningsSignal": "极强：2026Q1归母净利同比+1153.07%。",
    "purity": "中高：是硅光生态光源端，不是硅基PIC平台。",
    "marketAwareness": "已明显关注度变化",
    "misprice": "低",
    "judgement": "作为硅光生态光源端温度计，前一专项已展开。",
    "nextAudit": "光源线后续跟踪，不在本线重复专题观察。",
    "lastDate": "20260626",
    "ret5d": "6.2%",
    "ret20d": "55.6%",
    "ret60d": "61.5%",
    "volRatio20d": "0.78"
  },
  {
    "code": "000988.SZ",
    "name": "华工科技",
    "board": "主板",
    "userAccess": "主板样本",
    "layer": "光模块/光互联映射",
    "chainRole": "高速光模块、光互联业务，硅光PIC证据待补",
    "bottleneck": "B",
    "evidenceGrade": "中",
    "officialEvidence": "已有专题观察显示AI算力驱动下400G/800G/1.6T高速光模块出货提升，但本轮未看到硅光PIC/调制器/探测器直接证据。",
    "earningsSignal": "强：2026Q1预告光互联业务盈利同比增幅约120%。",
    "purity": "中低：当前更偏成品模块/光互联，不作为硅光PIC主线。",
    "marketAwareness": "已关注度变化",
    "misprice": "中",
    "judgement": "保留为主板光互联候选，但硅光专项里不拔高。",
    "nextAudit": "成品模块跟踪阶段再处理。",
    "lastDate": "20260626",
    "ret5d": "-9.4%",
    "ret20d": "-2.8%",
    "ret60d": "47.0%",
    "volRatio20d": "0.94"
  }
];

