window.CPO_OPTICAL_ENGINE_PACKAGING_AUDIT = [
  {
    "code": "300394.SZ",
    "name": "天孚通信",
    "board": "创业板",
    "userAccess": "非主板样本/风向标",
    "layer": "高速光引擎/精密微光学/封装耦合最强风向标",
    "chainRole": "高速光引擎、精密微光学组件、精密机械组件、隔离器、光波导器件、BOX封装、ELS解决方案",
    "bottleneck": "S-A",
    "evidenceGrade": "强",
    "officialEvidence": "2025年报披露高速光引擎项目，且提示募投高速光引擎项目毛利率相对较低；高速光引擎定义为在高速发射/接收芯片封装基础上集成精密微光学组件、精密机械组件、隔离器、光波导器件，实现单路或多路并行光信号传输与接收；产品定义还包括BOX高速率光器件封装、ELS解决方案。",
    "earningsSignal": "强：2025年光互连元器件收入50.82亿元，占营收98.43%，同比+57.27%。",
    "purity": "高：虽然非主板样本，但最接近CPO量产中的耦合/封装/光引擎良率关键约束。",
    "marketAwareness": "认知度较高/近期回落",
    "misprice": "中",
    "judgement": "本专项第一风向标，用它判断资金是否从模块扩散到光引擎和封装耦合。",
    "nextAudit": "下次看中报高速光引擎收入、毛利率下滑幅度、ELS和CPO客户进展。",
    "lastDate": "20260626",
    "ret5d": "-5.5%",
    "ret20d": "-28.9%",
    "ret60d": "0.1%",
    "volRatio20d": "1.14"
  },
  {
    "code": "603083.SH",
    "name": "剑桥科技",
    "board": "主板",
    "userAccess": "主板样本",
    "layer": "主板CPO集成硅光引擎/精密耦合制造映射",
    "chainRole": "CPO集成硅光引擎、NPO/CPO样机、自研500余台精密耦合机台",
    "bottleneck": "A",
    "evidenceGrade": "强",
    "officialEvidence": "2025年报披露NPO/CPO技术包括基于100G/L和200G/L的CPO集成硅光引擎；自研500余台精密耦合机台，生产自动化率与良率显著提升；硅光800G海外核心客户批量发货。",
    "earningsSignal": "强：2026Q1归母净利同比+276.44%。",
    "purity": "中高：更偏模块厂自用的光引擎集成和精密耦合能力，不是上游独立封装设备/材料。",
    "marketAwareness": "认知度较高/已明显关注度变化",
    "misprice": "低-中",
    "judgement": "主板里光引擎/CPO集成映射较直观，但已明显抢跑，不能当低位观察。",
    "nextAudit": "中报跟踪CPO/NPO是否从预研样机走到客户验证，精密耦合是否改善毛利和交付。",
    "lastDate": "20260626",
    "ret5d": "14.6%",
    "ret20d": "21.1%",
    "ret60d": "135.3%",
    "volRatio20d": "1.03"
  },
  {
    "code": "003031.SZ",
    "name": "中瓷电子",
    "board": "主板",
    "userAccess": "主板样本",
    "layer": "陶瓷外壳/氮化铝薄膜基板/封装材料核心候选",
    "chainRole": "光通信器件外壳、基板、氮化铝薄膜基板、陶瓷封装材料",
    "bottleneck": "A",
    "evidenceGrade": "强",
    "officialEvidence": "2025年报披露光通信器件外壳和基板速率覆盖2.5G至3.2T；具备氧化铝、氮化铝陶瓷材料和新型金属封接可靠性仿真能力；1.6T多层薄膜基板实现量产并通过客户验证。",
    "earningsSignal": "强：2025年收入28.78亿元、归母净利5.63亿元；2026Q1收入10.99亿元、归母净利1.93亿元，同比+79.05%、+57.32%。",
    "purity": "高：主板里最像CPO上游封装材料/基板关键约束的公司。",
    "marketAwareness": "关注度提升/涨幅高",
    "misprice": "中",
    "judgement": "主板主板样本里最值得继续专题观察的封装材料候选，但60日涨幅已高，不能追。",
    "nextAudit": "跟踪1.6T薄膜基板收入弹性、客户验证扩大、产能和毛利率。",
    "lastDate": "20260626",
    "ret5d": "3.9%",
    "ret20d": "20.4%",
    "ret60d": "135.0%",
    "volRatio20d": "1.21"
  },
  {
    "code": "002281.SZ",
    "name": "光迅科技",
    "board": "主板",
    "userAccess": "主板样本",
    "layer": "COB/混合集成/平面光波导封装平台映射",
    "chainRole": "COB、混合集成、平面光波导、微光器件、MEMS封装平台",
    "bottleneck": "A",
    "evidenceGrade": "强",
    "officialEvidence": "2025年报披露拥有COB、混合集成、平面光波导、微光器件、MEMS器件等封装平台，为各类产品稳定量产提供保障；同时具备光芯片、探测器和高速模块业务。",
    "earningsSignal": "强：2025年归母净利同比+43.10%，2026Q1归母净利同比+59.76%。",
    "purity": "中高：平台完整，但公司业务多元，封装耦合收入弹性需拆分。",
    "marketAwareness": "已关注度变化",
    "misprice": "中",
    "judgement": "主板样本核心平台型映射，等待中报拆分验证。",
    "nextAudit": "中报看高速数通、COB/光波导封装平台、光芯片自供比例。",
    "lastDate": "20260626",
    "ret5d": "-9.7%",
    "ret20d": "11.8%",
    "ret60d": "184.4%",
    "volRatio20d": "0.95"
  },
  {
    "code": "300502.SZ",
    "name": "新易盛",
    "board": "创业板",
    "userAccess": "非主板样本/风向标",
    "layer": "CPO/NPO/光引擎产业化需求风向标",
    "chainRole": "CPO/NPO/XPO形态、精密贴片、封装集成、光引擎和光模块",
    "bottleneck": "A",
    "evidenceGrade": "强",
    "officialEvidence": "2025年报披露覆盖LPO/LRO/XPO/NPO/CPO等形态；行业描述中光互联方案商通过精密贴片、封装等核心工序把光芯片和电芯片集成为光引擎以及光模块。",
    "earningsSignal": "极强：2025年营收同比+187.29%，归母净利同比+235.89%。",
    "purity": "中高：强风向标，但不是主板样本；更多验证需求和路线。",
    "marketAwareness": "认知度较高",
    "misprice": "低",
    "judgement": "用来确认CPO/NPO新形态需求，不作为关注候选。",
    "nextAudit": "成品与系统跟踪阶段继续跟踪。",
    "lastDate": "20260626",
    "ret5d": "-2.7%",
    "ret20d": "-21.2%",
    "ret60d": "26.5%",
    "volRatio20d": "1.18"
  },
  {
    "code": "300308.SZ",
    "name": "中际旭创",
    "board": "创业板",
    "userAccess": "非主板样本/风向标",
    "layer": "COB/硅光模块/共封装行业温度计",
    "chainRole": "多模并行光学设计与耦合、COB光电子器件封装、硅光模块、CPO定义",
    "bottleneck": "B-A",
    "evidenceGrade": "强",
    "officialEvidence": "2025年报披露多模并行光学设计与耦合技术、自动组装测试平台、Chip on Board光电子器件设计与封装技术；年报也定义CPO为交换ASIC与硅光引擎协同封装。",
    "earningsSignal": "极强：2025年归母净利同比+108.78%。",
    "purity": "中：成品模块温度计，不是上游封装材料/设备纯标的。",
    "marketAwareness": "认知度较高",
    "misprice": "低",
    "judgement": "只用于判断行业温度和海外AI光模块产业热度。",
    "nextAudit": "成品模块跟踪阶段统一处理。",
    "lastDate": "20260626",
    "ret5d": "-8.3%",
    "ret20d": "4.7%",
    "ret60d": "109.7%",
    "volRatio20d": "1.02"
  },
  {
    "code": "688313.SH",
    "name": "仕佳光子",
    "board": "科创板",
    "userAccess": "非主板样本/风向标",
    "layer": "CPO/硅光引擎用FAU/微光学器件风向标",
    "chainRole": "FAU、AWG、CPO类微光学器件、硅光引擎/硅光模块配套",
    "bottleneck": "A",
    "evidenceGrade": "强",
    "officialEvidence": "2025年报披露FAU应用于CPO交换机、AI算力集群、1.6T及以上高速光模块、硅光引擎/硅光模块；CPO类微光学器件中CPO用FAU-MT、高精度无盖板FAU-MT已小批量出货。",
    "earningsSignal": "强：2025年营收同比+98.15%，归母净利同比+473.25%。",
    "purity": "高：偏光引擎配套和耦合器件，非主板样本但很关键。",
    "marketAwareness": "已关注度变化",
    "misprice": "中",
    "judgement": "与上一条无源器件线交叉，是CPO微光学配套风向标。",
    "nextAudit": "继续看CPO类微光学器件小批量出货是否扩大。",
    "lastDate": "20260626",
    "ret5d": "2.4%",
    "ret20d": "9.7%",
    "ret60d": "102.8%",
    "volRatio20d": "1.15"
  },
  {
    "code": "002902.SZ",
    "name": "铭普光磁",
    "board": "主板",
    "userAccess": "主板样本",
    "layer": "CPO/NPO光源与NPO预研边缘候选",
    "chainRole": "800G NPO联合研发、ELSFP光源、CPO/NPO应用大功率激光光源",
    "bottleneck": "B-A待验证",
    "evidenceGrade": "中",
    "officialEvidence": "2025年报披露ELSFP光源开发CPO/NPO应用的大功率激光光源，已完成前期方案设计、样品投料加工；但公司异动公告提示800G LPO订单较小、800G NPO未量产、1.6T前期。",
    "earningsSignal": "弱：2025年亏损，2026Q1仍亏损。",
    "purity": "中低：有方向但反证强，不能作为主攻。",
    "marketAwareness": "概念已知/走势弱",
    "misprice": "低",
    "judgement": "跟踪验证，不作为本线核心。",
    "nextAudit": "等待量产订单和亏损收窄信号。",
    "lastDate": "20260626",
    "ret5d": "-18.5%",
    "ret20d": "-14.3%",
    "ret60d": "7.2%",
    "volRatio20d": "1.12"
  },
  {
    "code": "002897.SZ",
    "name": "意华股份",
    "board": "主板",
    "userAccess": "主板样本",
    "layer": "CPO端口/高速连接器/壳体外围映射",
    "chainRole": "3.2T ELSFP CPO OSFP端口、CPC芯片共封装电模组、光模块壳体",
    "bottleneck": "B",
    "evidenceGrade": "中",
    "officialEvidence": "2025年报披露3.2T ELSFP CPO OSFP端口、CPC芯片共封装电模组进入实质性开发阶段，800G/1.6T高速模块壳体大批量交付。",
    "earningsSignal": "弱化：2026Q1归母净利同比-37.69%。",
    "purity": "中低：更偏高速连接器/壳体/电模组，不是光引擎本体。",
    "marketAwareness": "关注度提升",
    "misprice": "中",
    "judgement": "外围跟踪，不纳入核心关键约束。",
    "nextAudit": "后续连接器/AI硬件扩散统一处理。",
    "lastDate": "20260626",
    "ret5d": "-12.7%",
    "ret20d": "4.9%",
    "ret60d": "39.0%",
    "volRatio20d": "1.07"
  },
  {
    "code": "002436.SZ",
    "name": "兴森科技",
    "board": "主板",
    "userAccess": "主板样本",
    "layer": "封装基板/玻璃基板外围映射",
    "chainRole": "PCB、封装基板、玻璃基板映射，非CPO光电共封装直接证据",
    "bottleneck": "B-C",
    "evidenceGrade": "弱-中",
    "officialEvidence": "现有映射表列为PCB、封装基板、玻璃基板映射；本轮未见光电共封装、CPO光引擎封装直接证据。",
    "earningsSignal": "待补。",
    "purity": "低-中：容易被先进封装概念带动，但不等于CPO核心。",
    "marketAwareness": "明显关注度变化",
    "misprice": "低",
    "judgement": "不作为CPO核心封装候选，避免跑题到泛先进封装。",
    "nextAudit": "若做PCB/封装基板专题再处理。",
    "lastDate": "20260626",
    "ret5d": "-0.5%",
    "ret20d": "42.6%",
    "ret60d": "150.3%",
    "volRatio20d": "0.90"
  },
  {
    "code": "002179.SZ",
    "name": "中航光电",
    "board": "主板",
    "userAccess": "主板样本",
    "layer": "AI高速连接器/液冷外围映射",
    "chainRole": "数据中心连接器、液冷、AI互连",
    "bottleneck": "B-C",
    "evidenceGrade": "中",
    "officialEvidence": "已有专题观察显示设立数据与通讯事业部，布局数据中心；但不是CPO光引擎/光电共封装本体。",
    "earningsSignal": "弱化：2026Q1归母净利同比-37.75%。",
    "purity": "低-中：AI硬件扩散，不是本专项核心。",
    "marketAwareness": "关注度提升",
    "misprice": "中",
    "judgement": "外围观察。",
    "nextAudit": "连接器/AI服务器硬件专题再处理。",
    "lastDate": "20260626",
    "ret5d": "4.7%",
    "ret20d": "9.5%",
    "ret60d": "28.5%",
    "volRatio20d": "1.24"
  }
];

