window.CPO_PASSIVE_COUPLING_AUDIT = [
  {
    "code": "688313.SH",
    "name": "仕佳光子",
    "board": "科创板",
    "userAccess": "非主板样本/风向标",
    "layer": "AWG/PLC/FAU/MT-FA最强风向标",
    "chainRole": "AWG组件、PLC光分路器、FAU、MT-FA、MMC/SN-MT高密度连接器",
    "bottleneck": "A",
    "evidenceGrade": "强",
    "officialEvidence": "2025年报披露FAU是光通信核心无源精密光学器件，是高速高密度光互联关键基础部件；AWG相关产品收入5.45亿元、PLC光分路器相关产品0.75亿元；400G/800G光模块用CWDM/LANWDM AWG组件大批量出货，1.6T光模块用AWG芯片及组件小批量出货，800G/1.6T MT-FA批量出货。",
    "earningsSignal": "强：2025年营收21.29亿元同比+98.15%，归母净利3.72亿元同比+473.25%。",
    "purity": "高：AWG/PLC/FAU/MT-FA都贴近CPO和硅光耦合、MUX/DEMUX卡点。",
    "marketAwareness": "已关注度变化",
    "misprice": "中",
    "judgement": "这条线的核心风向标，非主板样本但需要盯；若7月资金从模块上移到无源器件，它最敏感。",
    "nextAudit": "继续跟踪1.6T AWG、MT-FA批量进展、毛利率和客户结构。",
    "lastDate": "20260626",
    "ret5d": "2.4%",
    "ret20d": "9.7%",
    "ret60d": "102.8%",
    "volRatio20d": "1.15"
  },
  {
    "code": "300394.SZ",
    "name": "天孚通信",
    "board": "创业板",
    "userAccess": "非主板样本/风向标",
    "layer": "FA/FAU/微光学组件/光引擎耦合风向标",
    "chainRole": "FA/FAU光纤阵列、LENS ARRAY、AWG、Mux/Demux、微光学组件、高速光引擎",
    "bottleneck": "A",
    "evidenceGrade": "强",
    "officialEvidence": "2025年报释义包括FA/FAU光纤阵列、LENS ARRAY光纤透镜阵列、AWG阵列波导光栅、Mux/Demux复用/解复用器件；高速光引擎集成精密微光学组件、精密机械组件、隔离器、光波导器件等。",
    "earningsSignal": "强：2025年光互连元器件收入50.82亿元，占营收98.43%，同比+57.27%。",
    "purity": "高：不是单一AWG公司，但在耦合、微光学、光引擎封装链条非常关键。",
    "marketAwareness": "认知度较高/近期回落",
    "misprice": "中",
    "judgement": "比普通连接器更接近CPO量产良率关键约束，但非主板样本；它的走势判断“耦合/封装”是否被资金重估。",
    "nextAudit": "在光引擎/封装耦合专项继续专题观察高速光引擎和ELS解决方案。",
    "lastDate": "20260626",
    "ret5d": "-5.5%",
    "ret20d": "-28.9%",
    "ret60d": "0.1%",
    "volRatio20d": "1.14"
  },
  {
    "code": "002281.SZ",
    "name": "光迅科技",
    "board": "主板",
    "userAccess": "主板样本",
    "layer": "主板无源器件/AWG/光波导平台映射",
    "chainRole": "AWG、VMUX、WDM、VOA、OPM、光波导集成产品、无源器件",
    "bottleneck": "A",
    "evidenceGrade": "强",
    "officialEvidence": "2025年报披露公司覆盖无源器件、光波导集成产品；无源光器件包括AWG阵列波导光栅、VMUX光功率可调波分复用器、WDM、VOA、OPM等。",
    "earningsSignal": "强：2025年归母净利同比+43.10%，2026Q1归母净利同比+59.76%。",
    "purity": "中高：主板里无源器件和光波导证据较完整，但公司体量和业务多元，需拆分收入。",
    "marketAwareness": "已关注度变化",
    "misprice": "中",
    "judgement": "主板样本中最值得放入这条线的公司，但不算低位冷门；重点等中报验证，而不是阶段位置偏高。",
    "nextAudit": "中报拆分数据中心无源器件、AWG/光波导相关收入和毛利。",
    "lastDate": "20260626",
    "ret5d": "-9.7%",
    "ret20d": "11.8%",
    "ret60d": "184.4%",
    "volRatio20d": "0.95"
  },
  {
    "code": "300570.SZ",
    "name": "太辰光",
    "board": "创业板",
    "userAccess": "非主板样本/风向标",
    "layer": "光纤连接器/光器件风向标",
    "chainRole": "光纤连接器、光器件、高密度连接潜在线索",
    "bottleneck": "B-A待验证",
    "evidenceGrade": "中待补",
    "officialEvidence": "现有映射表列为光纤连接器/光器件风向标，但本轮未补齐官方年报证据；需确认是否是CPO/硅光所需高密度连接和耦合，还是普通光纤连接器弹性。",
    "earningsSignal": "待补。",
    "purity": "待验证：连接器不等于CPO核心耦合，需要看MT/MPO/MTP、FAU、客户和应用场景。",
    "marketAwareness": "明显关注度变化",
    "misprice": "低-中",
    "judgement": "涨幅已高，不能只因“连接器/光器件”就当作未专题观察；待补官方证据。",
    "nextAudit": "补年报，确认光纤连接器产品是否用于800G/1.6T、CPO/硅光高密度连接。",
    "lastDate": "20260626",
    "ret5d": "-12.8%",
    "ret20d": "37.4%",
    "ret60d": "97.9%",
    "volRatio20d": "0.98"
  },
  {
    "code": "688195.SH",
    "name": "腾景科技",
    "board": "科创板",
    "userAccess": "非主板样本/风向标",
    "layer": "精密光学/光通信器件待证实",
    "chainRole": "精密光学元件、光通信器件、微光学/耦合潜在线索",
    "bottleneck": "B-A待验证",
    "evidenceGrade": "弱-中",
    "officialEvidence": "现有映射表列为精密光学元件、光通信器件；本轮尚缺FAU/AWG/PLC/Mux-Demux直接官方证据。",
    "earningsSignal": "待补。",
    "purity": "待验证：可能更偏精密光学和微光学组件，是否进入CPO耦合链需要公告证据。",
    "marketAwareness": "低迷/回落",
    "misprice": "中高但证据不足",
    "judgement": "从涨幅看不热，但证据不足，不能因为低位就提高阶段标签。",
    "nextAudit": "补官方年报/问询，核实微光学、准直、滤波、耦合相关产品和客户。",
    "lastDate": "20260626",
    "ret5d": "-11.7%",
    "ret20d": "-45.1%",
    "ret60d": "-36.2%",
    "volRatio20d": "0.89"
  },
  {
    "code": "603083.SH",
    "name": "剑桥科技",
    "board": "主板",
    "userAccess": "主板样本",
    "layer": "精密耦合设备/模块集成映射",
    "chainRole": "自研精密耦合机台、硅光/CPO模块集成",
    "bottleneck": "B-A",
    "evidenceGrade": "中-强",
    "officialEvidence": "2025年报披露自研500多台精密耦合机台，并用于新产品交付；同时具备硅光800G和CPO集成硅光引擎预研。",
    "earningsSignal": "强：2026Q1归母净利同比+276.44%。",
    "purity": "中：更偏成品模块和内部耦合制造能力，不是独立出售的FAU/AWG/PLC器件。",
    "marketAwareness": "认知度较高/已明显关注度变化",
    "misprice": "低",
    "judgement": "主板样本但不是本专项最纯标的；用于理解光模块厂如何掌控耦合良率。",
    "nextAudit": "关注精密耦合机台是否只是自用，是否影响毛利和交付能力。",
    "lastDate": "20260626",
    "ret5d": "14.6%",
    "ret20d": "21.1%",
    "ret60d": "135.3%",
    "volRatio20d": "1.03"
  },
  {
    "code": "002897.SZ",
    "name": "意华股份",
    "board": "主板",
    "userAccess": "主板样本",
    "layer": "高速光电连接器/外壳外围映射",
    "chainRole": "800G/1.6T高速连接器、OSFP液冷屏蔽组件、CPO OSFP端口",
    "bottleneck": "B",
    "evidenceGrade": "中",
    "officialEvidence": "已有专题观察显示公司有800G/1.6T高速模块壳体、3.2T ELSFP CPO OSFP端口、CPC电模组开发，但更偏高速连接器/壳体/散热组件。",
    "earningsSignal": "弱化：2026Q1业绩下滑。",
    "purity": "中低：属于AI网络硬件扩散，不是FAU/AWG/PLC光耦合本体。",
    "marketAwareness": "关注度提升",
    "misprice": "中",
    "judgement": "保留外围观察，不纳入本专项核心。",
    "nextAudit": "后续连接器/AI网络硬件扩散线再统一处理。",
    "lastDate": "20260626",
    "ret5d": "-12.7%",
    "ret20d": "4.9%",
    "ret60d": "39.0%",
    "volRatio20d": "1.07"
  },
  {
    "code": "300620.SZ",
    "name": "光库科技",
    "board": "创业板",
    "userAccess": "非主板样本/风向标",
    "layer": "调制器/光器件交叉线",
    "chainRole": "光器件、铌酸锂调制器映射，非本专项核心",
    "bottleneck": "A-B",
    "evidenceGrade": "中待补",
    "officialEvidence": "现有映射为光器件/TFLN调制器方向，和本专项有交叉但更适合放在调制器线补证。",
    "earningsSignal": "待补。",
    "purity": "中：不是AWG/FAU主线。",
    "marketAwareness": "关注度提升",
    "misprice": "中",
    "judgement": "本专项只作为交叉观察，重点仍在硅光调制器补证。",
    "nextAudit": "补年报确认TFLN调制器量产与收入。",
    "lastDate": "20260626",
    "ret5d": "-7.3%",
    "ret20d": "23.7%",
    "ret60d": "86.4%",
    "volRatio20d": "0.82"
  },
  {
    "code": "300548.SZ",
    "name": "博创科技",
    "board": "创业板",
    "userAccess": "非主板样本/风向标",
    "layer": "硅光模块/光模块交叉线",
    "chainRole": "光模块、硅光方向，非FAU/AWG主线",
    "bottleneck": "B",
    "evidenceGrade": "弱-中",
    "officialEvidence": "现有映射为光模块/硅光，缺少FAU/AWG/PLC直接证据。",
    "earningsSignal": "待补。",
    "purity": "低-中：更适合成品/硅光模块线。",
    "marketAwareness": "关注度提升",
    "misprice": "中",
    "judgement": "不作为本专项核心。",
    "nextAudit": "后续成品模块或硅光补证时处理。",
    "lastDate": "20260626",
    "ret5d": "-6.9%",
    "ret20d": "9.4%",
    "ret60d": "74.3%",
    "volRatio20d": "1.01"
  },
  {
    "code": "300502.SZ",
    "name": "新易盛",
    "board": "创业板",
    "userAccess": "非主板样本/风向标",
    "layer": "成品模块/PIC平台温度计",
    "chainRole": "SiPh/TFLN/PIC平台，非无源器件主线",
    "bottleneck": "A",
    "evidenceGrade": "强",
    "officialEvidence": "硅光PIC线证据强，但本专项仅作为需求温度计，不重复展开。",
    "earningsSignal": "极强：2025年归母净利同比+235.89%。",
    "purity": "中：不是FAU/AWG/PLC主线。",
    "marketAwareness": "认知度较高",
    "misprice": "低",
    "judgement": "用于判断硅光产业化需求，不作为本专项核心观察对象。",
    "nextAudit": "成品/硅光跟踪时跟踪。",
    "lastDate": "20260626",
    "ret5d": "-2.7%",
    "ret20d": "-21.2%",
    "ret60d": "26.5%",
    "volRatio20d": "1.18"
  }
];

