const BATCH_B_PARTNER_CANDIDATE_WORKBENCH_V1 = {
  "generated_at": "2026-06-27 17:05:18",
  "source": "E:\\CODEX  zhuanyi\\网站规划工作区\\legacy_reports\\batch_b_workbench\\batch_b_partner_evidence_v1.json",
  "purpose": "第二批10家公司合作对象候选线索工作台。只做证据排队，不直接写入正式报告。",
  "rules": [
    "提问里出现公司名但公司回答未确认，不得写入报告。",
    "公告标题只能作为强证据入口，未解析全文前不得写入合作对象。",
    "只有公告/年报/公司回答正文明确出现合作对象，并且没有否认或不披露表述，才可升级为已确认。"
  ],
  "summary": {
    "companies": 10,
    "candidate_items": 115,
    "blocked_items": 1,
    "fulltext_items": 74,
    "low_confidence_items": 40
  },
  "rows": [
    {
      "code": "600497",
      "name": "驰宏锌锗",
      "partner_status": "有强证据入口，待全文确认",
      "candidate_count": 9,
      "blocked_count": 0,
      "fulltext_count": 9,
      "low_confidence_count": 0,
      "candidates": [
        {
          "order": 1,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-06-16",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "驰宏锌锗股票交易异常波动公告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600497&announcementId=1225371268&orgId=gssh0600497&announcementTime=2026-06-16",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 2,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-03-27",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "驰宏锌锗2025年年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600497&announcementId=1225035092&orgId=gssh0600497&announcementTime=2026-03-27",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 3,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-03-27",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "云南驰宏锌锗股份有限公司2025年年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600497&announcementId=1225035088&orgId=gssh0600497&announcementTime=2026-03-27",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 4,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-01-29",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "驰宏锌锗关于与中铝融资租赁有限公司签订融资租赁业务框架合作协议暨关联交易的公告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600497&announcementId=1224954199&orgId=gssh0600497&announcementTime=2026-01-29",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 5,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-01-29",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "驰宏锌锗关于与中铝商业保理有限公司签订保理业务框架合作协议暨关联交易的公告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600497&announcementId=1224954180&orgId=gssh0600497&announcementTime=2026-01-29",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 6,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-08-27",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "驰宏锌锗2025年半年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600497&announcementId=1224575309&orgId=gssh0600497&announcementTime=2025-08-27",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 7,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-08-27",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "驰宏锌锗2025年半年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600497&announcementId=1224575308&orgId=gssh0600497&announcementTime=2025-08-27",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 8,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-03-28",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "驰宏锌锗2024年年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600497&announcementId=1222924612&orgId=gssh0600497&announcementTime=2025-03-28",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 9,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-03-28",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "驰宏锌锗2024年年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600497&announcementId=1222924605&orgId=gssh0600497&announcementTime=2025-03-28",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        }
      ]
    },
    {
      "code": "600301",
      "name": "华锡有色",
      "partner_status": "有强证据入口，待全文确认",
      "candidate_count": 10,
      "blocked_count": 0,
      "fulltext_count": 10,
      "low_confidence_count": 0,
      "candidates": [
        {
          "order": 1,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-06-16",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "广西华锡有色金属股份有限公司关于股票交易异常波动的公告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600301&announcementId=1225371520&orgId=gssh0600301&announcementTime=2026-06-16",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 2,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-06-03",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "广西华锡有色金属股份有限公司关于股票交易异常波动的公告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600301&announcementId=1225346768&orgId=gssh0600301&announcementTime=2026-06-03",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 3,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-04-22",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "广西华锡有色金属股份有限公司2025年年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600301&announcementId=1225142999&orgId=gssh0600301&announcementTime=2026-04-22",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 4,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-04-22",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "广西华锡有色金属股份有限公司2025年年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600301&announcementId=1225142991&orgId=gssh0600301&announcementTime=2026-04-22",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 5,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-02-28",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "广西华锡有色金属股份有限公司投资者关系活动记录表（2026年2月）",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600301&announcementId=1224987720&orgId=gssh0600301&announcementTime=2026-02-28",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 6,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-02-28",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "《关于广西华锡有色金属股份有限公司股票交易异常波动的征询函》的回函（华锡集团）",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600301&announcementId=1224987718&orgId=gssh0600301&announcementTime=2026-02-28",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 7,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-02-28",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "《关于广西华锡有色金属股份有限公司股票交易异常波动的征询函》的回函（北部湾港集团）",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600301&announcementId=1224987715&orgId=gssh0600301&announcementTime=2026-02-28",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 8,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-02-28",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "《关于广西华锡有色金属股份有限公司股票交易异常波动的征询函》的回函（关键金属集团）",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600301&announcementId=1224987713&orgId=gssh0600301&announcementTime=2026-02-28",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 9,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-02-28",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "广西华锡有色金属股份有限公司关于股票交易异常波动的公告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600301&announcementId=1224987708&orgId=gssh0600301&announcementTime=2026-02-28",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 10,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-11-20",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "广西华锡有色金属股份有限公司投资者关系活动记录表（2025年11月18日）",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600301&announcementId=1224815026&orgId=gssh0600301&announcementTime=2025-11-20",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        }
      ]
    },
    {
      "code": "001332",
      "name": "锡装股份",
      "partner_status": "有强证据入口，待全文确认",
      "candidate_count": 15,
      "blocked_count": 0,
      "fulltext_count": 9,
      "low_confidence_count": 6,
      "candidates": [
        {
          "order": 1,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-06-17 15:09:13",
          "answer_time": "2026-06-25 15:00:04",
          "question": "尊敬的董秘您好！公司三月公告获得沙特阿美认证，现在是否已经获得其小批量订单？",
          "answer": "感谢您对公司的关注，经营情况请以公司正式公告为准。",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 2,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-05-26 10:22:48",
          "answer_time": "2026-06-09 11:30:04",
          "question": "公司一季度业绩高增，为什么社保基金却退出了？公司一季度业绩高增原因是什么？谢谢！",
          "answer": "尊敬的投资者，由于公司销售的为非标产品，不同定单及不同产品的售价及毛利率存在差异，取决于市场环境、每一个合同价格竞争的激烈程度、客户关系、技术壁垒、产品本身的材质、对质量的要求、制造难度、对成本估算的精准度、材料成本的波动等多重因素，因此，不同订单之间及不同期间的收入及毛利率会存在一定的波动。2026年1-3月的营业收入及毛利率同比提升主要系报告期交付的外销产品销售占比及平均售价同比提升等所致。",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 3,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-05-26 10:20:09",
          "answer_time": "2026-06-09 11:30:04",
          "question": "看好公司在中东重建方面情况，这方面价值量不知道怎样？随着新能源的不断应用，公司业务是否能多元发展，以应对行业风险？谢谢！",
          "answer": "尊敬的投资者，公司主营产品是为非标金属压力容器，产品广泛应用于能源、化工等领域，可满足下游行业在换热、反应、分离、储存等关键环节的应用需求。公司积极加大市场开拓力度，重点布局并拓展国际市场，持续优化客户结构、扩大优质客户群体；同时不断加大研发投入，稳步推进产品与技术迭代升级，持续拓展应用场景，在高技术船舶及海洋工程、新能源综合利用等领域的业务占比逐步提升，推动公司经营持续稳定发展。感谢您的关心和支持！",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 4,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-05-17 15:24:00",
          "answer_time": "2026-05-29 08:50:03",
          "question": "公司年报提到“近年迅速布局新能源装备行业”，但年报数据显示传统的石油炼化领域仍然占了营业收入的6成，在全球大力发展储能、新能源的趋势下，公司在石油及石油化工领域能否继续维持高毛利和饱和的业务量？公司26年在海洋工程、太阳能、核能等方向有没有新的措施和投入？能否更快的提升在营收中的比例？谢谢",
          "answer": "尊敬的投资者，公司主营产品是为非标金属压力容器，产品广泛应用于能源、化工等领域，可满足下游行业在换热、反应、分离、储存等关键环节的应用需求。公司积极加大市场开拓力度，重点布局并拓展国际市场，持续优化客户结构、扩大优质客户群体；同时不断加大研发投入，稳步推进产品与技术迭代升级，持续拓展应用场景，在高技术船舶及海洋工程、新能源综合利用等领域的业务占比逐步提升，推动公司经营持续稳定发展。感谢您的关心和支持！",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 5,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-05-18 09:17:59",
          "answer_time": "2026-05-29 08:18:03",
          "question": "公司一季度毛利和营收同比都大幅提升，请问是哪部分业务增加形成的？谢谢",
          "answer": "尊敬的投资者，由于公司销售的为非标产品，不同定单及不同产品的售价及毛利率存在差异，取决于市场环境、每一个合同价格竞争的激烈程度、客户关系、技术壁垒、产品本身的材质、对质量的要求、制造难度、对成本估算的精准度、材料成本的波动等多重因素，因此，不同订单之间及不同期间的收入及毛利率会存在一定的波动。2026年1-3月的营业收入及毛利率同比提升主要系报告期交付的外销产品销售占比及平均售价同比提升等所致。感谢您的关心和支持！",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 6,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-04-27 14:50:53",
          "answer_time": "2026-04-30 11:30:04",
          "question": "董秘您好，公司营收降23%但毛利率升4.27%，请解释背离原因。营收下滑存货却增23.4%，减值计提是否充分？债务重组中债权转股权公允价值按担保额20%确定的依据及合理性？谢谢！",
          "answer": "尊敬的投资者，感谢您对公司的关注！关于您的问题答复如下：\n1、2025年度，公司营业收入同比下降，主要是由于公司完工交付产品数量同比减少以及碳钢等普通材质产品占比提升导致产品平均售价下降；同期公司毛利率同比提升的主要原因系外销收入占比及毛利率提升所致。2、2025年末，存货增加主要系在执行订单增加相应原材料及库存商品、发出商品增加所致。公司严格按照《企业会计准则》相关规定计提各项资产减值，且已充分、谨慎计提存货跌价准备，能够客观、公允地反映公司的财务状况及经营成果，符合公司实际情况。3、公司2025年度债权转股权事项的公允价值是基于交易的经济实质，以第三方提供的担保金额作为其公允价值。具体内容详见公司《2025年年度报告》相关章节。",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 7,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-04-27",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "2025年年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=001332&announcementId=1225183919&orgId=9900031494&announcementTime=2026-04-27",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 8,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-04-27",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "2025年年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=001332&announcementId=1225183918&orgId=9900031494&announcementTime=2026-04-27",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 9,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-03-27",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "关于获得沙特阿美公司供应商资质认证的公告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=001332&announcementId=1225034484&orgId=9900031494&announcementTime=2026-03-27",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 10,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-09-10",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "股票交易异常波动公告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=001332&announcementId=1224647187&orgId=9900031494&announcementTime=2025-09-10",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 11,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-08-26",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "2025年半年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=001332&announcementId=1224569433&orgId=9900031494&announcementTime=2025-08-26",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 12,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-08-26",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "2025年半年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=001332&announcementId=1224569429&orgId=9900031494&announcementTime=2025-08-26",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 13,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-05-28",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "股票交易异常波动公告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=001332&announcementId=1223695345&orgId=9900031494&announcementTime=2025-05-28",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 14,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-04-09",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "2024年年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=001332&announcementId=1223029492&orgId=9900031494&announcementTime=2025-04-09",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 15,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-04-09",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "2024年年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=001332&announcementId=1223029481&orgId=9900031494&announcementTime=2025-04-09",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        }
      ]
    },
    {
      "code": "600888",
      "name": "新疆众和",
      "partner_status": "有强证据入口，待全文确认",
      "candidate_count": 8,
      "blocked_count": 0,
      "fulltext_count": 8,
      "low_confidence_count": 0,
      "candidates": [
        {
          "order": 1,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-06-27",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "新疆众和股份有限公司股票交易异常波动的公告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600888&announcementId=1225390588&orgId=gssh0600888&announcementTime=2026-06-27",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 2,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-03-31",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "新疆众和股份有限公司2025年年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600888&announcementId=1225055079&orgId=gssh0600888&announcementTime=2026-03-31",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 3,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-03-31",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "新疆众和股份有限公司2025年年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600888&announcementId=1225055008&orgId=gssh0600888&announcementTime=2026-03-31",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 4,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-08-27",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "新疆众和股份有限公司2025年半年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600888&announcementId=1224584891&orgId=gssh0600888&announcementTime=2025-08-27",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 5,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-08-27",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "新疆众和股份有限公司2025年半年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600888&announcementId=1224584890&orgId=gssh0600888&announcementTime=2025-08-27",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 6,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-03-28",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "国信证券关于新疆众和股份有限公司2024年度持续督导年度报告书",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600888&announcementId=1222923260&orgId=gssh0600888&announcementTime=2025-03-28",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 7,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-03-25",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "新疆众和股份有限公司2024年年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600888&announcementId=1222882673&orgId=gssh0600888&announcementTime=2025-03-25",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 8,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-03-25",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "新疆众和股份有限公司2024年年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600888&announcementId=1222882664&orgId=gssh0600888&announcementTime=2025-03-25",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        }
      ]
    },
    {
      "code": "600961",
      "name": "株冶集团",
      "partner_status": "有强证据入口，待全文确认",
      "candidate_count": 9,
      "blocked_count": 0,
      "fulltext_count": 9,
      "low_confidence_count": 0,
      "candidates": [
        {
          "order": 1,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-06-24",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "株冶集团股票交易异常波动公告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600961&announcementId=1225383737&orgId=gssh0600961&announcementTime=2026-06-24",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 2,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-04-22",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "株冶集团股票交易异常波动公告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600961&announcementId=1225137349&orgId=gssh0600961&announcementTime=2026-04-22",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 3,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-04-18",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "株冶集团股票交易异常波动公告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600961&announcementId=1225118515&orgId=gssh0600961&announcementTime=2026-04-18",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 4,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-04-17",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "株冶集团2025年年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600961&announcementId=1225112150&orgId=gssh0600961&announcementTime=2026-04-17",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 5,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-04-17",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "株冶集团2025年年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600961&announcementId=1225112140&orgId=gssh0600961&announcementTime=2026-04-17",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 6,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-08-13",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "株冶集团2025年半年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600961&announcementId=1224461670&orgId=gssh0600961&announcementTime=2025-08-13",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 7,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-08-13",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "株冶集团2025年半年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600961&announcementId=1224461668&orgId=gssh0600961&announcementTime=2025-08-13",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 8,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-04-11",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "株冶集团2024年年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600961&announcementId=1223057788&orgId=gssh0600961&announcementTime=2025-04-11",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 9,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-04-11",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "株冶集团2024年年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600961&announcementId=1223057777&orgId=gssh0600961&announcementTime=2025-04-11",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        }
      ]
    },
    {
      "code": "002384",
      "name": "东山精密",
      "partner_status": "有强证据入口，待全文确认",
      "candidate_count": 16,
      "blocked_count": 1,
      "fulltext_count": 4,
      "low_confidence_count": 11,
      "candidates": [
        {
          "order": 1,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-06-24 14:18:18",
          "answer_time": "2026-06-26 09:10:33",
          "question": "董秘你好，索尔思拟投资12亿美元实施光芯片及光模块扩建项目，目标客户是哪些？谢谢",
          "answer": "基于商业保密原则，具体信息不便披露，敬请谅解。",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 2,
          "source": "互动易/巨潮问答",
          "kind": "回答含名称但未达确认规则",
          "risk_level": "低置信",
          "question_time": "2026-06-24 15:25:39",
          "answer_time": "2026-06-26 09:10:03",
          "question": "董秘你好，公司是真的国内唯一实现78层及以上超高层高速背板批量供货英伟达AI服务器（GB200） 的厂商，掌握7阶厚板HDI?谢谢",
          "answer": "基于商业保密原则，具体信息不便披露，敬请谅解。",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [
            "英伟达"
          ],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 3,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-06-24 14:20:38",
          "answer_time": "2026-06-26 09:06:33",
          "question": "董秘你好，高端光芯片供需缺口扩大，Lumentum在FY26Q3业绩会上表示EML供需缺口已从上一季度的25%-30%扩大至超过30%，订单已经排满至2028年。公司产能利用率如何？谢谢",
          "answer": "基于商业保密原则，具体信息不便披露，敬请谅解。",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 4,
          "source": "互动易/巨潮问答",
          "kind": "提问提及名称，回答未确认",
          "risk_level": "不能写入",
          "question_time": "2026-06-24 15:33:58",
          "answer_time": "2026-06-25 14:09:05",
          "question": "董秘你好，公司是全球第二FPC柔性线路板精细线路制造（苹果折叠屏核心供应商）？谢谢",
          "answer": "",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [
            "苹果"
          ],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 5,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-06-20 13:28:47",
          "answer_time": "2026-06-23 16:04:33",
          "question": "董秘您好，请问公司收购索尔斯完成股权闭环没有？后面会不会发生股权纠纷？目前公司没有光芯片底层研发设计能力，收购后下一步有在光芯片底层上的研发设计计划吗？",
          "answer": "公司已全额支付交易对价，因标的公司涉及开曼群岛等多地主体，股权变更登记属程序性工作，正在按各辖区法规正常推进办理。此外，公司依托“光芯片+光模块”IDM垂直整合模式，通过自研自产光芯片，有效优化产品成本结构、提升盈利空间，同时能显著提升产品研发迭代与客户响应能力，持续筑牢供应链安全壁垒，持续提升市场份额与行业影响力。谢谢。",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 6,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-06-18 11:41:12",
          "answer_time": "2026-06-23 16:01:33",
          "question": "请介绍公司与苏州易缆微的合作进展",
          "answer": "基于商业保密原则，具体信息不便披露，敬请谅解。谢谢。",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 7,
          "source": "互动易/巨潮问答",
          "kind": "回答含名称但未达确认规则",
          "risk_level": "低置信",
          "question_time": "2026-06-17 11:36:33",
          "answer_time": "2026-06-18 11:30:04",
          "question": "您好，公司产业与市值大涨，又地处江苏苏州工业园区内，是否考虑持股或收购中新集团，中新集团现在市值仅仅100亿元，让公司产业模式及国际知名度更上一层楼，目标对标比肩韩国三星。",
          "answer": "您好！感谢您对公司的关注！谢谢",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [
            "三星"
          ],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 8,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-06-10 23:14:48",
          "answer_time": "2026-06-15 20:45:33",
          "question": "NPO 成为市场热点。看到公司年报中将 ELSFP 和 NPO 列为前二研发项目，公司盐城工厂技改也有 CPO/NPO 生产线布局。请公司披露在 NPO 新技术上的战略定位、技术路线、研发进展、产能规划与客户布局。",
          "answer": "公司具备硅光 CW 激光芯片研发能力，目前已与外部硅光企业开展合作并布局自研硅光模块产品，后续技术方案坚持 EML与硅光并行，多元布局应对光互联技术迭代，持续夯实技术竞争力。具体信息请参考公司定期报告及相关公告。谢谢。",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 9,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-06-09 17:14:42",
          "answer_time": "2026-06-12 20:45:33",
          "question": "当前高端PCB行业整体景气度维持高位，市场供需格局持续向好。请问公司在AI服务器PCB市场的份额情况如何？后续市占率提升的核心驱动力是什么？",
          "answer": "公司依托成熟的高端制造能力、持续扩张的产能规模、稳固的客户合作关系，同时发挥光模块（含光芯片）与 PCB 业务协同效应，增强客户粘性，持续巩固市场地位。谢谢。",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 10,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-06-09 17:14:03",
          "answer_time": "2026-06-12 20:45:33",
          "question": "公司作为国内少数具备100G/200G高端光芯片量产能力的光通信IDM厂商，如何看待当前国内光芯片领域的竞争格局？公司的差异化优势主要体现在哪些方面？",
          "answer": "公司具备完整的光芯片全流程 IDM 体系，拥有成熟的自研技术与工艺，同时形成了产能、客户以及多业务协同的综合优势，综合竞争力在国内处于领先位置。谢谢。",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 11,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-06-09 17:13:48",
          "answer_time": "2026-06-12 20:45:33",
          "question": "全球高端光芯片供需缺口持续扩大，Lumentum等厂商订单已排满至2028年。在此背景下，公司如何抓住光芯片国产替代的窗口机遇期？",
          "answer": "公司依托“光芯片+光模块”IDM垂直整合模式，通过自研自产光芯片，有效优化产品成本结构、提升盈利空间，同时能显著提升产品研发迭代与客户响应能力，持续筑牢供应链安全壁垒，持续提升市场份额与行业影响力。谢谢。",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 12,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-06-09 17:11:32",
          "answer_time": "2026-06-12 20:45:33",
          "question": "公司表示 ＂这可能是我这辈子看到的最大的机会＂，请问公司如何把握 AI 产业的战略发展机遇？",
          "answer": "公司凭借光芯片、光模块、高端 PCB 等领域的一体化布局构建差异化竞争壁垒，积极加大与全球一线客户的合作，同时前瞻性开展前沿技术的研发，紧跟行业发展的节奏。谢谢。",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 13,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-06-05 00:00:00",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "关于股票交易异常波动的公告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=002384&announcementId=1225352290&orgId=9900011647&announcementTime=2026-06-05 00:00:00",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 14,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-05-23 00:00:00",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "2025年年度报告（英文版）",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=002384&announcementId=1225325502&orgId=9900011647&announcementTime=2026-05-23 00:00:00",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 15,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-04-22 00:00:00",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "2025年年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=002384&announcementId=1225139318&orgId=9900011647&announcementTime=2026-04-22 00:00:00",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 16,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-04-22 00:00:00",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "2025年年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=002384&announcementId=1225139317&orgId=9900011647&announcementTime=2026-04-22 00:00:00",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        }
      ]
    },
    {
      "code": "600183",
      "name": "生益科技",
      "partner_status": "有强证据入口，待全文确认",
      "candidate_count": 7,
      "blocked_count": 0,
      "fulltext_count": 7,
      "low_confidence_count": 0,
      "candidates": [
        {
          "order": 1,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-05-27",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "生益科技股票交易异常波动公告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600183&announcementId=1225331800&orgId=gssh0600183&announcementTime=2026-05-27",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 2,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-04-25",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "生益科技2025年年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600183&announcementId=1225195409&orgId=gssh0600183&announcementTime=2026-04-25",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 3,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-04-25",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "生益科技2025年年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600183&announcementId=1225195362&orgId=gssh0600183&announcementTime=2026-04-25",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 4,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-08-16",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "生益科技2025年半年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600183&announcementId=1224499862&orgId=gssh0600183&announcementTime=2025-08-16",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 5,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-08-16",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "生益科技2025年半年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600183&announcementId=1224499861&orgId=gssh0600183&announcementTime=2025-08-16",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 6,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-03-29",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "生益科技2024年年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600183&announcementId=1222952359&orgId=gssh0600183&announcementTime=2025-03-29",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 7,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-03-29",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "生益科技2024年年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600183&announcementId=1222952338&orgId=gssh0600183&announcementTime=2025-03-29",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        }
      ]
    },
    {
      "code": "002916",
      "name": "深南电路",
      "partner_status": "有强证据入口，待全文确认",
      "candidate_count": 14,
      "blocked_count": 0,
      "fulltext_count": 8,
      "low_confidence_count": 6,
      "candidates": [
        {
          "order": 1,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-06-16 10:51:44",
          "answer_time": "2026-06-18 18:05:33",
          "question": "贵公司目前马8马9材料是否已经有实际订单？目前有个众所周知的问题就是原来钻针只能打几百针非常不利生产的连贯，公司有没有解决这个问题？是不是传闻要换金刚石钻针？",
          "answer": "尊敬的投资者，您好。目前公司部分产品涉及高速材料。公司坚持与供应商进行长期稳定的合作，通过建立多元化供应来源等手段保障供应链的安全稳定。谢谢您的关注。",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 2,
          "source": "互动易/巨潮问答",
          "kind": "回答含名称但未达确认规则",
          "risk_level": "低置信",
          "question_time": "2026-05-29 20:10:12",
          "answer_time": "2026-06-03 19:58:33",
          "question": "您好，请问贵公司的产品是否进入了英伟达rubin机架的供应链？",
          "answer": "尊敬的投资者，您好。基于商业保密原则，凡涉及与具体企业合作的问题公司均不便于回复，敬请谅解。谢谢您的关注。",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [
            "英伟达"
          ],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 3,
          "source": "互动易/巨潮问答",
          "kind": "回答含名称但未达确认规则",
          "risk_level": "低置信",
          "question_time": "2026-05-26 15:08:44",
          "answer_time": "2026-05-28 18:33:03",
          "question": "公司与华为半导体韬定律有无合作？",
          "answer": "尊敬的投资者，您好。基于商业保密原则，凡涉及与具体企业合作的问题公司均不便于回复，敬请谅解。谢谢您的关注。",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [
            "华为"
          ],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 4,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-05-23 16:26:21",
          "answer_time": "2026-05-26 19:27:03",
          "question": "你好，随着AI PCB的需求增大，多层板PCB订单越来越多，贵司新建产线 和 旧产线升级， 配置LDI设备 还是 传统菲林曝光设备？",
          "answer": "尊敬的投资者，您好。公司工艺设备选型会依据实际生产要求、产品品质标准等维度综合考量，择优匹配适配的工艺设备方案，以保证产能供应及产品质量。谢谢您的关注。",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 5,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-04-28 08:58:51",
          "answer_time": "2026-04-28 19:30:33",
          "question": "公司年报数据显示外协费用显著增加，请问主要原因是什么？是产能跟不上进度还是缺少关键技术还是利益输送？谢谢",
          "answer": "尊敬的投资者，您好。2025年公司外协费用同比增加主要是因为公司订单饱和导致部分工序内部产能出现瓶颈，外协需求增加。谢谢您的关注。",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 6,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-04-16 12:59:33",
          "answer_time": "2026-04-20 18:49:03",
          "question": "您好，董秘，公司作为国内FC-BGA与AI封装基板龙头，对下一代玻璃基板（TGV）技术是否有研发或中试布局？目前TGV激光微孔设备是否已开始选型、测试或技术对接？是否与帝尔激光等国产设备商有合作？",
          "answer": "尊敬的投资者，您好。公司对行业前沿技术保持关注和研究，积极探索行业机会并做好相应技术储备。基于商业保密原则，凡涉及与具体企业合作的问题公司均不便于回复，敬请谅解。谢谢您的关注。",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 7,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-03-13",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "2025年年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=002916&announcementId=1225006760&orgId=9900022488&announcementTime=2026-03-13",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 8,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-03-13",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "2025年年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=002916&announcementId=1225006759&orgId=9900022488&announcementTime=2026-03-13",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 9,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-02-27",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "股票交易异常波动公告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=002916&announcementId=1224985961&orgId=9900022488&announcementTime=2026-02-27",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 10,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-09-01",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "股票交易异常波动公告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=002916&announcementId=1224626954&orgId=9900022488&announcementTime=2025-09-01",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 11,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-08-28",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "2025年半年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=002916&announcementId=1224596190&orgId=9900022488&announcementTime=2025-08-28",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 12,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-08-28",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "2025年半年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=002916&announcementId=1224596189&orgId=9900022488&announcementTime=2025-08-28",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 13,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-03-13",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "2024年年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=002916&announcementId=1222778134&orgId=9900022488&announcementTime=2025-03-13",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 14,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-03-13",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "2024年年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=002916&announcementId=1222778132&orgId=9900022488&announcementTime=2025-03-13",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        }
      ]
    },
    {
      "code": "000338",
      "name": "潍柴动力",
      "partner_status": "有强证据入口，待全文确认",
      "candidate_count": 11,
      "blocked_count": 0,
      "fulltext_count": 6,
      "low_confidence_count": 5,
      "candidates": [
        {
          "order": 1,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-06-17 20:51:10",
          "answer_time": "2026-06-24 15:16:33",
          "question": "尊敬的董秘，您好！请问贵公司在做市场份额预测时，会不会参考分析师对贵企业客户发布的预测信息？",
          "answer": "公司始终结合多维度信息开展审慎评估，保障经营研判的科学性与合理性。感谢您对公司的关注！",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 2,
          "source": "互动易/巨潮问答",
          "kind": "问答主题候选，待补全文",
          "risk_level": "低置信",
          "question_time": "2026-06-22 10:28:54",
          "answer_time": "2026-06-23 11:19:58",
          "question": "国内AIDC建设加速，分布式清洁能源供电需求旺盛。请问公司SOFC产品在数据中心备用/主供电源市场的客户拓展进展如何？与燃气轮机、柴油发电机等传统方案相比，公司产品的竞争优势主要体现在哪些方面？",
          "answer": "",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 3,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-06-12 10:43:16",
          "answer_time": "2026-06-18 17:27:03",
          "question": "公司生产重卡、工程机械发动机，又要大力生产重卡和工程机械，和自己客户福田、三一、徐工等等竞争，这个战略没问题吧？",
          "answer": "公司主营业务涵盖动力系统、商用车、农业装备、智慧物流、电力能源等业务板块，各业务板块资源互通、协同增效，可有效平滑行业周期波动，保障公司长期稳健发展。多年来，动力系统与重卡整车业务保持相互赋能、协同发展，动力系统业务稳居行业龙头，重卡稳居行业第一梯队。同时，公司坚持创新驱动，致力于打造最具技术、品质、成本和服务四大核心竞争力的产品，为合作伙伴创造多重价值。随着国内市场步入存量竞争阶段，海外市场是共同增量赛道，我们将坚持多元动力提供商的定位，对内强化全产业链技术迭代，对外深化与合作伙伴的协同合作，携手国内装备企业共同开拓全球市场，合力打造并擦亮中国高端装备产业的国际名片。感谢您对公司的关注！",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 4,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-05-21 22:28:05",
          "answer_time": "2026-06-01 08:38:33",
          "question": "SpaceX斥资28亿美元采购燃气轮机，为其人工智能数据中心供电，公司是否拿到此次燃气轮机订单？",
          "answer": "公司没有燃气轮机产品。感谢您对公司的关注！",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 5,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-03-25 13:13:01",
          "answer_time": "2026-04-03 08:38:02",
          "question": "请问以色列伊朗战争发生后，发电类产品订单是否增长迅速？",
          "answer": "主要受全球数据中心电力需求爆发增长影响，公司发电业务产品需求饱满。感谢您对公司的关注！",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 6,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-03-27",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "2025年年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=000338&announcementId=1225037559&orgId=9900002961&announcementTime=2026-03-27",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 7,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-03-27",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "2025年年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=000338&announcementId=1225037558&orgId=9900002961&announcementTime=2026-03-27",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 8,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-08-30",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "2025年半年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=000338&announcementId=1224626777&orgId=9900002961&announcementTime=2025-08-30",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 9,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-08-30",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "2025年半年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=000338&announcementId=1224626769&orgId=9900002961&announcementTime=2025-08-30",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 10,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-03-28",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "2024年年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=000338&announcementId=1222927979&orgId=9900002961&announcementTime=2025-03-28",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 11,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-03-28",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "2024年年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=000338&announcementId=1222927963&orgId=9900002961&announcementTime=2025-03-28",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        }
      ]
    },
    {
      "code": "002281",
      "name": "光迅科技",
      "partner_status": "有强证据入口，待全文确认",
      "candidate_count": 16,
      "blocked_count": 0,
      "fulltext_count": 4,
      "low_confidence_count": 12,
      "candidates": [
        {
          "order": 1,
          "source": "互动易/巨潮问答",
          "kind": "问答主题候选，待补全文",
          "risk_level": "低置信",
          "question_time": "2026-06-22 08:29:00",
          "answer_time": "2026-06-23 10:07:14",
          "question": "你好，公司光互联vcsel芯片供应商是老鹰半导体吗？",
          "answer": "",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 2,
          "source": "互动易/巨潮问答",
          "kind": "问答主题候选，待补全文",
          "risk_level": "低置信",
          "question_time": "2026-04-23 06:14:55",
          "answer_time": "2026-04-23 11:04:46",
          "question": "看了公司的报表，请问公司：1、一季度存货六十多亿，创新高，是订单大幅增加备货吗？2、公司200G EML高端芯片开始出货了吗？美国光芯片订单2028年己基本卖完，供不应求，公司抓住机会的情况？有进行扩产吗？3、北美客户有1.6T的订单或出货吗？海外高端客户有认证或供货的进展顺利吗？机不可失。请及时互动交流，逐一帮助解惑，谢谢！",
          "answer": "",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 3,
          "source": "互动易/巨潮问答",
          "kind": "问答主题候选，待补全文",
          "risk_level": "低置信",
          "question_time": "2026-04-03 23:47:52",
          "answer_time": "2026-04-06 14:48:23",
          "question": "1.6T/3.2T是否只是讲故事，无实际订单？",
          "answer": "",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 4,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-03-20 17:22:28",
          "answer_time": "2026-04-03 19:39:02",
          "question": "董秘你好！贵司于3.13发布的公告称“涉及公司送样及潜在客户、取得大额订单、收入预测、技术突破、产能等相关信息，经核实，均为不实信息”，但于3.17公司官微上又称“双里程碑!光迅科技 3.2T NPO全球首发，业界率先完成头部CSP全系列验证”。请问贵司3.13公告所述内容是否存在虚假陈述？是否存在利用股东权力操纵市场以便于低价增发目的？",
          "answer": "投资者您好！\n公司生产经营一切正常。公司业务及经营情况请以公司定期报告及官方披露信息为准，感谢您的关注！",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 5,
          "source": "互动易/巨潮问答",
          "kind": "回答含名称但未达确认规则",
          "risk_level": "低置信",
          "question_time": "2026-03-18 16:46:49",
          "answer_time": "2026-04-03 19:36:32",
          "question": "3.17 日贵公司在回复央广记者采访的提问时，提到公司3.2 TNPO光模块已在几个月前完成送样，并通过头部厂商CSP认证。而且提到，在阿里云大会已公开并公司内部宣传过。请问董秘，贵公司是否已经供货阿里巴巴3.2 TNPO 光模块？同时，友商华工正源也说已供货阿里巴巴3.2TNPO光模块？请问谁是真的？",
          "answer": "投资者您好！\n公司在3月OFC 2026展会上推出了全球首款3.2T硅光单模NPO模块，已在国内头部CSP厂商完成全系列验证，感谢您的关注！",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [
            "阿里"
          ],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 6,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-03-18 10:49:14",
          "answer_time": "2026-04-03 19:35:32",
          "question": "公司此前官方公开表态（互动易+公告）：\n1. 互动易多次明确回复投资者1.6T光模块已完成客户送样、具备批量交付能力1.6TOSFP全系列产品已在2025年光博会正式展出，技术完全成熟。2.投资者交流会中公开表示，公司是国内唯一实现25G EML芯片自研量产的企业，100G EML芯片已完成送样测800G硅光模块量产良率达95%，属于明确的技术突破。公司是否违规操作股价发“利空公告”配合低价定增？",
          "answer": "投资者您好！\n公司生产经营一切正常。公司业务及经营情况请以公司定期报告及官方披露信息为准，感谢您的关注！",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 7,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-03-17 16:29:12",
          "answer_time": "2026-04-03 19:33:32",
          "question": "网络出现涉及公司送样及潜在客户、取得大额订单、收入预测、技术突破、产能等相关信息，具体指的是什么？",
          "answer": "投资者您好！\n公司生产经营一切正常。公司业务及经营情况请以公司定期报告及官方披露信息为准，感谢您的关注！",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 8,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-03-17 14:40:30",
          "answer_time": "2026-04-03 19:32:32",
          "question": "网络出现涉及公司送样及潜在客户、取得大额订单、收入预测、技术突破、产能等相关信息，具体指的是什么？要解释清楚这些内容为不实信息不等于公司在技术上不行，不等于公司没有积极开发潜在客户，也不等于公司未来不会取得大额订单。现在市场已经把那些所谓的不实信息与公司不行之间划等号了。",
          "answer": "投资者您好！\n公司生产经营一切正常。公司业务及经营情况请以公司定期报告及官方披露信息为准，感谢您的关注！",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 9,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-03-17 13:55:23",
          "answer_time": "2026-04-03 19:31:32",
          "question": "请问公司产能利用率怎样？华工科技公告订单排到了四季度，请问公司的订单怎样？是否也一样处于非常饱满状态？",
          "answer": "投资者您好！\n公司将结合市场需求合理安排产能，感谢您的关注！",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 10,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-03-16 18:41:20",
          "answer_time": "2026-04-03 19:29:32",
          "question": "·  公司在股票交易异常波动公告中提及网络存在关于送样、客户、订单、收入预测、技术突破、产能等不实信息，但本人通过公开渠道未检索到相关内容。请公司说明上述信息的具体来源、传播渠道及核实依据。\n·  公司在未明确信息来源的情况下公开澄清，易引发市场误解与恐慌，甚至被解读为配合定增压价。请公司正面回应：是否存在利用公告影响股价的情形？公司是否真实受益于行业大发展红利？",
          "answer": "投资者您好！\n公司生产经营一切正常。公司业务及经营情况请以公司定期报告及官方披露信息为准，感谢您的关注！",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 11,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-03-13 22:46:59",
          "answer_time": "2026-04-03 19:27:02",
          "question": "请问董秘，公司3月12号发布的公告说：有关贵公司取得大额订单等不实消息，请你提供一下网络权威媒体发布的相关消息的证据！如果有权威媒体或官方网络媒体发布的消息，为什么不第一时间澄清？如若没有，你应该给持有贵公司股票的广大投资者一个说法！我们广大投资者会保留是否诉诸法律？",
          "answer": "投资者您好！\n公司生产经营一切正常，公司业务及经营情况请以公司定期报告及官方披露信息为准。感谢您的关注！",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 12,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-03-13 16:25:18",
          "answer_time": "2026-04-03 19:26:02",
          "question": "请问公司在公告提高公司没有新技术突破，也没有新增大客户，以及大额订单，说明公司管理团队对公司经营非常糟糕。公司近期是否有降本增效，裁员降薪，以及撤回定增的计划。",
          "answer": "投资者您好！\n公司生产经营一切正常。公司业务及经营情况请以公司定期报告及官方披露信息为准，感谢您的关注！",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 13,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-05-21 00:00:00",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "武汉光迅科技股份有限公司股票交易异常波动暨风险提示公告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=002281&announcementId=1225321640&orgId=9900007888&announcementTime=2026-05-21 00:00:00",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 14,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-05-13 00:00:00",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "武汉光迅科技股份有限公司股票交易异常波动公告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=002281&announcementId=1225301563&orgId=9900007888&announcementTime=2026-05-13 00:00:00",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 15,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-05-08 00:00:00",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "武汉光迅科技股份有限公司股票交易异常波动公告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=002281&announcementId=1225282503&orgId=9900007888&announcementTime=2026-05-08 00:00:00",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 16,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-04-23 00:00:00",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "2025年年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=002281&announcementId=1225148212&orgId=9900007888&announcementTime=2026-04-23 00:00:00",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        }
      ]
    }
  ]
};
