const BATCH_A_PARTNER_CANDIDATE_WORKBENCH_V1 = {
  "generated_at": "2026-06-27 16:37:02",
  "source": "E:\\CODEX  zhuanyi\\网站规划工作区\\legacy_reports\\batch_a_workbench\\batch_a_partner_evidence_v1.json",
  "purpose": "第一批10家公司合作对象候选线索工作台。候选线索只用于后续全文解析或人工抽查，不直接进入正式报告。",
  "rules": [
    "提问里出现公司名但公司回答未确认，不得写入报告。",
    "公告标题只能作为强证据入口，未解析全文前不得写入合作对象。",
    "只有公告/年报/公司回答正文明确出现合作对象，并且没有否认或不披露表述，才可升级为已确认。"
  ],
  "summary": {
    "companies": 10,
    "candidate_items": 97,
    "blocked_items": 1,
    "fulltext_items": 76,
    "low_confidence_items": 20
  },
  "rows": [
    {
      "code": "002484",
      "name": "江海股份",
      "partner_status": "有强证据入口，待全文确认",
      "candidate_count": 13,
      "blocked_count": 1,
      "fulltext_count": 10,
      "low_confidence_count": 2,
      "candidates": [
        {
          "order": 1,
          "source": "互动易/巨潮问答",
          "kind": "提问提及名称，回答未确认",
          "risk_level": "不能写入",
          "question_time": "2026-06-02 13:05:02",
          "answer_time": "2026-06-03 09:45:05",
          "question": "你好董秘，东北计算机发布信息说谷歌和英伟达近期将会向公司下单MLPC和超级电容，预计订单超过30亿，请问是否属实？请正面回复，因为此信息对股价有直接影响。",
          "answer": "",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [
            "英伟达",
            "谷歌"
          ],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 2,
          "source": "互动易/巨潮问答",
          "kind": "问答主题候选，待补全文",
          "risk_level": "低置信",
          "question_time": "2026-05-25 17:28:25",
          "answer_time": "2026-05-26 16:19:43",
          "question": "请问公司的4N级高纯球形铝粉的供应情况如何？国内供应商是否能够满足需求？如果未来日本等外部发供应商中断供货，公司是否有相关预案？",
          "answer": "",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 3,
          "source": "互动易/巨潮问答",
          "kind": "问答主题候选，待补全文",
          "risk_level": "低置信",
          "question_time": "2026-03-31 23:34:06",
          "answer_time": "2026-04-01 10:23:16",
          "question": "董秘好,近日深圳全国首个万卡昇腾910C超节点智算集群投运,请问贵公司是否有参与这个项目的供货?",
          "answer": "",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 4,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-06-18",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "南通江海电容器股份有限公司关于股票交易异常波动的公告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=002484&announcementId=1225376481&orgId=9900014777&announcementTime=2026-06-18",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 5,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-06-05",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "南通江海电容器股份有限公司关于股票交易异常波动的公告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=002484&announcementId=1225351566&orgId=9900014777&announcementTime=2026-06-05",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 6,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-05-29",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "南通江海电容器股份有限公司关于股票交易异常波动的公告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=002484&announcementId=1225336772&orgId=9900014777&announcementTime=2026-05-29",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 7,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-05-20",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "南通江海电容器股份有限公司关于股票交易异常波动的公告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=002484&announcementId=1225317428&orgId=9900014777&announcementTime=2026-05-20",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 8,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-04-10",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "南通江海电容器股份有限公司关于2026年度日常经营关联交易预计情况的公告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=002484&announcementId=1225087182&orgId=9900014777&announcementTime=2026-04-10",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 9,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-04-10",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "2025年年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=002484&announcementId=1225087169&orgId=9900014777&announcementTime=2026-04-10",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 10,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-04-10",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "2025年年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=002484&announcementId=1225087168&orgId=9900014777&announcementTime=2026-04-10",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 11,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-09-01",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "南通江海电容器股份有限公司关于股票交易异常波动的公告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=002484&announcementId=1224618779&orgId=9900014777&announcementTime=2025-09-01",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 12,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-08-28",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "2025年半年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=002484&announcementId=1224590736&orgId=9900014777&announcementTime=2025-08-28",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 13,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-08-28",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "2025年半年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=002484&announcementId=1224590733&orgId=9900014777&announcementTime=2025-08-28",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        }
      ]
    },
    {
      "code": "000636",
      "name": "风华高科",
      "partner_status": "有强证据入口，待全文确认",
      "candidate_count": 16,
      "blocked_count": 0,
      "fulltext_count": 4,
      "low_confidence_count": 12,
      "candidates": [
        {
          "order": 1,
          "source": "互动易/巨潮问答",
          "kind": "问答主题候选，待补全文",
          "risk_level": "低置信",
          "question_time": "2026-06-22 15:42:26",
          "answer_time": "2026-06-23 16:43:55",
          "question": "董秘您好，据悉日韩及台系MLCC大厂（如国巨、华新科等）主动缩减/退出部分消费级低阶MLCC产能，贵公司作为国内MLCC龙头，是否承接了这部分转单？目前公司MLCC产能利用率如何？常规品与车规/AI高阶品的订单结构及稼动率是否有明显变化？谢谢！",
          "answer": "",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 2,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-06-14 19:22:29",
          "answer_time": "2026-06-23 15:00:05",
          "question": "你好，请问公司在mlcc整体货源紧缺全行业涨价的情况下，公司是否有再次提价的准备，以应对行业日益紧张的格局",
          "answer": "您好，公司将根据市场供求情况、客户及产品结构等因素制定价格策略。感谢您的关注！",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 3,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-06-13 09:07:28",
          "answer_time": "2026-06-23 15:00:05",
          "question": "你好，请问公司在mlcc供应紧缺外围头部扩产缓慢的情况下，有再次提价的应对准备吗",
          "answer": "您好，公司将根据市场供求情况、客户及产品结构等因素制定价格策略。感谢您的关注！",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 4,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-06-12 17:04:47",
          "answer_time": "2026-06-23 15:00:05",
          "question": "你好，作为公司长期投资者，请问公司在MLCC供不应求，国外巨头扩产缓慢的情况下，是否有再次提价的准备，",
          "answer": "您好，公司将根据市场供求情况、客户及产品结构等因素制定价格策略。感谢您的关注！",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 5,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-06-12 09:28:14",
          "answer_time": "2026-06-23 15:00:05",
          "question": "董秘你好，村田制作所已公开确认供应链拆分已完成，我们也同步收紧稀土出口管制，现在日系MLCC厂商减产和扩产困难已是共识。在此全球供需错配下，贵司是否能承接产能转移的能力？目前祥和工业园的高端产线设备是否会受制于人，能否实现自主可控？能否吃到本轮涨价红利，谢谢！",
          "answer": "您好，公司高度重视全球供应链格局变化带来的机遇与挑战，经过四十余年的行业深耕，已具备完整的材料、产品、装备三位一体产业布局，可为全球客户提供一站式产品采购服务和设计解决方案。感谢您的关注！",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 6,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-05-25 13:44:28",
          "answer_time": "2026-05-29 11:30:03",
          "question": "您好，请问公司依托军工高可靠技术平移，高频高容 MLCC 性能是否可对标日韩高端产品？目前是否已导入国内 AI 服务器、算力集群客户？公司高容、高频、车规 / AI 工业级 MLCC 产能是否计划 2026‑2027 年释放，以匹配 AI 算力需求，但是今年高端供不应求，为啥不考虑快速投产，还要到2027年才达产？？",
          "answer": "投资者您好，公司MLCC产品扩产项目“祥和工业园高端电容基地项目”已于 2025 年底全面建设完成，并于2026年4月完成结项，公司后续将根据自身规划并结合市场需求合理规划产能，感谢您的关注。",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 7,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-05-12 11:45:10",
          "answer_time": "2026-05-19 11:30:03",
          "question": "目前mlcc产品，全行业都在涨价，请问贵司目前价格是否有所上涨。贵司作为国企，在mlcc行业是否属于技术领先的，目前跟ai服务器公司是否有合作，贵司产品目前应用于电力行业多么，国家主推算电协同，贵司能否为这类型客户提供产品解决方案",
          "answer": "您好，公司将根据市场供求情况、客户及产品结构等因素制定价格策略。公司生产的MLCC、电阻、电感等被动元器件作为电子电路的基础组成部分，广泛应用于众多行业及领域。感谢您的关注！",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 8,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-05-08 10:40:49",
          "answer_time": "2026-05-19 11:30:03",
          "question": "公司作为高端MLCC领域国产替代的主力军，请问贵公司这方面的技术优势有哪些？",
          "answer": "您好！公司高度重视技术研发工作，坚持高效创新，重点关注新兴领域发展趋势和市场需求，围绕高可靠、高容量、高温度、高电压、高精密、高频率等六大高端方向持续开展技术开发和产品研发，并不断加强与高校、科研机构、产业链上下游合作，持续夯实公司长期发展的技术根基。感谢您的关注！",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 9,
          "source": "互动易/巨潮问答",
          "kind": "回答含名称但未达确认规则",
          "risk_level": "低置信",
          "question_time": "2026-05-06 15:55:09",
          "answer_time": "2026-05-11 11:30:04",
          "question": "风华高科作为“链主”企业，长期来看是要对标村田、三星电机做全球一线被动元件巨头，还是聚焦中国市场做国产替代龙头？公司对未来十年的愿景是什么？",
          "answer": "投资者您好，公司深耕电子元器件领域四十余年，不断夯实电子信息产业链的基础。公司将聚焦“3+2”产业布局，以容阻感三大支柱产业为核心，拓展超级电容与敏感元器件新兴赛道，不断提升公司核心竞争力，推动企业高质量发展。感谢您的关注！",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [
            "三星"
          ],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 10,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-05-06 15:21:11",
          "answer_time": "2026-05-11 11:30:04",
          "question": "公司依托广晟有色实现稀土原料协同供应，重稀土占全球供应70%。请问这一稀土闭环优势对提升MLCC产品耐压性、可靠性有怎样的直接作用？是否构成了竞争对手难以复制的壁垒？",
          "answer": "投资者您好，公司高度重视材料自主可控工作，通过自主研发和产业链战略合作等模式提升材料国产化和自产化比例，近年来核心材料自产化率持续提升。",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 11,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-05-06 15:20:58",
          "answer_time": "2026-05-11 11:30:04",
          "question": "近期全球地缘政治环境复杂多变，商务部对日本实施两用物資管制，供应链自主可控的紧迫性显著提升。请问如果日本对中国实施高端被动元器件出口管制，风华高科目前能在多大程度上实现国产替代？",
          "answer": "您好，公司高度重视全球供应链格局变化带来的机遇与挑战，经过四十余年的行业深耕，已构建完整的从材料、工艺到产品大规模研发制造的产品链，具备为全球客户提供整体配套及一站式采购服务和解决方案的能力。感谢您的关注！",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 12,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-05-06 15:20:09",
          "answer_time": "2026-05-11 11:30:04",
          "question": "村田明确表示AI服务器用MLCC需求将以年均30%以上的速度增长，2030年将较2025年增长3.3倍，高端MLCC已开始涨价。请问公司是否已经感受到这一轮由AI驱动的供需紧张？",
          "answer": "您好，新技术突破将持续为电子元器件市场需求带来新的增长点，公司将密切关注新兴领域发展趋势和市场需求变化情况，以市场为导向开展产品研发生产工作，为全球客户提供整体配套及一站式采购服务和解决方案。",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 13,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-06-18",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "关于股票交易异常波动的公告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=000636&announcementId=1225376901&orgId=gssz0000636&announcementTime=2026-06-18",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 14,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-06-01",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "关于股票交易异常波动的公告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=000636&announcementId=1225340262&orgId=gssz0000636&announcementTime=2026-06-01",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 15,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-05-26",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "关于股票交易异常波动的公告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=000636&announcementId=1225329698&orgId=gssz0000636&announcementTime=2026-05-26",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 16,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-05-21",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "关于股票交易异常波动的公告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=000636&announcementId=1225321639&orgId=gssz0000636&announcementTime=2026-05-21",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        }
      ]
    },
    {
      "code": "603989",
      "name": "艾华集团",
      "partner_status": "有强证据入口，待全文确认",
      "candidate_count": 10,
      "blocked_count": 0,
      "fulltext_count": 10,
      "low_confidence_count": 0,
      "candidates": [
        {
          "order": 1,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-06-26",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "湖南艾华集团股份有限公司股票交易异常波动公告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=603989&announcementId=1225388012&orgId=9900023223&announcementTime=2026-06-26",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 2,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-06-18",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "湖南艾华集团股份有限公司股票交易异常波动公告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=603989&announcementId=1225375858&orgId=9900023223&announcementTime=2026-06-18",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 3,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-05-29",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "湖南艾华集团股份有限公司股票交易异常波动公告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=603989&announcementId=1225336388&orgId=9900023223&announcementTime=2026-05-29",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 4,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-05-27",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "湖南艾华集团股份有限公司股票交易异常波动公告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=603989&announcementId=1225331147&orgId=9900023223&announcementTime=2026-05-27",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 5,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-05-20",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "湖南艾华集团股份有限公司股票交易异常波动公告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=603989&announcementId=1225317384&orgId=9900023223&announcementTime=2026-05-20",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 6,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-04-30",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "湖南艾华集团股份有限公司2025年年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=603989&announcementId=1225263683&orgId=9900023223&announcementTime=2026-04-30",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 7,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-04-30",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "湖南艾华集团股份有限公司2025年年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=603989&announcementId=1225263610&orgId=9900023223&announcementTime=2026-04-30",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 8,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-08-30",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "湖南艾华集团股份有限公司2025年半年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=603989&announcementId=1224625642&orgId=9900023223&announcementTime=2025-08-30",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 9,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-08-30",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "湖南艾华集团股份有限公司2025年半年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=603989&announcementId=1224625641&orgId=9900023223&announcementTime=2025-08-30",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 10,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-04-30",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "湖南艾华集团股份有限公司2024年年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=603989&announcementId=1223416714&orgId=9900023223&announcementTime=2025-04-30",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        }
      ]
    },
    {
      "code": "600522",
      "name": "中天科技",
      "partner_status": "有强证据入口，待全文确认",
      "candidate_count": 9,
      "blocked_count": 0,
      "fulltext_count": 9,
      "low_confidence_count": 0,
      "candidates": [
        {
          "order": 1,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-05-09",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "江苏中天科技股份有限公司股票交易异常波动的公告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600522&announcementId=1225285176&orgId=gssh0600522&announcementTime=2026-05-09",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 2,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-04-25",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "江苏中天科技股份有限公司2025年年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600522&announcementId=1225177318&orgId=gssh0600522&announcementTime=2026-04-25",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 3,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-04-25",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "江苏中天科技股份有限公司2025年年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600522&announcementId=1225177315&orgId=gssh0600522&announcementTime=2026-04-25",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 4,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-04-23",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "江苏中天科技股份有限公司股票交易异常波动的公告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600522&announcementId=1225146513&orgId=gssh0600522&announcementTime=2026-04-23",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 5,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-10-28",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "江苏中天科技股份有限公司关于增加与部分关联方2025年日常经营性关联交易的公告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600522&announcementId=1224742520&orgId=gssh0600522&announcementTime=2025-10-28",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 6,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-08-26",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "江苏中天科技股份有限公司2025年半年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600522&announcementId=1224564534&orgId=gssh0600522&announcementTime=2025-08-26",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 7,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-08-26",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "江苏中天科技股份有限公司2025年半年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600522&announcementId=1224564533&orgId=gssh0600522&announcementTime=2025-08-26",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 8,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-04-25",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "江苏中天科技股份有限公司2024年年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600522&announcementId=1223276680&orgId=gssh0600522&announcementTime=2025-04-25",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 9,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-04-25",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "江苏中天科技股份有限公司2024年年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600522&announcementId=1223276666&orgId=gssh0600522&announcementTime=2025-04-25",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        }
      ]
    },
    {
      "code": "600900",
      "name": "长江电力",
      "partner_status": "有强证据入口，待全文确认",
      "candidate_count": 6,
      "blocked_count": 0,
      "fulltext_count": 6,
      "low_confidence_count": 0,
      "candidates": [
        {
          "order": 1,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-04-30 00:00:00",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "长江电力2025年年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600900&announcementId=1225262042&orgId=gssh0600900&announcementTime=2026-04-30 00:00:00",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 2,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-04-30 00:00:00",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "长江电力2025年年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600900&announcementId=1225262036&orgId=gssh0600900&announcementTime=2026-04-30 00:00:00",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 3,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-08-30 00:00:00",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "长江电力2025年半年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600900&announcementId=1224627986&orgId=gssh0600900&announcementTime=2025-08-30 00:00:00",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 4,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-08-30 00:00:00",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "长江电力2025年半年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600900&announcementId=1224627985&orgId=gssh0600900&announcementTime=2025-08-30 00:00:00",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 5,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-04-30 00:00:00",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "长江电力2024年年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600900&announcementId=1223421172&orgId=gssh0600900&announcementTime=2025-04-30 00:00:00",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 6,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-04-30 00:00:00",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "长江电力2024年年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600900&announcementId=1223421164&orgId=gssh0600900&announcementTime=2025-04-30 00:00:00",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        }
      ]
    },
    {
      "code": "600025",
      "name": "华能水电",
      "partner_status": "有强证据入口，待全文确认",
      "candidate_count": 7,
      "blocked_count": 0,
      "fulltext_count": 7,
      "low_confidence_count": 0,
      "candidates": [
        {
          "order": 1,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-05-22",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "华能澜沧江水电股份有限公司投资者关系活动记录表",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600025&announcementId=1225322512&orgId=9900030360&announcementTime=2026-05-22",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 2,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-04-29",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "2025年年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600025&announcementId=1225231661&orgId=9900030360&announcementTime=2026-04-29",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 3,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-04-29",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "2025年年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600025&announcementId=1225231649&orgId=9900030360&announcementTime=2026-04-29",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 4,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-08-29",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "2025年半年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600025&announcementId=1224613750&orgId=9900030360&announcementTime=2025-08-29",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 5,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-08-29",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "2025年半年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600025&announcementId=1224613749&orgId=9900030360&announcementTime=2025-08-29",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 6,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-04-25",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "2024年年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600025&announcementId=1223273616&orgId=9900030360&announcementTime=2025-04-25",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 7,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-04-25",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "2024年年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600025&announcementId=1223273611&orgId=9900030360&announcementTime=2025-04-25",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        }
      ]
    },
    {
      "code": "600547",
      "name": "山东黄金",
      "partner_status": "有强证据入口，待全文确认",
      "candidate_count": 6,
      "blocked_count": 0,
      "fulltext_count": 6,
      "low_confidence_count": 0,
      "candidates": [
        {
          "order": 1,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-03-27 00:00:00",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "山东黄金矿业股份有限公司2025年年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600547&announcementId=1225035674&orgId=gssh0600547&announcementTime=2026-03-27 00:00:00",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 2,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-03-27 00:00:00",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "山东黄金矿业股份有限公司2025年年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600547&announcementId=1225035639&orgId=gssh0600547&announcementTime=2026-03-27 00:00:00",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 3,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-08-28 00:00:00",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "山东黄金矿业股份有限公司2025年半年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600547&announcementId=1224591284&orgId=gssh0600547&announcementTime=2025-08-28 00:00:00",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 4,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-08-28 00:00:00",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "山东黄金矿业股份有限公司2025年半年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600547&announcementId=1224591283&orgId=gssh0600547&announcementTime=2025-08-28 00:00:00",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 5,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-03-28 00:00:00",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "山东黄金矿业股份有限公司2024年年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600547&announcementId=1222928636&orgId=gssh0600547&announcementTime=2025-03-28 00:00:00",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 6,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-03-28 00:00:00",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "山东黄金矿业股份有限公司2024年年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600547&announcementId=1222928628&orgId=gssh0600547&announcementTime=2025-03-28 00:00:00",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        }
      ]
    },
    {
      "code": "600489",
      "name": "中金黄金",
      "partner_status": "有强证据入口，待全文确认",
      "candidate_count": 7,
      "blocked_count": 0,
      "fulltext_count": 7,
      "low_confidence_count": 0,
      "candidates": [
        {
          "order": 1,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-04-29 00:00:00",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "中金黄金股份有限公司2025年年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600489&announcementId=1225232907&orgId=gssh0600489&announcementTime=2026-04-29 00:00:00",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 2,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-04-29 00:00:00",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "中金黄金股份有限公司2025年年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600489&announcementId=1225232651&orgId=gssh0600489&announcementTime=2026-04-29 00:00:00",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 3,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-01-29 00:00:00",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "中金黄金股份有限公司股票交易异常波动公告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600489&announcementId=1224954418&orgId=gssh0600489&announcementTime=2026-01-29 00:00:00",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 4,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-08-29 00:00:00",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "中金黄金股份有限公司2025年半年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600489&announcementId=1224604436&orgId=gssh0600489&announcementTime=2025-08-29 00:00:00",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 5,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-08-29 00:00:00",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "中金黄金股份有限公司2025年半年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600489&announcementId=1224604433&orgId=gssh0600489&announcementTime=2025-08-29 00:00:00",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 6,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-04-30 00:00:00",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "中金黄金股份有限公司2024年年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600489&announcementId=1223413319&orgId=gssh0600489&announcementTime=2025-04-30 00:00:00",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 7,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-04-30 00:00:00",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "中金黄金股份有限公司2024年年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=600489&announcementId=1223413290&orgId=gssh0600489&announcementTime=2025-04-30 00:00:00",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        }
      ]
    },
    {
      "code": "603799",
      "name": "华友钴业",
      "partner_status": "有强证据入口，待全文确认",
      "candidate_count": 9,
      "blocked_count": 0,
      "fulltext_count": 9,
      "low_confidence_count": 0,
      "candidates": [
        {
          "order": 1,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-04-08 00:00:00",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "华友钴业2025年年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=603799&announcementId=1225083106&orgId=9900023781&announcementTime=2026-04-08 00:00:00",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 2,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-04-08 00:00:00",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "华友钴业2025年年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=603799&announcementId=1225083091&orgId=9900023781&announcementTime=2026-04-08 00:00:00",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 3,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-01-31 00:00:00",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "华友钴业关于子公司签订合作框架协议的公告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=603799&announcementId=1224959614&orgId=9900023781&announcementTime=2026-01-31 00:00:00",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 4,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-10-10 00:00:00",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "华友钴业股票交易异常波动公告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=603799&announcementId=1224703176&orgId=9900023781&announcementTime=2025-10-10 00:00:00",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 5,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-08-18 00:00:00",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "华友钴业2025年半年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=603799&announcementId=1224501101&orgId=9900023781&announcementTime=2025-08-18 00:00:00",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 6,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-08-18 00:00:00",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "华友钴业2025年半年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=603799&announcementId=1224501100&orgId=9900023781&announcementTime=2025-08-18 00:00:00",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 7,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-04-19 00:00:00",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "华友钴业2024年年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=603799&announcementId=1223152968&orgId=9900023781&announcementTime=2025-04-19 00:00:00",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 8,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-04-19 00:00:00",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "华友钴业2024年年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=603799&announcementId=1223152952&orgId=9900023781&announcementTime=2025-04-19 00:00:00",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 9,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-03-19 00:00:00",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "华友钴业关于子公司和北京卫蓝新能源科技股份有限公司签订战略合作协议的公告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=603799&announcementId=1222834729&orgId=9900023781&announcementTime=2025-03-19 00:00:00",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        }
      ]
    },
    {
      "code": "000426",
      "name": "兴业银锡",
      "partner_status": "有强证据入口，待全文确认",
      "candidate_count": 14,
      "blocked_count": 0,
      "fulltext_count": 8,
      "low_confidence_count": 6,
      "candidates": [
        {
          "order": 1,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-06-17 09:44:23",
          "answer_time": "2026-06-26 11:45:33",
          "question": "董秘您好，公司子公司发起FEG全面要约报价0.13澳元，当前二级市场股价0.17澳元，FEG董事会联合多家专业机构公开抵制收购，劝导股东拒绝要约。若本次收购最终失败，公司既无法取得FEG控股权，又与标的管理层合作关系破裂。请问公司如何看待本次收购存在两头落空的风险？后续是否计划上调要约对价？若收购失败，公司有无其他获取FEG黄金资产的布局方案？",
          "answer": "感谢您的关注！关于本次要约收购具体情况，请查阅和关注公司在指定媒体披露的公告。",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 2,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-06-01 09:28:38",
          "answer_time": "2026-06-26 11:45:33",
          "question": "董秘你好：2025年1月，兴业银锡与云南锡业签署战略合作框架协议；2026年5月23日，赤峰市政府、云南锡业、兴业银锡三方签署锡产业合作备忘录，共建“北方锡都”。公司总部位于赤峰，但核心锡矿（如银漫矿业）位于锡林郭勒盟，赤峰本地仅有宇邦等银铅锌矿山 。请问公司将通过哪些具体路径参与本次三方合作？如何统筹区内外矿山产能与物流，保障赤峰锡产业项目的原料稳定供应？",
          "answer": "感谢您的关注！公司将依托自身资源禀赋协同各方推进相关合作事宜，后续若涉及需披露的重大事项，公司将及时履行信息披露义务。",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 3,
          "source": "互动易/巨潮问答",
          "kind": "问答主题候选，待补全文",
          "risk_level": "低置信",
          "question_time": "2026-06-24 13:05:40",
          "answer_time": "2026-06-25 10:17:47",
          "question": "董秘你好：2024 年公司与 FEG 达成战略入股合作，本次全面要约收购未提前与对方董事会沟通，属于突发单方收购。想咨询管理层：本次收购发起的合理性逻辑是什么？是否预判到该行为会影响双方矿产项目协同合作？若后续 FEG 持续增发稀释我方股权，公司有何种应对安排？",
          "answer": "",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 4,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-04-30 14:21:14",
          "answer_time": "2026-05-12 15:45:33",
          "question": "董秘你好：请问公司2026年一季度新增披露的矿产铟业务，以及矿产锡、铋产量大幅下滑、铋零销售的原因是什么？",
          "answer": "感谢您的关注！①2026年一季度，公司经与客户议价，矿产锌中含铟达到计价标准。②公司当前锡产品全部来源于子公司银漫矿业，银漫矿业选矿厂分为铅锌和铜锡两个系列，铜锡原矿处理量、品位波动会造成锡产量的变化。银漫矿业2024年下半年以来主要开采17号主矿体，随着探矿工程持续推进，已在生产区域内新探明9、10小型附属矿体（品位整体低于17主矿体）。为实现资源综合回收利用，2025 年四季度以来铜锡矿石一部分来源于10号脉，导致回收率和锡产量环比下降。此外，一季度受春节放假、复工手续办理等因素影响，铜锡矿石选矿处理量相对较少。③2026年一季度生产矿产铋15.77吨，量较少未在一季度进行销售。",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 5,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-04-27 07:24:56",
          "answer_time": "2026-05-07 15:45:33",
          "question": "董秘你好，25年报披露的前5大客户中，新增加了丹东金朗贸易有限公司而且金额较大，请问这个客户背景资质有哪些？是公司关联方吗？公司对其销售合同条款，销售价格和其他客户一样公允吗？",
          "answer": "感谢您的关注！①丹东金朗贸易有限公司为公司2025年度新增客户，主要采购公司新并入的宇邦矿业所产银铅精矿。②2025年银金属价格大幅上涨，带动高价值含银产品销售收入相应增长，致使该客户销售金额排名靠前。③该客户已严格履行公司客户准入及资质审核流程，合作合同条款、定价政策均与其他客户保持一致，交易价格公允。该客户与公司不存在关联关系。",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 6,
          "source": "互动易/巨潮问答",
          "kind": "回答涉及客户/订单但无名称",
          "risk_level": "低置信",
          "question_time": "2026-04-23 23:23:30",
          "answer_time": "2026-05-07 15:45:33",
          "question": "董秘你好，我在股吧看到大家讨论公司年报，公司在收入增长的同时客户集中度和债务水平明显提升，因此想请教：\n\n① 前五大客户销售占比较高，其中第一大客户占比接近一半，请问客户结构及议价能力情况如何？\n② 短期及长期借款规模均明显上升，财务费用大幅增长，请问债务安排及对分红政策的影响如何？\n③ 收购宇邦矿业等导致投资现金流净流出较大，请问相关矿业权估值依据及减值风险管控措施如何？\n\n烦请说明，谢谢。",
          "answer": "感谢您的关注！①公司所处的有色金属采选业属于典型的资源密集型行业，长期呈现供需紧平衡状态，卖方市场特征显著。在此背景下，公司采用 “全额预收款”的销售模式，客户结构由冶炼终端和贸易商组成，主要选取行业信誉好、资金实力强、履约能力强与公司高度契合的客户合作。议价能力方面：公司产品数量、品质稳定，供货保障能力强，在区域及品类供给端具备自身竞争优势，且产品市场需求处于紧平衡状态，与核心客户形成战略互利合作模式，公司与所有客户的合作方式相同，均通过议价、签订合同、预付货款、交付货物、检验结算的模式完成；同时公司持续拓展优质客户，不断优化客户结构拓宽销售渠道。②报告期内，公司借款规模上升，系公司基于自身经营规模扩张及长远战略发展需要而实施的融资安排。公司旨在适度增加债务融资规模，优化资本结构，并有效控制综合融资成本。尽管财务费用有所上升，但公司经营性现金流持续改善、业绩稳步增长，具备充足的债务覆盖能力，债务风险可控。③ 矿业权由专业机构按准则评估。公司严格执行减值测试制度，定期核查减值迹象，每年对商誉及无形资产进行减值测试；外部评估时公司会复核关键参数，严控减值风险。",
          "title": "",
          "url": "",
          "partners_mentioned_by_question": [],
          "reason": "互动易问答涉及客户/供应商/合作，但没有形成可直接写入报告的明确合作对象。"
        },
        {
          "order": 7,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-04-22 00:00:00",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "2025年年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=000426&announcementId=1225136963&orgId=gssz0000426&announcementTime=2026-04-22 00:00:00",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 8,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2026-04-22 00:00:00",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "2025年年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=000426&announcementId=1225136962&orgId=gssz0000426&announcementTime=2026-04-22 00:00:00",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 9,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-08-26 00:00:00",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "2025年半年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=000426&announcementId=1224567375&orgId=gssz0000426&announcementTime=2025-08-26 00:00:00",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 10,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-08-26 00:00:00",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "2025年半年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=000426&announcementId=1224567363&orgId=gssz0000426&announcementTime=2025-08-26 00:00:00",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 11,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-04-28 00:00:00",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "2024年年度报告摘要",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=000426&announcementId=1223317586&orgId=gssz0000426&announcementTime=2025-04-28 00:00:00",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 12,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-04-28 00:00:00",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "2024年年度报告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=000426&announcementId=1223317584&orgId=gssz0000426&announcementTime=2025-04-28 00:00:00",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 13,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-03-21 00:00:00",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "关于公司与中铁隧道局集团有限公司签署《战略合作框架协议》的公告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=000426&announcementId=1222855729&orgId=gssz0000426&announcementTime=2025-03-21 00:00:00",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        },
        {
          "order": 14,
          "source": "巨潮公告标题",
          "kind": "公告标题候选，待全文",
          "risk_level": "待解析",
          "question_time": "2025-01-22 00:00:00",
          "answer_time": "",
          "question": "",
          "answer": "",
          "title": "关于公司与云南锡业股份有限公司签署《战略合作框架协议》的公告",
          "url": "http://www.cninfo.com.cn/new/disclosure/detail?stockCode=000426&announcementId=1222388022&orgId=gssz0000426&announcementTime=2025-01-22 00:00:00",
          "partners_mentioned_by_question": [],
          "reason": "公告标题为强证据候选入口；当前未解析公告全文，不直接写合作对象。"
        }
      ]
    }
  ]
};
