const CORE9_EXTERNAL_EVIDENCE_CARDS_V1 = {
  "generated_at": "2026/6/28 10:37:21",
  "purpose": "首页1-9号外部补充候选证据卡。仅用于本地复核，不直接覆盖线上分类。",
  "summary": {
    "total": 5,
    "proposed_first_batch": 5,
    "high_confidence": 5,
    "confirmed_partner_companies": 0
  },
  "cards": [
    {
      "order": 1,
      "concept_seq": 2,
      "concept_id": "optical_module",
      "concept_name": "光模块/CPO",
      "code": "002281",
      "name": "光迅科技",
      "target_landing": "光模块/CPO / 光器件与光模块",
      "candidate_status": "拟纳入首批候选",
      "include_first_batch": true,
      "confidence": "high",
      "classification_reason": "主营为光电子器件、模块和子系统，产品含传输、接入、数据通信类产品，和光模块/CPO主线匹配度高。",
      "business_summary": "光电子器件、模块和子系统的研发、生产及销售。",
      "products": [
        "传输类产品",
        "接入类产品",
        "数据通信类产品"
      ],
      "business_scope_excerpt": "信息科技领域光、电器件技术及产品的研制、生产、销售和相关技术服务；信息系统的工程设计、施工、系统集成；信息咨询服务；计算机软、硬件研制、开发、系统集成；网络及数据通信产品的开发、生产、销售；软件开发与技术服务；安全技术防范产品的生产、销售；货物进出口、技术进出口、代理进出口。（依法须经批准的项目，经相关部门批准后方可开展经营活动）",
      "business_source": "AkShare stock_zyjs_ths / 同花顺公开资料口径",
      "net_profit_yi": 2.32,
      "net_profit_yoy_pct": 60,
      "financial_period": "2026-03-31",
      "improvement": "净利润同比改善",
      "market_strength_score": 59,
      "market_strength_label": "中性",
      "ret_5d_pct": -9.71,
      "ret_10d_pct": 17.01,
      "ret_20d_pct": 11.84,
      "ret_60d_pct": 184.43,
      "market_role": "弱于本组领涨股",
      "peer_rank": 5,
      "peer_count": 5,
      "partner_status": "有强证据入口，待全文确认",
      "confirmed_partners": [],
      "partner_conclusion": "无；当前只保留为待补证据，不写入正式合作对象。",
      "announcement_fulltext_strong_count": 0,
      "candidate_source_count": 16,
      "source_report_path": "batch_b_partner_candidate_workbench.html?v=core9-ext",
      "local_batch_source": "legacy_p0_batch_b_workbench_v1 / batch_b_partner_candidate_workbench_v1 / batch_b_announcement_fulltext_evidence_v1",
      "remaining_gaps": [
        "明确披露的上下游合作对象",
        "V2报告暂缓，等待分类纠偏复核"
      ],
      "risk_level": "中：报告未升级，分类先作为候选",
      "next_action": "进入首页1-9首批候选清单；生成完整V2报告前，需要补年报原文/主营占比/上下游合作对象证据。"
    },
    {
      "order": 2,
      "concept_seq": 3,
      "concept_id": "pcb_high_speed",
      "concept_name": "PCB/高速PCB",
      "code": "002384",
      "name": "东山精密",
      "target_landing": "PCB/高速PCB / 软板、硬板、软硬结合板",
      "candidate_status": "拟纳入首批候选",
      "include_first_batch": true,
      "confidence": "high",
      "classification_reason": "产品覆盖软板、硬板、软硬结合板，同时具备光模块与精密组件线索，适合进入PCB主线并保留光模块交叉标签。",
      "business_summary": "电子电路、光模块（含光芯片）、精密组件、光电显示模组的全球设计、生产和销售。",
      "products": [
        "软板",
        "硬板",
        "软硬结合板",
        "光芯片",
        "数据中心光模块",
        "电信光模块",
        "汽车零部件",
        "水冷板",
        "通信设备组件",
        "触控面板",
        "LCD及OLED模组"
      ],
      "business_scope_excerpt": "一般项目：锻件及粉末冶金制品制造；锻件及粉末冶金制品销售；金属表面处理及热处理加工；通信设备制造；通信设备销售；技术服务、技术开发、技术咨询、技术交流、技术转让、技术推广；电子元器件零售；显示器件销售；货物进出口；技术进出口；仪器仪表制造；仪器仪表销售；机械零件、零部件加工；通用设备制造（不含特种设备制造）；机械设备租赁；汽车零部件及配件制造；汽车零配件零售；电池零配件生产；电池零配件销售；新能源汽车电附件销售；电子元器件批发；电子元器",
      "business_source": "AkShare stock_zyjs_ths / 同花顺公开资料口径",
      "net_profit_yi": 11.24,
      "net_profit_yoy_pct": 143,
      "financial_period": "2026-03-31",
      "improvement": "净利润同比改善",
      "market_strength_score": 73,
      "market_strength_label": "偏强",
      "ret_5d_pct": -4.64,
      "ret_10d_pct": 23.38,
      "ret_20d_pct": 18.87,
      "ret_60d_pct": 153.6,
      "market_role": "弱于本组领涨股",
      "peer_rank": 3,
      "peer_count": 5,
      "partner_status": "有强证据入口，待全文确认",
      "confirmed_partners": [],
      "partner_conclusion": "无；当前只保留为待补证据，不写入正式合作对象。",
      "announcement_fulltext_strong_count": 0,
      "candidate_source_count": 16,
      "source_report_path": "batch_b_partner_candidate_workbench.html?v=core9-ext",
      "local_batch_source": "legacy_p0_batch_b_workbench_v1 / batch_b_partner_candidate_workbench_v1 / batch_b_announcement_fulltext_evidence_v1",
      "remaining_gaps": [
        "明确披露的上下游合作对象",
        "V2报告暂缓，等待分类纠偏复核"
      ],
      "risk_level": "中：报告未升级，分类先作为候选",
      "next_action": "进入首页1-9首批候选清单；生成完整V2报告前，需要补年报原文/主营占比/上下游合作对象证据。"
    },
    {
      "order": 3,
      "concept_seq": 3,
      "concept_id": "pcb_high_speed",
      "concept_name": "PCB/高速PCB",
      "code": "002916",
      "name": "深南电路",
      "target_landing": "PCB/高速PCB / PCB与封装基板",
      "candidate_status": "拟纳入首批候选",
      "include_first_batch": true,
      "confidence": "high",
      "classification_reason": "主营为印制电路板、封装基板及电子装联，属于PCB和先进封装上游关键环节。",
      "business_summary": "印制电路板、封装基板及电子装联产品的研发、生产及销售。",
      "products": [
        "印制电路板产品",
        "封装基板产品",
        "电子装联"
      ],
      "business_scope_excerpt": "一般经营项目是：电镀、鉴证咨询、不动产租赁服务、经营进出口业务、技术研发及信息技术咨询、物业管理。计算机软硬件及外围设备制造；计算机软硬件及辅助设备批发；计算机软硬件及辅助设备零售。（除依法须经批准的项目外，凭营业执照依法自主开展经营活动），许可经营项目是：印刷电路板、封装基板产品、模块模组封装产品、电子装联产品、电子元器件、网络通讯科技产品、通信设备的研制、生产、加工、服务、销售；工业自动化设备、电信终端设备、信息技术类设备、LED产",
      "business_source": "AkShare stock_zyjs_ths / 同花顺公开资料口径",
      "net_profit_yi": 8.51,
      "net_profit_yoy_pct": 73,
      "financial_period": "2026-03-31",
      "improvement": "净利润同比改善",
      "market_strength_score": 60,
      "market_strength_label": "偏强",
      "ret_5d_pct": -4.47,
      "ret_10d_pct": 15.24,
      "ret_20d_pct": 9.5,
      "ret_60d_pct": 87.03,
      "market_role": "弱于本组领涨股",
      "peer_rank": 4,
      "peer_count": 5,
      "partner_status": "有强证据入口，待全文确认",
      "confirmed_partners": [],
      "partner_conclusion": "无；当前只保留为待补证据，不写入正式合作对象。",
      "announcement_fulltext_strong_count": 0,
      "candidate_source_count": 14,
      "source_report_path": "batch_b_partner_candidate_workbench.html?v=core9-ext",
      "local_batch_source": "legacy_p0_batch_b_workbench_v1 / batch_b_partner_candidate_workbench_v1 / batch_b_announcement_fulltext_evidence_v1",
      "remaining_gaps": [
        "明确披露的上下游合作对象",
        "V2报告暂缓，等待分类纠偏复核"
      ],
      "risk_level": "中：报告未升级，分类先作为候选",
      "next_action": "进入首页1-9首批候选清单；生成完整V2报告前，需要补年报原文/主营占比/上下游合作对象证据。"
    },
    {
      "order": 4,
      "concept_seq": 3,
      "concept_id": "pcb_high_speed",
      "concept_name": "PCB/高速PCB",
      "code": "600183",
      "name": "生益科技",
      "target_landing": "PCB/高速PCB / 覆铜板与电子材料",
      "candidate_status": "拟纳入首批候选",
      "include_first_batch": true,
      "confidence": "high",
      "classification_reason": "主营为覆铜板、粘结片和印制线路板，是PCB上游材料与板材环节，适合以CCL/覆铜板子概念入池。",
      "business_summary": "设计、生产和销售覆铜板和粘结片、印制线路板。",
      "products": [
        "覆铜板",
        "粘结片",
        "印制线路板",
        "房地产",
        "废弃资源综合利用"
      ],
      "business_scope_excerpt": "设计、生产和销售覆铜板和粘结片、陶瓷电子元件、液晶产品、电子级玻璃布、环氧树脂、铜箔、电子用挠性材料、显示材料、封装材料、绝缘材料；自有房屋出租；从事非配额许可证管理、非专营商品的收购出口业务；提供产品服务、技术服务、咨询服务、加工服务和佣金代理(拍卖除外)。",
      "business_source": "AkShare stock_zyjs_ths / 同花顺公开资料口径",
      "net_profit_yi": 13.32,
      "net_profit_yoy_pct": 105,
      "financial_period": "2026-03-31",
      "improvement": "净利润同比改善",
      "market_strength_score": 93,
      "market_strength_label": "强势",
      "ret_5d_pct": -292,
      "ret_10d_pct": 19.21,
      "ret_20d_pct": 32.33,
      "ret_60d_pct": 227.85,
      "market_role": "弱于本组领涨股",
      "peer_rank": 2,
      "peer_count": 5,
      "partner_status": "有强证据入口，待全文确认",
      "confirmed_partners": [],
      "partner_conclusion": "无；当前只保留为待补证据，不写入正式合作对象。",
      "announcement_fulltext_strong_count": 0,
      "candidate_source_count": 7,
      "source_report_path": "batch_b_partner_candidate_workbench.html?v=core9-ext",
      "local_batch_source": "legacy_p0_batch_b_workbench_v1 / batch_b_partner_candidate_workbench_v1 / batch_b_announcement_fulltext_evidence_v1",
      "remaining_gaps": [
        "明确披露的上下游合作对象",
        "V2报告暂缓，等待分类纠偏复核"
      ],
      "risk_level": "中：报告未升级，分类先作为候选",
      "next_action": "进入首页1-9首批候选清单；生成完整V2报告前，需要补年报原文/主营占比/上下游合作对象证据。"
    },
    {
      "order": 5,
      "concept_seq": 6,
      "concept_id": "passive_components",
      "concept_name": "电子元器件/被动元器件",
      "code": "600888",
      "name": "新疆众和",
      "target_landing": "电子元器件/被动元器件 / 铝电解电容材料",
      "candidate_status": "拟纳入首批候选",
      "include_first_batch": true,
      "confidence": "high",
      "classification_reason": "主营与产品包含电子铝箔、电极箔、高纯铝，对应铝电解电容材料链，适合作为被动元器件上游材料候选。",
      "business_summary": "铝电子新材料和铝及合金制品的研发、生产和销售。",
      "products": [
        "电子铝箔",
        "电极箔",
        "高纯铝",
        "铝制品及合金产品"
      ],
      "business_scope_excerpt": "发电；经营道路运输业务；对外承包工程业务经营；高纯铝、电子铝箔、腐蚀箔、化成箔电子元器件原料、铝及铝制品、铝合金、炭素的生产、销售；经营本企业自产产品及相关技术的出口业务；金属门窗工程专业承包叁级；经营本企业生产、科研所需的原辅材料、机械设备、仪器仪表、零配件及相关技术的进口业务；经营本企业的进料加工和“三来一补”业务；本企业生产废旧物资的销售；非标准机加工件、钢结构件、机电产品的制造、安装、销售；金属支架的制造、安装及电器设备安装；线",
      "business_source": "AkShare stock_zyjs_ths / 同花顺公开资料口径",
      "net_profit_yi": 2.64,
      "net_profit_yoy_pct": 20,
      "financial_period": "2026-03-31",
      "improvement": "净利润同比改善",
      "market_strength_score": 100,
      "market_strength_label": "强势",
      "ret_5d_pct": 22.68,
      "ret_10d_pct": 46.41,
      "ret_20d_pct": 35.36,
      "ret_60d_pct": 98.42,
      "market_role": "本组阶段领涨",
      "peer_rank": 1,
      "peer_count": 5,
      "partner_status": "有强证据入口，待全文确认",
      "confirmed_partners": [],
      "partner_conclusion": "无；当前只保留为待补证据，不写入正式合作对象。",
      "announcement_fulltext_strong_count": 0,
      "candidate_source_count": 8,
      "source_report_path": "batch_b_partner_candidate_workbench.html?v=core9-ext",
      "local_batch_source": "legacy_p0_batch_b_workbench_v1 / batch_b_partner_candidate_workbench_v1 / batch_b_announcement_fulltext_evidence_v1",
      "remaining_gaps": [
        "明确披露的上下游合作对象",
        "V2报告暂缓，等待分类纠偏复核"
      ],
      "risk_level": "中：报告未升级，分类先作为候选",
      "next_action": "进入首页1-9首批候选清单；生成完整V2报告前，需要补年报原文/主营占比/上下游合作对象证据。"
    }
  ]
};
