const CORE9_V2_REPORT_BATCH_001_QC_V1 = {
  "generated_at": "2026/6/28 10:56:42",
  "purpose": "batch_001 V2报告本地质检",
  "summary": {
    "total": 20,
    "pass": 20,
    "need_review": 0
  },
  "rows": [
    {
      "code": "600888",
      "name": "新疆众和",
      "html_path": "reports_v2_core9_batch_001/新疆众和_V2深度报告.html",
      "text_chars": 6263,
      "chapters_count": 9,
      "has_front_financials": true,
      "has_partner_rule": true,
      "forbidden_words": [],
      "pass": true,
      "note": "通过本地结构质检"
    },
    {
      "code": "600183",
      "name": "生益科技",
      "html_path": "reports_v2_core9_batch_001/生益科技_V2深度报告.html",
      "text_chars": 5477,
      "chapters_count": 9,
      "has_front_financials": true,
      "has_partner_rule": true,
      "forbidden_words": [],
      "pass": true,
      "note": "通过本地结构质检"
    },
    {
      "code": "002384",
      "name": "东山精密",
      "html_path": "reports_v2_core9_batch_001/东山精密_V2深度报告.html",
      "text_chars": 5493,
      "chapters_count": 9,
      "has_front_financials": true,
      "has_partner_rule": true,
      "forbidden_words": [],
      "pass": true,
      "note": "通过本地结构质检"
    },
    {
      "code": "002916",
      "name": "深南电路",
      "html_path": "reports_v2_core9_batch_001/深南电路_V2深度报告.html",
      "text_chars": 5476,
      "chapters_count": 9,
      "has_front_financials": true,
      "has_partner_rule": true,
      "forbidden_words": [],
      "pass": true,
      "note": "通过本地结构质检"
    },
    {
      "code": "002281",
      "name": "光迅科技",
      "html_path": "reports_v2_core9_batch_001/光迅科技_V2深度报告.html",
      "text_chars": 5448,
      "chapters_count": 9,
      "has_front_financials": true,
      "has_partner_rule": true,
      "forbidden_words": [],
      "pass": true,
      "note": "通过本地结构质检"
    },
    {
      "code": "603019",
      "name": "中科曙光",
      "html_path": "reports_v2_core9_batch_001/中科曙光_V2深度报告.html",
      "text_chars": 5487,
      "chapters_count": 9,
      "has_front_financials": true,
      "has_partner_rule": true,
      "forbidden_words": [],
      "pass": true,
      "note": "通过本地结构质检"
    },
    {
      "code": "000938",
      "name": "紫光股份",
      "html_path": "reports_v2_core9_batch_001/紫光股份_V2深度报告.html",
      "text_chars": 5998,
      "chapters_count": 9,
      "has_front_financials": true,
      "has_partner_rule": true,
      "forbidden_words": [],
      "pass": true,
      "note": "通过本地结构质检"
    },
    {
      "code": "002484",
      "name": "江海股份",
      "html_path": "reports_v2_core9_batch_001/江海股份_V2深度报告.html",
      "text_chars": 6050,
      "chapters_count": 9,
      "has_front_financials": true,
      "has_partner_rule": true,
      "forbidden_words": [],
      "pass": true,
      "note": "通过本地结构质检"
    },
    {
      "code": "603989",
      "name": "艾华集团",
      "html_path": "reports_v2_core9_batch_001/艾华集团_V2深度报告.html",
      "text_chars": 6169,
      "chapters_count": 9,
      "has_front_financials": true,
      "has_partner_rule": true,
      "forbidden_words": [],
      "pass": true,
      "note": "通过本地结构质检"
    },
    {
      "code": "002902",
      "name": "铭普光磁",
      "html_path": "reports_v2_core9_batch_001/铭普光磁_V2深度报告.html",
      "text_chars": 6355,
      "chapters_count": 9,
      "has_front_financials": true,
      "has_partner_rule": true,
      "forbidden_words": [],
      "pass": true,
      "note": "通过本地结构质检"
    },
    {
      "code": "603328",
      "name": "依顿电子",
      "html_path": "reports_v2_core9_batch_001/依顿电子_V2深度报告.html",
      "text_chars": 6250,
      "chapters_count": 9,
      "has_front_financials": true,
      "has_partner_rule": true,
      "forbidden_words": [],
      "pass": true,
      "note": "通过本地结构质检"
    },
    {
      "code": "001389",
      "name": "广合科技",
      "html_path": "reports_v2_core9_batch_001/广合科技_V2深度报告.html",
      "text_chars": 6032,
      "chapters_count": 9,
      "has_front_financials": true,
      "has_partner_rule": true,
      "forbidden_words": [],
      "pass": true,
      "note": "通过本地结构质检"
    },
    {
      "code": "002463",
      "name": "沪电股份",
      "html_path": "reports_v2_core9_batch_001/沪电股份_V2深度报告.html",
      "text_chars": 5490,
      "chapters_count": 9,
      "has_front_financials": true,
      "has_partner_rule": true,
      "forbidden_words": [],
      "pass": true,
      "note": "通过本地结构质检"
    },
    {
      "code": "300308",
      "name": "中际旭创",
      "html_path": "reports_v2_core9_batch_001/中际旭创_V2深度报告.html",
      "text_chars": 5517,
      "chapters_count": 9,
      "has_front_financials": true,
      "has_partner_rule": true,
      "forbidden_words": [],
      "pass": true,
      "note": "通过本地结构质检"
    },
    {
      "code": "300502",
      "name": "新易盛",
      "html_path": "reports_v2_core9_batch_001/新易盛_V2深度报告.html",
      "text_chars": 5501,
      "chapters_count": 9,
      "has_front_financials": true,
      "has_partner_rule": true,
      "forbidden_words": [],
      "pass": true,
      "note": "通过本地结构质检"
    },
    {
      "code": "601138",
      "name": "工业富联",
      "html_path": "reports_v2_core9_batch_001/工业富联_V2深度报告.html",
      "text_chars": 5496,
      "chapters_count": 9,
      "has_front_financials": true,
      "has_partner_rule": true,
      "forbidden_words": [],
      "pass": true,
      "note": "通过本地结构质检"
    },
    {
      "code": "688041",
      "name": "海光信息",
      "html_path": "reports_v2_core9_batch_001/海光信息_V2深度报告.html",
      "text_chars": 5504,
      "chapters_count": 9,
      "has_front_financials": true,
      "has_partner_rule": true,
      "forbidden_words": [],
      "pass": true,
      "note": "通过本地结构质检"
    },
    {
      "code": "688256",
      "name": "寒武纪",
      "html_path": "reports_v2_core9_batch_001/寒武纪_V2深度报告.html",
      "text_chars": 5497,
      "chapters_count": 9,
      "has_front_financials": true,
      "has_partner_rule": true,
      "forbidden_words": [],
      "pass": true,
      "note": "通过本地结构质检"
    },
    {
      "code": "002156",
      "name": "通富微电",
      "html_path": "reports_v2_core9_batch_001/通富微电_V2深度报告.html",
      "text_chars": 5528,
      "chapters_count": 9,
      "has_front_financials": true,
      "has_partner_rule": true,
      "forbidden_words": [],
      "pass": true,
      "note": "通过本地结构质检"
    },
    {
      "code": "600584",
      "name": "长电科技",
      "html_path": "reports_v2_core9_batch_001/长电科技_V2深度报告.html",
      "text_chars": 5545,
      "chapters_count": 9,
      "has_front_financials": true,
      "has_partner_rule": true,
      "forbidden_words": [],
      "pass": true,
      "note": "通过本地结构质检"
    }
  ]
};
