const CORE9_CLASSIFICATION_RECALIBRATION_AFTER_BATCH001_V1 = {
  "generated_at": "2026/6/28 10:58:33",
  "purpose": "batch_001生成后首页1-9分类校准结果。本文件不改线上分类，只标记报告覆盖状态和后续校准优先级。",
  "summary": {
    "concepts": 9,
    "batch001_generated": 20,
    "qc_pass": 20,
    "memberships": 287,
    "new_report_memberships": 29
  },
  "concepts": [
    {
      "seq": 1,
      "concept_id": "ai_compute",
      "concept_name": "AI算力",
      "first_batch_count": 33,
      "coverage": {
        "new_batch001": 11,
        "v2_existing": 1,
        "legacy_fallback": 21,
        "none": 0
      },
      "calibration_note": "已接入batch_001新版草稿，可用于反向校准标签"
    },
    {
      "seq": 2,
      "concept_id": "optical_module",
      "concept_name": "光模块/CPO",
      "first_batch_count": 4,
      "coverage": {
        "new_batch001": 4,
        "v2_existing": 0,
        "legacy_fallback": 0,
        "none": 0
      },
      "calibration_note": "已接入batch_001新版草稿，可用于反向校准标签"
    },
    {
      "seq": 3,
      "concept_id": "pcb_high_speed",
      "concept_name": "PCB/高速PCB",
      "first_batch_count": 15,
      "coverage": {
        "new_batch001": 5,
        "v2_existing": 0,
        "legacy_fallback": 10,
        "none": 0
      },
      "calibration_note": "已接入batch_001新版草稿，可用于反向校准标签"
    },
    {
      "seq": 4,
      "concept_id": "semiconductor",
      "concept_name": "半导体",
      "first_batch_count": 10,
      "coverage": {
        "new_batch001": 4,
        "v2_existing": 2,
        "legacy_fallback": 4,
        "none": 0
      },
      "calibration_note": "已接入batch_001新版草稿，可用于反向校准标签"
    },
    {
      "seq": 5,
      "concept_id": "advanced_packaging",
      "concept_name": "封装测试/先进封装",
      "first_batch_count": 4,
      "coverage": {
        "new_batch001": 2,
        "v2_existing": 2,
        "legacy_fallback": 0,
        "none": 0
      },
      "calibration_note": "已接入batch_001新版草稿，可用于反向校准标签"
    },
    {
      "seq": 6,
      "concept_id": "passive_components",
      "concept_name": "电子元器件/被动元器件",
      "first_batch_count": 5,
      "coverage": {
        "new_batch001": 3,
        "v2_existing": 1,
        "legacy_fallback": 1,
        "none": 0
      },
      "calibration_note": "已接入batch_001新版草稿，可用于反向校准标签"
    },
    {
      "seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "first_batch_count": 79,
      "coverage": {
        "new_batch001": 0,
        "v2_existing": 0,
        "legacy_fallback": 79,
        "none": 0
      },
      "calibration_note": "待后续批次生成后校准"
    },
    {
      "seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "first_batch_count": 57,
      "coverage": {
        "new_batch001": 0,
        "v2_existing": 5,
        "legacy_fallback": 49,
        "none": 3
      },
      "calibration_note": "待后续批次生成后校准"
    },
    {
      "seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "first_batch_count": 80,
      "coverage": {
        "new_batch001": 0,
        "v2_existing": 0,
        "legacy_fallback": 79,
        "none": 1
      },
      "calibration_note": "待后续批次生成后校准"
    }
  ],
  "rows": [
    {
      "concept_seq": 1,
      "concept_id": "ai_compute",
      "concept_name": "AI算力",
      "code": "688041",
      "name": "海光信息",
      "report_status": "batch_001新版草稿",
      "report_priority": "new_batch001",
      "batch": "batch_001",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 1,
      "concept_id": "ai_compute",
      "concept_name": "AI算力",
      "code": "000682",
      "name": "东方电子",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 1,
      "concept_id": "ai_compute",
      "concept_name": "AI算力",
      "code": "000938",
      "name": "紫光股份",
      "report_status": "batch_001新版草稿",
      "report_priority": "new_batch001",
      "batch": "batch_001",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 1,
      "concept_id": "ai_compute",
      "concept_name": "AI算力",
      "code": "002063",
      "name": "远光软件",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 1,
      "concept_id": "ai_compute",
      "concept_name": "AI算力",
      "code": "002195",
      "name": "岩山科技",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 1,
      "concept_id": "ai_compute",
      "concept_name": "AI算力",
      "code": "002380",
      "name": "科远智慧",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 1,
      "concept_id": "ai_compute",
      "concept_name": "AI算力",
      "code": "002410",
      "name": "广联达",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 1,
      "concept_id": "ai_compute",
      "concept_name": "AI算力",
      "code": "002421",
      "name": "达实智能",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 1,
      "concept_id": "ai_compute",
      "concept_name": "AI算力",
      "code": "002439",
      "name": "启明星辰",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 1,
      "concept_id": "ai_compute",
      "concept_name": "AI算力",
      "code": "002463",
      "name": "沪电股份",
      "report_status": "batch_001新版草稿",
      "report_priority": "new_batch001",
      "batch": "batch_001",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 1,
      "concept_id": "ai_compute",
      "concept_name": "AI算力",
      "code": "002544",
      "name": "普天科技",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 1,
      "concept_id": "ai_compute",
      "concept_name": "AI算力",
      "code": "002657",
      "name": "中科金财",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 1,
      "concept_id": "ai_compute",
      "concept_name": "AI算力",
      "code": "002851",
      "name": "麦格米特",
      "report_status": "已有新版",
      "report_priority": "v2_existing",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 1,
      "concept_id": "ai_compute",
      "concept_name": "AI算力",
      "code": "003010",
      "name": "若羽臣",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 1,
      "concept_id": "ai_compute",
      "concept_name": "AI算力",
      "code": "003029",
      "name": "吉大正元",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 1,
      "concept_id": "ai_compute",
      "concept_name": "AI算力",
      "code": "300308",
      "name": "中际旭创",
      "report_status": "batch_001新版草稿",
      "report_priority": "new_batch001",
      "batch": "batch_001",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 1,
      "concept_id": "ai_compute",
      "concept_name": "AI算力",
      "code": "300502",
      "name": "新易盛",
      "report_status": "batch_001新版草稿",
      "report_priority": "new_batch001",
      "batch": "batch_001",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 1,
      "concept_id": "ai_compute",
      "concept_name": "AI算力",
      "code": "600131",
      "name": "国网信通",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 1,
      "concept_id": "ai_compute",
      "concept_name": "AI算力",
      "code": "600446",
      "name": "金证股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 1,
      "concept_id": "ai_compute",
      "concept_name": "AI算力",
      "code": "600602",
      "name": "云赛智联",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 1,
      "concept_id": "ai_compute",
      "concept_name": "AI算力",
      "code": "601138",
      "name": "工业富联",
      "report_status": "batch_001新版草稿",
      "report_priority": "new_batch001",
      "batch": "batch_001",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 1,
      "concept_id": "ai_compute",
      "concept_name": "AI算力",
      "code": "601360",
      "name": "三六零",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 1,
      "concept_id": "ai_compute",
      "concept_name": "AI算力",
      "code": "603019",
      "name": "中科曙光",
      "report_status": "batch_001新版草稿",
      "report_priority": "new_batch001",
      "batch": "batch_001",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 1,
      "concept_id": "ai_compute",
      "concept_name": "AI算力",
      "code": "603171",
      "name": "税友股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 1,
      "concept_id": "ai_compute",
      "concept_name": "AI算力",
      "code": "603383",
      "name": "顶点软件",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 1,
      "concept_id": "ai_compute",
      "concept_name": "AI算力",
      "code": "603613",
      "name": "国联股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 1,
      "concept_id": "ai_compute",
      "concept_name": "AI算力",
      "code": "603776",
      "name": "永安行",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 1,
      "concept_id": "ai_compute",
      "concept_name": "AI算力",
      "code": "603927",
      "name": "中科软",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 1,
      "concept_id": "ai_compute",
      "concept_name": "AI算力",
      "code": "603688",
      "name": "石英股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 1,
      "concept_id": "ai_compute",
      "concept_name": "AI算力",
      "code": "688256",
      "name": "寒武纪",
      "report_status": "batch_001新版草稿",
      "report_priority": "new_batch001",
      "batch": "batch_001",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 1,
      "concept_id": "ai_compute",
      "concept_name": "AI算力",
      "code": "001389",
      "name": "广合科技",
      "report_status": "batch_001新版草稿",
      "report_priority": "new_batch001",
      "batch": "batch_001",
      "classification_reason": "广合科技当前主行业为AI算力，且PCB/高速PCB作为二级赛道，保留但需补主营与客户证据。"
    },
    {
      "concept_seq": 1,
      "concept_id": "ai_compute",
      "concept_name": "AI算力",
      "code": "600584",
      "name": "长电科技",
      "report_status": "batch_001新版草稿",
      "report_priority": "new_batch001",
      "batch": "batch_001",
      "classification_reason": "长电科技具备AI算力与先进封装交叉价值，保留在首批，但报告需明确封测环节。"
    },
    {
      "concept_seq": 1,
      "concept_id": "ai_compute",
      "concept_name": "AI算力",
      "code": "603328",
      "name": "依顿电子",
      "report_status": "batch_001新版草稿",
      "report_priority": "new_batch001",
      "batch": "batch_001",
      "classification_reason": "依顿电子当前映射为AI服务器链/PCB，保留候选但必须优先补V2证据。"
    },
    {
      "concept_seq": 2,
      "concept_id": "optical_module",
      "concept_name": "光模块/CPO",
      "code": "002281",
      "name": "光迅科技",
      "report_status": "batch_001新版草稿",
      "report_priority": "new_batch001",
      "batch": "batch_001",
      "classification_reason": "主营为光电子器件、模块和子系统，产品含传输、接入、数据通信类产品，和光模块/CPO主线匹配度高。"
    },
    {
      "concept_seq": 2,
      "concept_id": "optical_module",
      "concept_name": "光模块/CPO",
      "code": "002902",
      "name": "铭普光磁",
      "report_status": "batch_001新版草稿",
      "report_priority": "new_batch001",
      "batch": "batch_001",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 2,
      "concept_id": "optical_module",
      "concept_name": "光模块/CPO",
      "code": "300308",
      "name": "中际旭创",
      "report_status": "batch_001新版草稿",
      "report_priority": "new_batch001",
      "batch": "batch_001",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 2,
      "concept_id": "optical_module",
      "concept_name": "光模块/CPO",
      "code": "300502",
      "name": "新易盛",
      "report_status": "batch_001新版草稿",
      "report_priority": "new_batch001",
      "batch": "batch_001",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 3,
      "concept_id": "pcb_high_speed",
      "concept_name": "PCB/高速PCB",
      "code": "600183",
      "name": "生益科技",
      "report_status": "batch_001新版草稿",
      "report_priority": "new_batch001",
      "batch": "batch_001",
      "classification_reason": "主营为覆铜板、粘结片和印制线路板，是PCB上游材料与板材环节，适合以CCL/覆铜板子概念入池。"
    },
    {
      "concept_seq": 3,
      "concept_id": "pcb_high_speed",
      "concept_name": "PCB/高速PCB",
      "code": "002384",
      "name": "东山精密",
      "report_status": "batch_001新版草稿",
      "report_priority": "new_batch001",
      "batch": "batch_001",
      "classification_reason": "产品覆盖软板、硬板、软硬结合板，同时具备光模块与精密组件线索，适合进入PCB主线并保留光模块交叉标签。"
    },
    {
      "concept_seq": 3,
      "concept_id": "pcb_high_speed",
      "concept_name": "PCB/高速PCB",
      "code": "002916",
      "name": "深南电路",
      "report_status": "batch_001新版草稿",
      "report_priority": "new_batch001",
      "batch": "batch_001",
      "classification_reason": "主营为印制电路板、封装基板及电子装联，属于PCB和先进封装上游关键环节。"
    },
    {
      "concept_seq": 3,
      "concept_id": "pcb_high_speed",
      "concept_name": "PCB/高速PCB",
      "code": "001359",
      "name": "平安电工",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 3,
      "concept_id": "pcb_high_speed",
      "concept_name": "PCB/高速PCB",
      "code": "002141",
      "name": "贤丰控股",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 3,
      "concept_id": "pcb_high_speed",
      "concept_name": "PCB/高速PCB",
      "code": "002203",
      "name": "海亮股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 3,
      "concept_id": "pcb_high_speed",
      "concept_name": "PCB/高速PCB",
      "code": "600110",
      "name": "诺德股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 3,
      "concept_id": "pcb_high_speed",
      "concept_name": "PCB/高速PCB",
      "code": "600226",
      "name": "亨通股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 3,
      "concept_id": "pcb_high_speed",
      "concept_name": "PCB/高速PCB",
      "code": "605006",
      "name": "山东玻纤",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 3,
      "concept_id": "pcb_high_speed",
      "concept_name": "PCB/高速PCB",
      "code": "600601",
      "name": "方正科技",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 3,
      "concept_id": "pcb_high_speed",
      "concept_name": "PCB/高速PCB",
      "code": "001389",
      "name": "广合科技",
      "report_status": "batch_001新版草稿",
      "report_priority": "new_batch001",
      "batch": "batch_001",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 3,
      "concept_id": "pcb_high_speed",
      "concept_name": "PCB/高速PCB",
      "code": "002741",
      "name": "光华科技",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 3,
      "concept_id": "pcb_high_speed",
      "concept_name": "PCB/高速PCB",
      "code": "300576",
      "name": "容大感光",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 3,
      "concept_id": "pcb_high_speed",
      "concept_name": "PCB/高速PCB",
      "code": "600869",
      "name": "远东股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 3,
      "concept_id": "pcb_high_speed",
      "concept_name": "PCB/高速PCB",
      "code": "603328",
      "name": "依顿电子",
      "report_status": "batch_001新版草稿",
      "report_priority": "new_batch001",
      "batch": "batch_001",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 4,
      "concept_id": "semiconductor",
      "concept_name": "半导体",
      "code": "603650",
      "name": "彤程新材",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 4,
      "concept_id": "semiconductor",
      "concept_name": "半导体",
      "code": "300046",
      "name": "台基股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "台基股份旧路径映射至功率半导体，保留为半导体首批候选，但需要新版证据复核。"
    },
    {
      "concept_seq": 4,
      "concept_id": "semiconductor",
      "concept_name": "半导体",
      "code": "688041",
      "name": "海光信息",
      "report_status": "batch_001新版草稿",
      "report_priority": "new_batch001",
      "batch": "batch_001",
      "classification_reason": "海光信息为国产算力芯片核心公司，半导体与AI算力交叉，保留但主展示可放AI算力。"
    },
    {
      "concept_seq": 4,
      "concept_id": "semiconductor",
      "concept_name": "半导体",
      "code": "688256",
      "name": "寒武纪",
      "report_status": "batch_001新版草稿",
      "report_priority": "new_batch001",
      "batch": "batch_001",
      "classification_reason": "寒武纪为AI芯片公司，半导体与AI算力交叉，保留但主展示可放AI算力。"
    },
    {
      "concept_seq": 4,
      "concept_id": "semiconductor",
      "concept_name": "半导体",
      "code": "002156",
      "name": "通富微电",
      "report_status": "batch_001新版草稿",
      "report_priority": "new_batch001",
      "batch": "batch_001",
      "classification_reason": "通富微电主行业为半导体且核心概念为封装测试/先进封装，保留首批。"
    },
    {
      "concept_seq": 4,
      "concept_id": "semiconductor",
      "concept_name": "半导体",
      "code": "002185",
      "name": "华天科技",
      "report_status": "已有新版",
      "report_priority": "v2_existing",
      "batch": "",
      "classification_reason": "华天科技主行业为半导体且核心概念为封装测试/先进封装，保留首批。"
    },
    {
      "concept_seq": 4,
      "concept_id": "semiconductor",
      "concept_name": "半导体",
      "code": "600353",
      "name": "旭光电子",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "旭光电子旧路径映射到功率/军工电子器件，保留候选但需新版证据复核。"
    },
    {
      "concept_seq": 4,
      "concept_id": "semiconductor",
      "concept_name": "半导体",
      "code": "600563",
      "name": "法拉电子",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "法拉电子被映射为半导体/功率方向，但需确认其更适合功率器件还是被动元器件。"
    },
    {
      "concept_seq": 4,
      "concept_id": "semiconductor",
      "concept_name": "半导体",
      "code": "600584",
      "name": "长电科技",
      "report_status": "batch_001新版草稿",
      "report_priority": "new_batch001",
      "batch": "batch_001",
      "classification_reason": "长电科技为封装测试核心公司，保留半导体首批并同步放入先进封装。"
    },
    {
      "concept_seq": 4,
      "concept_id": "semiconductor",
      "concept_name": "半导体",
      "code": "603501",
      "name": "韦尔股份",
      "report_status": "已有新版",
      "report_priority": "v2_existing",
      "batch": "",
      "classification_reason": "韦尔股份主行业为半导体，保留首批，需补传感器/模拟芯片证据。"
    },
    {
      "concept_seq": 5,
      "concept_id": "advanced_packaging",
      "concept_name": "封装测试/先进封装",
      "code": "002156",
      "name": "通富微电",
      "report_status": "batch_001新版草稿",
      "report_priority": "new_batch001",
      "batch": "batch_001",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 5,
      "concept_id": "advanced_packaging",
      "concept_name": "封装测试/先进封装",
      "code": "002185",
      "name": "华天科技",
      "report_status": "已有新版",
      "report_priority": "v2_existing",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 5,
      "concept_id": "advanced_packaging",
      "concept_name": "封装测试/先进封装",
      "code": "600584",
      "name": "长电科技",
      "report_status": "batch_001新版草稿",
      "report_priority": "new_batch001",
      "batch": "batch_001",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 5,
      "concept_id": "advanced_packaging",
      "concept_name": "封装测试/先进封装",
      "code": "603005",
      "name": "晶方科技",
      "report_status": "已有新版",
      "report_priority": "v2_existing",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 6,
      "concept_id": "passive_components",
      "concept_name": "电子元器件/被动元器件",
      "code": "600888",
      "name": "新疆众和",
      "report_status": "batch_001新版草稿",
      "report_priority": "new_batch001",
      "batch": "batch_001",
      "classification_reason": "主营与产品包含电子铝箔、电极箔、高纯铝，对应铝电解电容材料链，适合作为被动元器件上游材料候选。"
    },
    {
      "concept_seq": 6,
      "concept_id": "passive_components",
      "concept_name": "电子元器件/被动元器件",
      "code": "000636",
      "name": "风华高科",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 6,
      "concept_id": "passive_components",
      "concept_name": "电子元器件/被动元器件",
      "code": "002138",
      "name": "顺络电子",
      "report_status": "已有新版",
      "report_priority": "v2_existing",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 6,
      "concept_id": "passive_components",
      "concept_name": "电子元器件/被动元器件",
      "code": "002484",
      "name": "江海股份",
      "report_status": "batch_001新版草稿",
      "report_priority": "new_batch001",
      "batch": "batch_001",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 6,
      "concept_id": "passive_components",
      "concept_name": "电子元器件/被动元器件",
      "code": "603989",
      "name": "艾华集团",
      "report_status": "batch_001新版草稿",
      "report_priority": "new_batch001",
      "batch": "batch_001",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "601869",
      "name": "长飞光纤",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "000021",
      "name": "深科技",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "000066",
      "name": "中国长城",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "000070",
      "name": "特发信息",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "000536",
      "name": "华映科技",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "000547",
      "name": "航天发展",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "000561",
      "name": "烽火电子",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "001285",
      "name": "瑞立科密",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "001314",
      "name": "亿道信息",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "001339",
      "name": "智微智能",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "002017",
      "name": "东信和平",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "002025",
      "name": "航天电器",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "002049",
      "name": "紫光国微",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "002077",
      "name": "大港股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "002079",
      "name": "苏州固锝",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "002134",
      "name": "天津普林",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "002151",
      "name": "北斗星通",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "002152",
      "name": "广电运通",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "002189",
      "name": "中光学",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "002222",
      "name": "福晶科技",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "002273",
      "name": "水晶光电",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "002383",
      "name": "合众思壮",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "002387",
      "name": "维信诺",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "002402",
      "name": "和而泰",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "002413",
      "name": "雷科防务",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "002446",
      "name": "盛路通信",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "002519",
      "name": "银河电子",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "002552",
      "name": "宝鼎科技",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "002635",
      "name": "安洁科技",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "002636",
      "name": "金安国纪",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "002805",
      "name": "丰元股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "002841",
      "name": "视源股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "002859",
      "name": "洁美科技",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "002876",
      "name": "三利谱",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "002881",
      "name": "美格智能",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "002885",
      "name": "京泉华",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "002906",
      "name": "华阳集团",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "002925",
      "name": "盈趣科技",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "002935",
      "name": "天奥电子",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "002947",
      "name": "恒铭达",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "002992",
      "name": "宝明科技",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "003026",
      "name": "中晶科技",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "003031",
      "name": "中瓷电子",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "600037",
      "name": "歌华有线",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "600060",
      "name": "海信视像",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "600198",
      "name": "大唐电信",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "600203",
      "name": "福日电子",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "600288",
      "name": "大恒科技",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "600345",
      "name": "长江通信",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "600435",
      "name": "北方导航",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "600487",
      "name": "亨通光电",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "600562",
      "name": "国睿科技",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "600775",
      "name": "南京熊猫",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "600776",
      "name": "东方通信",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "600884",
      "name": "杉杉股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "600936",
      "name": "北投科技",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "600996",
      "name": "贵广网络",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "601231",
      "name": "环旭电子",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "603025",
      "name": "大豪科技",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "603042",
      "name": "华脉科技",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "603068",
      "name": "博通集成",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "603072",
      "name": "天和磁材",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "603083",
      "name": "剑桥科技",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "603115",
      "name": "海星股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "603118",
      "name": "共进股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "603124",
      "name": "江南新材",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "603186",
      "name": "华正新材",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "603293",
      "name": "埃泰克",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "603327",
      "name": "福蓉科技",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "603459",
      "name": "红板科技",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "603496",
      "name": "恒为科技",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "603516",
      "name": "淳中科技",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "603803",
      "name": "瑞斯康达",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "603890",
      "name": "春秋电子",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "603893",
      "name": "瑞芯微",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "603933",
      "name": "睿能科技",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "605118",
      "name": "力鼎光电",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "605358",
      "name": "立昂微",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 7,
      "concept_id": "comm_optical_infra",
      "concept_name": "光通信基础设施",
      "code": "605376",
      "name": "博迁新材",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "000338",
      "name": "潍柴动力",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "000581",
      "name": "威孚高科",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "000700",
      "name": "模塑科技",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "000800",
      "name": "一汽解放",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "000901",
      "name": "航天科技",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "000951",
      "name": "中国重汽",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "000957",
      "name": "中通客车",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "000980",
      "name": "众泰汽车",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "000981",
      "name": "山子高科",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "002048",
      "name": "宁波华翔",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "002125",
      "name": "湘潭电化",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "002126",
      "name": "银轮股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "002167",
      "name": "东方锆业",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "002283",
      "name": "天润工业",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "002284",
      "name": "亚太股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "002328",
      "name": "新朋股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "002406",
      "name": "远东传动",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "002448",
      "name": "中原内配",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "002488",
      "name": "金固股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "002537",
      "name": "海联金汇",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "002664",
      "name": "信质集团",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "002708",
      "name": "光洋股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "002733",
      "name": "雄韬股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "002824",
      "name": "和胜股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "600006",
      "name": "东风股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "600081",
      "name": "东风科技",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "600148",
      "name": "长春一东",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "600375",
      "name": "汉马科技",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "600686",
      "name": "金龙汽车",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "600698",
      "name": "湖南天雁",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "600733",
      "name": "北汽蓝谷",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "601279",
      "name": "英利汽车",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "601799",
      "name": "星宇股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "603009",
      "name": "北特科技",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "603013",
      "name": "亚普股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "603158",
      "name": "腾龙股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "603166",
      "name": "福达股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "603286",
      "name": "日盈电子",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "603305",
      "name": "旭升集团",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "603409",
      "name": "汇通控股",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "603418",
      "name": "友升股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "603596",
      "name": "伯特利",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "603950",
      "name": "长源东谷",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "603997",
      "name": "继峰股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "605128",
      "name": "上海沿浦",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "605133",
      "name": "嵘泰股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "605228",
      "name": "神通科技",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "605319",
      "name": "无锡振华",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "002050",
      "name": "三花智控",
      "report_status": "已有新版",
      "report_priority": "v2_existing",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "002074",
      "name": "国轩高科",
      "report_status": "暂未生成",
      "report_priority": "none",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "002460",
      "name": "赣锋锂业",
      "report_status": "已有新版",
      "report_priority": "v2_existing",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "002594",
      "name": "比亚迪",
      "report_status": "已有新版",
      "report_priority": "v2_existing",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "300014",
      "name": "亿纬锂能",
      "report_status": "暂未生成",
      "report_priority": "none",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "300207",
      "name": "欣旺达",
      "report_status": "暂未生成",
      "report_priority": "none",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "300274",
      "name": "阳光电源",
      "report_status": "已有新版",
      "report_priority": "v2_existing",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "300750",
      "name": "宁德时代",
      "report_status": "已有新版",
      "report_priority": "v2_existing",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 8,
      "concept_id": "battery_storage",
      "concept_name": "动力电池/储能",
      "code": "601678",
      "name": "滨化股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "000037",
      "name": "深南电A",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "000049",
      "name": "德赛电池",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "000155",
      "name": "川能动力",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "000531",
      "name": "穗恒运A",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "000600",
      "name": "建投能源",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "000722",
      "name": "湖南发展",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "001208",
      "name": "华菱线缆",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "001258",
      "name": "立新能源",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "001259",
      "name": "利仁科技",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "002015",
      "name": "协鑫能科",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "002026",
      "name": "山东威达",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "002053",
      "name": "云南能投",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "002112",
      "name": "三变科技",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "002129",
      "name": "TCL中环",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "002169",
      "name": "智光电气",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "002196",
      "name": "方正电机",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "002218",
      "name": "拓日新能",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "002249",
      "name": "大洋电机",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "002256",
      "name": "兆新股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "002309",
      "name": "中利集团",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "002335",
      "name": "科华数据",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "002358",
      "name": "森源电气",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "002364",
      "name": "中恒电气",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "002459",
      "name": "晶澳科技",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "002471",
      "name": "中超控股",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "002498",
      "name": "汉缆股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "002506",
      "name": "协鑫集成",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "002518",
      "name": "科士达",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "002580",
      "name": "圣阳股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "002606",
      "name": "大连电瓷",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "002668",
      "name": "TCL智家",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "002745",
      "name": "木林森",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "002801",
      "name": "微光股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "002823",
      "name": "凯中精密",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "002922",
      "name": "伊戈尔",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "600098",
      "name": "广州发展",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "600116",
      "name": "三峡水利",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "600268",
      "name": "国电南自",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "600310",
      "name": "广西能源",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "600312",
      "name": "平高电气",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "600396",
      "name": "华电辽能",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "600452",
      "name": "涪陵电力",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "600478",
      "name": "科力远",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "600509",
      "name": "天富能源",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "600550",
      "name": "保变电气",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "600580",
      "name": "卧龙电驱",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "600868",
      "name": "梅雁吉祥",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "600885",
      "name": "宏发股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "600973",
      "name": "宝胜股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "600979",
      "name": "广安爱众",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "600982",
      "name": "宁波能源",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "600995",
      "name": "南网储能",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "601126",
      "name": "四方股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "601179",
      "name": "中国西电",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "601877",
      "name": "正泰电器",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "601991",
      "name": "大唐发电",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "603031",
      "name": "安孚科技",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "603075",
      "name": "热威股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "603195",
      "name": "公牛集团",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "603366",
      "name": "日出东方",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "603489",
      "name": "八方股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "603507",
      "name": "振江股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "603530",
      "name": "神马电力",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "603606",
      "name": "东方电缆",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "603618",
      "name": "杭电股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "603685",
      "name": "晨丰科技",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "603701",
      "name": "德宏股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "603778",
      "name": "国晟科技",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "605011",
      "name": "杭州热电",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "605196",
      "name": "华通线缆",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "000400",
      "name": "许继电气",
      "report_status": "暂未生成",
      "report_priority": "none",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "002028",
      "name": "思源电气",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "002035",
      "name": "华帝股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "002184",
      "name": "海得控制",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "002451",
      "name": "摩恩电气",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "600089",
      "name": "特变电工",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "603333",
      "name": "福华尚纬",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "603819",
      "name": "神力股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "603988",
      "name": "中电电机",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    },
    {
      "concept_seq": 9,
      "concept_id": "power_grid_uhv",
      "concept_name": "电网设备 / 特高压",
      "code": "605117",
      "name": "德业股份",
      "report_status": "旧版兜底",
      "report_priority": "legacy_fallback",
      "batch": "",
      "classification_reason": "进入完整 V2 第一批；补主营/财务/上下游证据。"
    }
  ]
};
