const EXPANSION_BATCH_DASHBOARD_V1 = {
  "generated_at": "2026-06-27 14:04:50",
  "purpose": "扩容运营面板：先扩分类与证据底座，再决定是否生成深度报告。",
  "current": {
    "integrated_stock_count": 210,
    "taxonomy_node_count": 111,
    "evidence_card_count": 210,
    "evidence_high_purity_count": 149,
    "empty_leaf_node_count": 13
  },
  "queue_summary": {
    "unique_candidate_count": 160,
    "phase_counts": {
      "已完成": 127,
      "后续扩容": 33
    },
    "status_counts": {
      "已接入分类树": 127,
      "P0待复查": 1,
      "后续种子池": 32
    },
    "priority_counts": {
      "P0": 81,
      "P1": 47,
      "P2": 32
    },
    "pending_bucket_counts": {
      "电力与公用事业": 1,
      "AI视觉": 2,
      "动力电池/储能": 2,
      "半导体": 2,
      "半导体设备": 3,
      "国防军工与航空航天": 2,
      "工业软件": 1,
      "新能源发电": 1,
      "机器人/自动化": 5,
      "消费白马": 3,
      "资源周期": 5,
      "金融": 3,
      "锂电材料": 3
    },
    "next_round_count": 0,
    "next_p1_count": 0,
    "later_seed_count": 33,
    "projected_after_next_round": 210,
    "projected_after_seed_pool": 243
  },
  "recommended_next_actions": [
    "以当前 210 家为底座，先筛出尚未接入的后续种子池。",
    "下一批只做轻量证据卡和分类挂载，不生成深度报告。",
    "接入后重新跑质量诊断，优先处理跨主线过载和财务弱证据。",
    "到 300-500 家阶段时，按行业缺口、热点主线和细分材料链补样本，不平均铺开。"
  ],
  "empty_leaf_nodes": [
    {
      "id": "renewable_wind",
      "name": "风电",
      "path": "电力与公用事业 / 风电"
    },
    {
      "id": "renewable_storage_grid",
      "name": "储能并网",
      "path": "电力与公用事业 / 储能并网"
    },
    {
      "id": "power_grid_uhv",
      "name": "电网设备 / 特高压",
      "path": "电力与公用事业 / 电网设备 / 特高压"
    },
    {
      "id": "power_integrated_service",
      "name": "综合能源服务",
      "path": "电力与公用事业 / 综合能源服务"
    },
    {
      "id": "comm_optical_infra",
      "name": "光通信基础设施",
      "path": "通信设备与运营商 / 光通信基础设施"
    },
    {
      "id": "comm_operator_idc",
      "name": "运营商 / IDC",
      "path": "通信设备与运营商 / 运营商 / IDC"
    },
    {
      "id": "comm_equipment",
      "name": "通信设备",
      "path": "通信设备与运营商 / 通信设备"
    },
    {
      "id": "advanced_electronic_material",
      "name": "电子材料",
      "path": "有色金属与新材料 / 电子材料"
    },
    {
      "id": "chemical_fiber_polymer",
      "name": "化纤 / 高分子",
      "path": "化工材料 / 化纤 / 高分子"
    },
    {
      "id": "resources_precious_metal",
      "name": "黄金 / 贵金属",
      "path": "资源周期 / 黄金 / 贵金属"
    },
    {
      "id": "defense_prime",
      "name": "军工主机",
      "path": "国防军工与航空航天 / 军工主机"
    },
    {
      "id": "defense_commercial_space",
      "name": "商业航天 / 卫星互联网",
      "path": "国防军工与航空航天 / 商业航天 / 卫星互联网"
    },
    {
      "id": "consumer_dividend",
      "name": "高股息消费",
      "path": "消费白马 / 高股息消费"
    }
  ],
  "queue": [
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "001389",
      "name": "广合科技",
      "bucket": "AI算力",
      "subcategory": "PCB / 高速PCB",
      "old_report_status": "可复用旧报告",
      "reason": "PCB补充样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "603328",
      "name": "依顿电子",
      "bucket": "AI算力",
      "subcategory": "PCB / 高速PCB",
      "old_report_status": "可复用旧报告",
      "reason": "PCB补充样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "000089",
      "name": "深圳机场",
      "bucket": "交运物流",
      "subcategory": "机场",
      "old_report_status": "可复用旧报告",
      "reason": "机场样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "000582",
      "name": "北部湾港",
      "bucket": "交运物流",
      "subcategory": "港口",
      "old_report_status": "可复用旧报告",
      "reason": "区域港口样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "000905",
      "name": "厦门港务",
      "bucket": "交运物流",
      "subcategory": "港口",
      "old_report_status": "可复用旧报告",
      "reason": "港口物流样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "002040",
      "name": "南京港",
      "bucket": "交运物流",
      "subcategory": "港口",
      "old_report_status": "可复用旧报告",
      "reason": "港口样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "002928",
      "name": "华夏航空",
      "bucket": "交运物流",
      "subcategory": "航空",
      "old_report_status": "可复用旧报告",
      "reason": "航空公司样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "600009",
      "name": "上海机场",
      "bucket": "交运物流",
      "subcategory": "机场",
      "old_report_status": "可复用旧报告",
      "reason": "机场代表样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "600029",
      "name": "南方航空",
      "bucket": "交运物流",
      "subcategory": "航空",
      "old_report_status": "可复用旧报告",
      "reason": "航空公司样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "600377",
      "name": "宁沪高速",
      "bucket": "交运物流",
      "subcategory": "高速公路",
      "old_report_status": "可复用旧报告",
      "reason": "高速公路高股息样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "600548",
      "name": "深高速",
      "bucket": "交运物流",
      "subcategory": "高速公路",
      "old_report_status": "可复用旧报告",
      "reason": "高速公路样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "600717",
      "name": "天津港",
      "bucket": "交运物流",
      "subcategory": "港口",
      "old_report_status": "可复用旧报告",
      "reason": "港口样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "601000",
      "name": "唐山港",
      "bucket": "交运物流",
      "subcategory": "港口",
      "old_report_status": "可复用旧报告",
      "reason": "大宗港口样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "601018",
      "name": "宁波港",
      "bucket": "交运物流",
      "subcategory": "港口",
      "old_report_status": "可复用旧报告",
      "reason": "大型港口样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "601021",
      "name": "春秋航空",
      "bucket": "交运物流",
      "subcategory": "航空",
      "old_report_status": "可复用旧报告",
      "reason": "低成本航空样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "601156",
      "name": "东航物流",
      "bucket": "交运物流",
      "subcategory": "航空物流",
      "old_report_status": "可复用旧报告",
      "reason": "航空物流样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "601333",
      "name": "广深铁路",
      "bucket": "交运物流",
      "subcategory": "铁路",
      "old_report_status": "可复用旧报告",
      "reason": "铁路运输样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "603885",
      "name": "吉祥航空",
      "bucket": "交运物流",
      "subcategory": "航空",
      "old_report_status": "可复用旧报告",
      "reason": "民营航空样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "002607",
      "name": "中公教育",
      "bucket": "传媒互联网",
      "subcategory": "教育 / 人力服务",
      "old_report_status": "可复用旧报告",
      "reason": "教育服务样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "601929",
      "name": "吉视传媒",
      "bucket": "传媒互联网",
      "subcategory": "广电 / 内容平台",
      "old_report_status": "可复用旧报告",
      "reason": "传媒主分类可复用样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "605098",
      "name": "行动教育",
      "bucket": "传媒互联网",
      "subcategory": "教育 / 人力服务",
      "old_report_status": "可复用旧报告",
      "reason": "企业培训样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "001313",
      "name": "粤海饲料",
      "bucket": "农业养殖",
      "subcategory": "饲料 / 水产饲料",
      "old_report_status": "可复用旧报告",
      "reason": "饲料样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "002041",
      "name": "登海种业",
      "bucket": "农业养殖",
      "subcategory": "种业 / 种植",
      "old_report_status": "可复用旧报告",
      "reason": "种业样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "002250",
      "name": "联化科技",
      "bucket": "化工材料",
      "subcategory": "农化 / 化肥农药",
      "old_report_status": "可复用旧报告",
      "reason": "农药和精细化工样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "002326",
      "name": "永太科技",
      "bucket": "化工材料",
      "subcategory": "氟化工 / 电子化学品",
      "old_report_status": "可复用旧报告",
      "reason": "氟化工和医药中间体样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "002409",
      "name": "雅克科技",
      "bucket": "半导体",
      "subcategory": "半导体材料",
      "old_report_status": "可复用旧报告",
      "reason": "电子特气和材料样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "600563",
      "name": "法拉电子",
      "bucket": "半导体",
      "subcategory": "模拟 / 功率 / MCU",
      "old_report_status": "可复用旧报告",
      "reason": "薄膜电容和功率电子样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "601208",
      "name": "东材科技",
      "bucket": "半导体",
      "subcategory": "半导体材料",
      "old_report_status": "可复用旧报告",
      "reason": "电子材料样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "603005",
      "name": "晶方科技",
      "bucket": "半导体",
      "subcategory": "封测 / 设备零部件",
      "old_report_status": "可复用旧报告",
      "reason": "封测细分样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "600415",
      "name": "小商品城",
      "bucket": "商贸零售 / 社服",
      "subcategory": "商品市场 / 零售",
      "old_report_status": "可复用旧报告",
      "reason": "商品市场和跨境贸易样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "600754",
      "name": "锦江酒店",
      "bucket": "商贸零售 / 社服",
      "subcategory": "酒店",
      "old_report_status": "可复用旧报告",
      "reason": "酒店代表样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "601888",
      "name": "中国中免",
      "bucket": "商贸零售 / 社服",
      "subcategory": "免税 / 旅游零售",
      "old_report_status": "可复用旧报告",
      "reason": "免税代表样本",
      "status": "已接入分类树",
      "phase": "已完成",
      "extra_sources": [
        "第三批扩容候选池"
      ]
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "000002",
      "name": "万科A",
      "bucket": "地产 / 建筑建材",
      "subcategory": "房地产开发",
      "old_report_status": "可复用旧报告",
      "reason": "地产开发样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "001322",
      "name": "箭牌家居",
      "bucket": "地产 / 建筑建材",
      "subcategory": "建材 / 家居材料",
      "old_report_status": "可复用旧报告",
      "reason": "家居建材样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "600170",
      "name": "上海建工",
      "bucket": "地产 / 建筑建材",
      "subcategory": "建筑工程 / 基建",
      "old_report_status": "可复用旧报告",
      "reason": "建筑工程样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "600449",
      "name": "宁夏建材",
      "bucket": "地产 / 建筑建材",
      "subcategory": "建材 / 水泥玻璃",
      "old_report_status": "可复用旧报告",
      "reason": "水泥建材样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "600463",
      "name": "空港股份",
      "bucket": "地产 / 建筑建材",
      "subcategory": "园区 / 物业运营",
      "old_report_status": "可复用旧报告",
      "reason": "园区和地产运营样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "600502",
      "name": "安徽建工",
      "bucket": "地产 / 建筑建材",
      "subcategory": "建筑工程 / 基建",
      "old_report_status": "可复用旧报告",
      "reason": "基建工程样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "601789",
      "name": "宁波建工",
      "bucket": "地产 / 建筑建材",
      "subcategory": "建筑工程 / 基建",
      "old_report_status": "可复用旧报告",
      "reason": "地方建筑工程样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "000550",
      "name": "江铃汽车",
      "bucket": "新能源汽车",
      "subcategory": "整车 / 商用车",
      "old_report_status": "可复用旧报告",
      "reason": "整车样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "002590",
      "name": "万安科技",
      "bucket": "新能源汽车",
      "subcategory": "汽车零部件",
      "old_report_status": "可复用旧报告",
      "reason": "线控制动和汽车零部件样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "600166",
      "name": "福田汽车",
      "bucket": "新能源汽车",
      "subcategory": "整车 / 商用车",
      "old_report_status": "可复用旧报告",
      "reason": "商用车样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "600699",
      "name": "均胜电子",
      "bucket": "新能源汽车",
      "subcategory": "汽车零部件",
      "old_report_status": "可复用旧报告",
      "reason": "汽车电子样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "000885",
      "name": "城发环境",
      "bucket": "环保 / 水务固废",
      "subcategory": "环保综合",
      "old_report_status": "可复用旧报告",
      "reason": "环保运营样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "000967",
      "name": "盈峰环境",
      "bucket": "环保 / 水务固废",
      "subcategory": "环卫装备 / 环境服务",
      "old_report_status": "可复用旧报告",
      "reason": "环卫装备样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "002034",
      "name": "旺能环境",
      "bucket": "环保 / 水务固废",
      "subcategory": "固废 / 垃圾焚烧",
      "old_report_status": "可复用旧报告",
      "reason": "垃圾焚烧样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "002340",
      "name": "格林美",
      "bucket": "环保 / 水务固废",
      "subcategory": "固废 / 再生资源",
      "old_report_status": "可复用旧报告",
      "reason": "再生资源和电池回收样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "600323",
      "name": "瀚蓝环境",
      "bucket": "环保 / 水务固废",
      "subcategory": "水务 / 固废",
      "old_report_status": "可复用旧报告",
      "reason": "水务固废综合样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "600388",
      "name": "龙净环保",
      "bucket": "环保 / 水务固废",
      "subcategory": "大气治理",
      "old_report_status": "可复用旧报告",
      "reason": "大气治理样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "600874",
      "name": "创业环保",
      "bucket": "环保 / 水务固废",
      "subcategory": "水务 / 污水处理",
      "old_report_status": "可复用旧报告",
      "reason": "水务污水处理样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "601200",
      "name": "上海环境",
      "bucket": "环保 / 水务固废",
      "subcategory": "环保综合",
      "old_report_status": "可复用旧报告",
      "reason": "环保综合样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "601827",
      "name": "三峰环境",
      "bucket": "环保 / 水务固废",
      "subcategory": "固废 / 垃圾焚烧",
      "old_report_status": "可复用旧报告",
      "reason": "固废处理样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "000027",
      "name": "深圳能源",
      "bucket": "电力与公用事业",
      "subcategory": "综合电力",
      "old_report_status": "可复用旧报告",
      "reason": "综合电力样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "000400",
      "name": "许继电气",
      "bucket": "电力与公用事业",
      "subcategory": "电网设备 / 特高压",
      "old_report_status": "需新增报告",
      "reason": "电网设备代表样本",
      "status": "P0待复查",
      "phase": "后续扩容"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "000539",
      "name": "粤电力A",
      "bucket": "电力与公用事业",
      "subcategory": "火电 / 绿电运营",
      "old_report_status": "可复用旧报告",
      "reason": "火电和绿电运营样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "000690",
      "name": "宝新能源",
      "bucket": "电力与公用事业",
      "subcategory": "新能源发电",
      "old_report_status": "可复用旧报告",
      "reason": "新能源电力样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "000767",
      "name": "晋控电力",
      "bucket": "电力与公用事业",
      "subcategory": "火电 / 煤电",
      "old_report_status": "可复用旧报告",
      "reason": "火电样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "000791",
      "name": "甘肃能源",
      "bucket": "电力与公用事业",
      "subcategory": "综合电力",
      "old_report_status": "可复用旧报告",
      "reason": "区域电力样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "000883",
      "name": "湖北能源",
      "bucket": "电力与公用事业",
      "subcategory": "综合电力",
      "old_report_status": "可复用旧报告",
      "reason": "水火风光综合能源样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "600236",
      "name": "桂冠电力",
      "bucket": "电力与公用事业",
      "subcategory": "水电",
      "old_report_status": "可复用旧报告",
      "reason": "水电样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "600578",
      "name": "京能电力",
      "bucket": "电力与公用事业",
      "subcategory": "火电 / 煤电",
      "old_report_status": "可复用旧报告",
      "reason": "火电样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "600726",
      "name": "华电能源",
      "bucket": "电力与公用事业",
      "subcategory": "火电 / 煤电",
      "old_report_status": "可复用旧报告",
      "reason": "火电样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "600744",
      "name": "华银电力",
      "bucket": "电力与公用事业",
      "subcategory": "火电 / 煤电",
      "old_report_status": "可复用旧报告",
      "reason": "火电样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "002067",
      "name": "景兴纸业",
      "bucket": "纺服轻工",
      "subcategory": "造纸 / 印刷",
      "old_report_status": "可复用旧报告",
      "reason": "包装纸样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "002078",
      "name": "太阳纸业",
      "bucket": "纺服轻工",
      "subcategory": "造纸 / 印刷",
      "old_report_status": "可复用旧报告",
      "reason": "造纸行业代表样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "002831",
      "name": "裕同科技",
      "bucket": "纺服轻工",
      "subcategory": "包装",
      "old_report_status": "可复用旧报告",
      "reason": "精品包装样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "002969",
      "name": "嘉美包装",
      "bucket": "纺服轻工",
      "subcategory": "包装",
      "old_report_status": "可复用旧报告",
      "reason": "金属包装样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "600966",
      "name": "博汇纸业",
      "bucket": "纺服轻工",
      "subcategory": "造纸 / 印刷",
      "old_report_status": "可复用旧报告",
      "reason": "造纸样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "000977",
      "name": "浪潮信息",
      "bucket": "计算机 / 软件服务",
      "subcategory": "IT基础设施 / 云计算",
      "old_report_status": "可复用旧报告",
      "reason": "服务器和云基础设施样本",
      "status": "已接入分类树",
      "phase": "已完成",
      "extra_sources": [
        "第三批扩容候选池"
      ]
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "002065",
      "name": "东华软件",
      "bucket": "计算机 / 软件服务",
      "subcategory": "行业软件 / 应用软件",
      "old_report_status": "可复用旧报告",
      "reason": "补齐计算机主分类和行业软件样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "002153",
      "name": "石基信息",
      "bucket": "计算机 / 软件服务",
      "subcategory": "IT服务 / 酒店信息化",
      "old_report_status": "可复用旧报告",
      "reason": "垂直行业IT样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "002232",
      "name": "启明信息",
      "bucket": "计算机 / 软件服务",
      "subcategory": "汽车IT / 车联网",
      "old_report_status": "可复用旧报告",
      "reason": "汽车软件交叉样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "002279",
      "name": "久其软件",
      "bucket": "计算机 / 软件服务",
      "subcategory": "行业软件 / 应用软件",
      "old_report_status": "可复用旧报告",
      "reason": "财政和政务软件样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "600271",
      "name": "航天信息",
      "bucket": "计算机 / 软件服务",
      "subcategory": "信创 / 电子政务",
      "old_report_status": "可复用旧报告",
      "reason": "信创和电子政务样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "600570",
      "name": "恒生电子",
      "bucket": "计算机 / 软件服务",
      "subcategory": "金融IT / 行业软件",
      "old_report_status": "可复用旧报告",
      "reason": "金融IT核心样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "600588",
      "name": "用友网络",
      "bucket": "计算机 / 软件服务",
      "subcategory": "行业软件 / 应用软件",
      "old_report_status": "可复用旧报告",
      "reason": "企业软件代表公司",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "603039",
      "name": "泛微网络",
      "bucket": "计算机 / 软件服务",
      "subcategory": "行业软件 / 应用软件",
      "old_report_status": "可复用旧报告",
      "reason": "协同办公软件样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "603881",
      "name": "数据港",
      "bucket": "计算机 / 软件服务",
      "subcategory": "IDC / 数据中心",
      "old_report_status": "可复用旧报告",
      "reason": "IDC基础设施样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "000708",
      "name": "中信特钢",
      "bucket": "资源周期",
      "subcategory": "钢铁 / 建材",
      "old_report_status": "可复用旧报告",
      "reason": "特钢样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "600392",
      "name": "盛和资源",
      "bucket": "资源周期",
      "subcategory": "有色 / 稀土资源",
      "old_report_status": "可复用旧报告",
      "reason": "稀土资源样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P0",
      "code": "600072",
      "name": "中船科技",
      "bucket": "高端装备与工业",
      "subcategory": "轨交 / 船舶 / 海工装备",
      "old_report_status": "可复用旧报告",
      "reason": "船舶和海工装备样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P1",
      "code": "000938",
      "name": "紫光股份",
      "bucket": "AI算力",
      "subcategory": "AI算力",
      "old_report_status": "有旧报告",
      "reason": "ICT设备与云网基础设施样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P1",
      "code": "002463",
      "name": "沪电股份",
      "bucket": "AI算力",
      "subcategory": "PCB / 高速PCB",
      "old_report_status": "需新增报告",
      "reason": "高速PCB核心样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P1",
      "code": "603019",
      "name": "中科曙光",
      "bucket": "AI算力",
      "subcategory": "AI算力",
      "old_report_status": "有旧报告",
      "reason": "国产算力整机与高性能计算样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P1",
      "code": "002352",
      "name": "顺丰控股",
      "bucket": "交运物流",
      "subcategory": "快递 / 物流",
      "old_report_status": "需新增报告",
      "reason": "快递物流代表公司",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P1",
      "code": "601919",
      "name": "中远海控",
      "bucket": "交运物流",
      "subcategory": "航运",
      "old_report_status": "需新增报告",
      "reason": "集运航运代表公司",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P1",
      "code": "002027",
      "name": "分众传媒",
      "bucket": "传媒互联网",
      "subcategory": "广告营销",
      "old_report_status": "需新增报告",
      "reason": "广告营销代表公司",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P1",
      "code": "002555",
      "name": "三七互娱",
      "bucket": "传媒互联网",
      "subcategory": "游戏 / 内容",
      "old_report_status": "需新增报告",
      "reason": "游戏行业代表公司",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P1",
      "code": "002624",
      "name": "完美世界",
      "bucket": "传媒互联网",
      "subcategory": "游戏 / 内容",
      "old_report_status": "需新增报告",
      "reason": "游戏和影视内容代表公司",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P1",
      "code": "300251",
      "name": "光线传媒",
      "bucket": "传媒互联网",
      "subcategory": "影视内容",
      "old_report_status": "需新增报告",
      "reason": "影视内容样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P1",
      "code": "300413",
      "name": "芒果超媒",
      "bucket": "传媒互联网",
      "subcategory": "内容平台",
      "old_report_status": "需新增报告",
      "reason": "长视频和内容平台样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P1",
      "code": "000876",
      "name": "新希望",
      "bucket": "农业养殖",
      "subcategory": "饲料 / 养殖",
      "old_report_status": "需新增报告",
      "reason": "饲料和养殖综合样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P1",
      "code": "000998",
      "name": "隆平高科",
      "bucket": "农业养殖",
      "subcategory": "种业 / 种植",
      "old_report_status": "需新增报告",
      "reason": "种业代表样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P1",
      "code": "002311",
      "name": "海大集团",
      "bucket": "农业养殖",
      "subcategory": "饲料 / 水产饲料",
      "old_report_status": "需新增报告",
      "reason": "饲料龙头样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P1",
      "code": "002714",
      "name": "牧原股份",
      "bucket": "农业养殖",
      "subcategory": "猪禽水产养殖",
      "old_report_status": "需新增报告",
      "reason": "生猪养殖代表公司",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P1",
      "code": "300498",
      "name": "温氏股份",
      "bucket": "农业养殖",
      "subcategory": "猪禽水产养殖",
      "old_report_status": "需新增报告",
      "reason": "养殖综合样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P1",
      "code": "600598",
      "name": "北大荒",
      "bucket": "农业养殖",
      "subcategory": "种业 / 种植",
      "old_report_status": "需新增报告",
      "reason": "种植和土地资源样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P1",
      "code": "300014",
      "name": "亿纬锂能",
      "bucket": "动力电池/储能",
      "subcategory": "动力电池/储能",
      "old_report_status": "无旧报告",
      "reason": "动力储能电池样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P1",
      "code": "688008",
      "name": "澜起科技",
      "bucket": "半导体",
      "subcategory": "半导体",
      "old_report_status": "无旧报告",
      "reason": "内存接口芯片与AI服务器链样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P1",
      "code": "688347",
      "name": "华虹公司",
      "bucket": "半导体",
      "subcategory": "半导体",
      "old_report_status": "无旧报告",
      "reason": "特色工艺晶圆制造样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P1",
      "code": "688981",
      "name": "中芯国际",
      "bucket": "半导体",
      "subcategory": "半导体",
      "old_report_status": "无旧报告",
      "reason": "晶圆制造核心样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P1",
      "code": "300144",
      "name": "宋城演艺",
      "bucket": "商贸零售 / 社服",
      "subcategory": "旅游 / 景区",
      "old_report_status": "需新增报告",
      "reason": "旅游演艺样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P1",
      "code": "600258",
      "name": "首旅酒店",
      "bucket": "商贸零售 / 社服",
      "subcategory": "酒店",
      "old_report_status": "需新增报告",
      "reason": "酒店补充样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P1",
      "code": "600600",
      "name": "青岛啤酒",
      "bucket": "商贸零售 / 社服",
      "subcategory": "消费食品 / 啤酒",
      "old_report_status": "需新增报告",
      "reason": "消费白马交叉样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P1",
      "code": "600859",
      "name": "王府井",
      "bucket": "商贸零售 / 社服",
      "subcategory": "百货 / 零售",
      "old_report_status": "需新增报告",
      "reason": "百货和免税补充样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P1",
      "code": "601933",
      "name": "永辉超市",
      "bucket": "商贸零售 / 社服",
      "subcategory": "超市 / 零售",
      "old_report_status": "需新增报告",
      "reason": "超市零售样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P1",
      "code": "603711",
      "name": "香飘飘",
      "bucket": "商贸零售 / 社服",
      "subcategory": "消费食品 / 饮料",
      "old_report_status": "需新增报告",
      "reason": "消费品样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P1",
      "code": "001979",
      "name": "招商蛇口",
      "bucket": "地产 / 建筑建材",
      "subcategory": "房地产开发",
      "old_report_status": "需新增报告",
      "reason": "地产开发和园区代表公司",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P1",
      "code": "600048",
      "name": "保利发展",
      "bucket": "地产 / 建筑建材",
      "subcategory": "房地产开发",
      "old_report_status": "需新增报告",
      "reason": "央企地产代表公司",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P1",
      "code": "600585",
      "name": "海螺水泥",
      "bucket": "地产 / 建筑建材",
      "subcategory": "建材 / 水泥玻璃",
      "old_report_status": "需新增报告",
      "reason": "水泥行业龙头样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P1",
      "code": "601668",
      "name": "中国建筑",
      "bucket": "地产 / 建筑建材",
      "subcategory": "建筑工程 / 基建",
      "old_report_status": "需新增报告",
      "reason": "建筑央企核心样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P1",
      "code": "600438",
      "name": "通威股份",
      "bucket": "新能源发电",
      "subcategory": "新能源发电",
      "old_report_status": "无旧报告",
      "reason": "硅料与电池片周期样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P1",
      "code": "601012",
      "name": "隆基绿能",
      "bucket": "新能源发电",
      "subcategory": "新能源发电",
      "old_report_status": "无旧报告",
      "reason": "光伏硅片组件龙头样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P1",
      "code": "688223",
      "name": "晶科能源",
      "bucket": "新能源发电",
      "subcategory": "新能源发电",
      "old_report_status": "无旧报告",
      "reason": "光伏组件全球化样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P1",
      "code": "002747",
      "name": "埃斯顿",
      "bucket": "机器人/自动化",
      "subcategory": "机器人/自动化",
      "old_report_status": "有旧报告",
      "reason": "工业机器人本体样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P1",
      "code": "603728",
      "name": "鸣志电器",
      "bucket": "机器人/自动化",
      "subcategory": "机器人/自动化",
      "old_report_status": "有旧报告",
      "reason": "空心杯电机与运动控制样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P1",
      "code": "688017",
      "name": "绿的谐波",
      "bucket": "机器人/自动化",
      "subcategory": "机器人/自动化",
      "old_report_status": "无旧报告",
      "reason": "谐波减速器样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P1",
      "code": "300070",
      "name": "碧水源",
      "bucket": "环保 / 水务固废",
      "subcategory": "水务 / 污水处理",
      "old_report_status": "需新增报告",
      "reason": "膜法水处理样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P1",
      "code": "003816",
      "name": "中国广核",
      "bucket": "电力与公用事业",
      "subcategory": "核电",
      "old_report_status": "需新增报告",
      "reason": "核电运营代表公司",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P1",
      "code": "601985",
      "name": "中国核电",
      "bucket": "电力与公用事业",
      "subcategory": "核电",
      "old_report_status": "需新增报告",
      "reason": "核电运营代表公司",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P1",
      "code": "002563",
      "name": "森马服饰",
      "bucket": "纺服轻工",
      "subcategory": "服装 / 纺织",
      "old_report_status": "需新增报告",
      "reason": "休闲服饰样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P1",
      "code": "600398",
      "name": "海澜之家",
      "bucket": "纺服轻工",
      "subcategory": "服装 / 纺织",
      "old_report_status": "需新增报告",
      "reason": "服装零售代表样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P1",
      "code": "603816",
      "name": "顾家家居",
      "bucket": "纺服轻工",
      "subcategory": "家居 / 轻工制造",
      "old_report_status": "需新增报告",
      "reason": "软体家居样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P1",
      "code": "603833",
      "name": "欧派家居",
      "bucket": "纺服轻工",
      "subcategory": "家居 / 轻工制造",
      "old_report_status": "需新增报告",
      "reason": "定制家居样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P1",
      "code": "002230",
      "name": "科大讯飞",
      "bucket": "计算机 / 软件服务",
      "subcategory": "AI应用 / 大模型",
      "old_report_status": "需新增报告",
      "reason": "AI应用代表样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P1",
      "code": "300454",
      "name": "深信服",
      "bucket": "计算机 / 软件服务",
      "subcategory": "网络安全 / 信创",
      "old_report_status": "需新增报告",
      "reason": "补齐网络安全头部样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "下一批80-120候选池",
      "priority": "P1",
      "code": "688111",
      "name": "金山办公",
      "bucket": "计算机 / 软件服务",
      "subcategory": "办公软件 / AI应用",
      "old_report_status": "需新增报告",
      "reason": "补齐办公软件和AI应用头部样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P1",
      "code": "601288",
      "name": "农业银行",
      "bucket": "金融",
      "subcategory": "金融",
      "old_report_status": "有旧报告",
      "reason": "大行高股息样本",
      "status": "已接入分类树",
      "phase": "已完成"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P2",
      "code": "002236",
      "name": "大华股份",
      "bucket": "AI视觉",
      "subcategory": "AI视觉",
      "old_report_status": "有旧报告",
      "reason": "视觉AI与安防修复样本",
      "status": "后续种子池",
      "phase": "后续扩容"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P2",
      "code": "002415",
      "name": "海康威视",
      "bucket": "AI视觉",
      "subcategory": "AI视觉",
      "old_report_status": "有旧报告",
      "reason": "视觉AI与安防龙头样本",
      "status": "后续种子池",
      "phase": "后续扩容"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P2",
      "code": "002074",
      "name": "国轩高科",
      "bucket": "动力电池/储能",
      "subcategory": "动力电池/储能",
      "old_report_status": "无旧报告",
      "reason": "动力电池二线龙头样本",
      "status": "后续种子池",
      "phase": "后续扩容"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P2",
      "code": "300207",
      "name": "欣旺达",
      "bucket": "动力电池/储能",
      "subcategory": "动力电池/储能",
      "old_report_status": "无旧报告",
      "reason": "消费电池与动力电池样本",
      "status": "后续种子池",
      "phase": "后续扩容"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P2",
      "code": "301308",
      "name": "江波龙",
      "bucket": "半导体",
      "subcategory": "半导体",
      "old_report_status": "无旧报告",
      "reason": "存储品牌与模组样本",
      "status": "后续种子池",
      "phase": "后续扩容"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P2",
      "code": "688525",
      "name": "佰维存储",
      "bucket": "半导体",
      "subcategory": "半导体",
      "old_report_status": "无旧报告",
      "reason": "存储模组与AI存储弹性样本",
      "status": "后续种子池",
      "phase": "后续扩容"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P2",
      "code": "688037",
      "name": "芯源微",
      "bucket": "半导体设备",
      "subcategory": "半导体设备",
      "old_report_status": "无旧报告",
      "reason": "涂胶显影与清洗设备样本",
      "status": "后续种子池",
      "phase": "后续扩容"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P2",
      "code": "688082",
      "name": "盛美上海",
      "bucket": "半导体设备",
      "subcategory": "半导体设备",
      "old_report_status": "无旧报告",
      "reason": "清洗设备平台样本",
      "status": "后续种子池",
      "phase": "后续扩容"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P2",
      "code": "688120",
      "name": "华海清科",
      "bucket": "半导体设备",
      "subcategory": "半导体设备",
      "old_report_status": "无旧报告",
      "reason": "CMP设备与国产替代样本",
      "status": "后续种子池",
      "phase": "后续扩容"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P2",
      "code": "002179",
      "name": "中航光电",
      "bucket": "国防军工与航空航天",
      "subcategory": "国防军工与航空航天",
      "old_report_status": "无旧报告",
      "reason": "军工连接器样本",
      "status": "后续种子池",
      "phase": "后续扩容"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P2",
      "code": "300699",
      "name": "光威复材",
      "bucket": "国防军工与航空航天",
      "subcategory": "国防军工与航空航天",
      "old_report_status": "无旧报告",
      "reason": "碳纤维材料样本",
      "status": "后续种子池",
      "phase": "后续扩容"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P2",
      "code": "600845",
      "name": "宝信软件",
      "bucket": "工业软件",
      "subcategory": "工业软件",
      "old_report_status": "无旧报告",
      "reason": "工业软件与IDC样本",
      "status": "后续种子池",
      "phase": "后续扩容"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P2",
      "code": "688599",
      "name": "天合光能",
      "bucket": "新能源发电",
      "subcategory": "新能源发电",
      "old_report_status": "无旧报告",
      "reason": "光伏组件与储能样本",
      "status": "后续种子池",
      "phase": "后续扩容"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P2",
      "code": "002472",
      "name": "双环传动",
      "bucket": "机器人/自动化",
      "subcategory": "机器人/自动化",
      "old_report_status": "有旧报告",
      "reason": "齿轮传动与机器人减速器样本",
      "status": "后续种子池",
      "phase": "后续扩容"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P2",
      "code": "002896",
      "name": "中大力德",
      "bucket": "机器人/自动化",
      "subcategory": "机器人/自动化",
      "old_report_status": "无旧报告",
      "reason": "减速器与小型传动样本",
      "status": "后续种子池",
      "phase": "后续扩容"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P2",
      "code": "002979",
      "name": "雷赛智能",
      "bucket": "机器人/自动化",
      "subcategory": "机器人/自动化",
      "old_report_status": "有旧报告",
      "reason": "运动控制样本",
      "status": "后续种子池",
      "phase": "后续扩容"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P2",
      "code": "603662",
      "name": "柯力传感",
      "bucket": "机器人/自动化",
      "subcategory": "机器人/自动化",
      "old_report_status": "无旧报告",
      "reason": "传感器与力控样本",
      "status": "后续种子池",
      "phase": "后续扩容"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P2",
      "code": "688320",
      "name": "禾川科技",
      "bucket": "机器人/自动化",
      "subcategory": "机器人/自动化",
      "old_report_status": "无旧报告",
      "reason": "伺服与工业控制样本",
      "status": "后续种子池",
      "phase": "后续扩容"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P2",
      "code": "600809",
      "name": "山西汾酒",
      "bucket": "消费白马",
      "subcategory": "消费白马",
      "old_report_status": "无旧报告",
      "reason": "次高端白酒样本",
      "status": "后续种子池",
      "phase": "后续扩容"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P2",
      "code": "600887",
      "name": "伊利股份",
      "bucket": "消费白马",
      "subcategory": "消费白马",
      "old_report_status": "有旧报告",
      "reason": "乳制品龙头样本",
      "status": "后续种子池",
      "phase": "后续扩容"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P2",
      "code": "603288",
      "name": "海天味业",
      "bucket": "消费白马",
      "subcategory": "消费白马",
      "old_report_status": "有旧报告",
      "reason": "调味品龙头修复样本",
      "status": "后续种子池",
      "phase": "后续扩容"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P2",
      "code": "600019",
      "name": "宝钢股份",
      "bucket": "资源周期",
      "subcategory": "资源周期",
      "old_report_status": "无旧报告",
      "reason": "钢铁龙头与分红样本",
      "status": "后续种子池",
      "phase": "后续扩容"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P2",
      "code": "600028",
      "name": "中国石化",
      "bucket": "资源周期",
      "subcategory": "资源周期",
      "old_report_status": "有旧报告",
      "reason": "炼化央企样本",
      "status": "后续种子池",
      "phase": "后续扩容"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P2",
      "code": "600111",
      "name": "北方稀土",
      "bucket": "资源周期",
      "subcategory": "资源周期",
      "old_report_status": "有旧报告",
      "reason": "稀土资源样本",
      "status": "后续种子池",
      "phase": "后续扩容"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P2",
      "code": "601225",
      "name": "陕西煤业",
      "bucket": "资源周期",
      "subcategory": "资源周期",
      "old_report_status": "无旧报告",
      "reason": "煤炭龙头样本",
      "status": "后续种子池",
      "phase": "后续扩容"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P2",
      "code": "601600",
      "name": "中国铝业",
      "bucket": "资源周期",
      "subcategory": "资源周期",
      "old_report_status": "有旧报告",
      "reason": "铝周期央企样本",
      "status": "后续种子池",
      "phase": "后续扩容"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P2",
      "code": "601336",
      "name": "新华保险",
      "bucket": "金融",
      "subcategory": "金融",
      "old_report_status": "有旧报告",
      "reason": "寿险弹性样本",
      "status": "后续种子池",
      "phase": "后续扩容"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P2",
      "code": "601601",
      "name": "中国太保",
      "bucket": "金融",
      "subcategory": "金融",
      "old_report_status": "有旧报告",
      "reason": "保险龙头对比样本",
      "status": "后续种子池",
      "phase": "后续扩容"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P2",
      "code": "601988",
      "name": "中国银行",
      "bucket": "金融",
      "subcategory": "金融",
      "old_report_status": "有旧报告",
      "reason": "大行高股息样本",
      "status": "后续种子池",
      "phase": "后续扩容"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P2",
      "code": "002709",
      "name": "天赐材料",
      "bucket": "锂电材料",
      "subcategory": "锂电材料",
      "old_report_status": "有旧报告",
      "reason": "电解液材料样本",
      "status": "后续种子池",
      "phase": "后续扩容"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P2",
      "code": "002812",
      "name": "恩捷股份",
      "bucket": "锂电材料",
      "subcategory": "锂电材料",
      "old_report_status": "有旧报告",
      "reason": "隔膜材料样本",
      "status": "后续种子池",
      "phase": "后续扩容"
    },
    {
      "source": "第三批扩容候选池",
      "priority": "P2",
      "code": "603659",
      "name": "璞泰来",
      "bucket": "锂电材料",
      "subcategory": "锂电材料",
      "old_report_status": "有旧报告",
      "reason": "负极与隔膜设备样本",
      "status": "后续种子池",
      "phase": "后续扩容"
    }
  ]
};
